/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: StudioServerPlaceCache.cpp
// Started by: Hattozo
// Started on: 8/15/2026
// Description: Content-addressed cache and atomic publication for launch-only Studio places.
// (Disclaimer: This code was generated by GPT 5.6 Sol and Claude Opus 5.)
#include <NoobWarrior/Roblox/FileFormat/StudioServerPlaceCache.h>
#include <NoobWarrior/Log.h>
#include <NoobWarrior/Roblox/FileFormat/StudioServerPlace.h>

#include <openssl/evp.h>

#include <algorithm>
#include <array>
#include <atomic>
#include <charconv>
#include <chrono>
#include <fstream>
#include <iomanip>
#include <memory>
#include <mutex>
#include <sstream>
#include <system_error>
#include <vector>

#if defined(_WIN32)
#include <windows.h>
#else
#include <unistd.h>
#endif

namespace NoobWarrior {
namespace {
constexpr std::string_view kCacheDomain = "noobWarrior/studio-server-place-cache";
// A prepared place is only worth keeping while its plugin set and Studio build stay put. Every hit
// touches its entry, so anything untouched for this long belongs to a configuration the user has
// moved on from.
constexpr auto kCacheEntryLifetime = std::chrono::hours(24 * 14);
std::atomic_uint64_t gTemporaryCounter {0};

void SetError(std::string *error, std::string message) {
    if (error != nullptr)
        *error = std::move(message);
}

bool IsHexDigest(std::string_view value) {
    return value.size() == 64 && std::ranges::all_of(value, [](unsigned char character) {
        return (character >= '0' && character <= '9') ||
               (character >= 'a' && character <= 'f');
    });
}

bool DigestBytes(EVP_MD_CTX *context, const void *data, size_t size) {
    return size == 0 || EVP_DigestUpdate(context, data, size) == 1;
}

bool DigestUint64(EVP_MD_CTX *context, uint64_t value) {
    std::array<unsigned char, sizeof(value)> encoded {};
    for (size_t index = 0; index < encoded.size(); ++index)
        encoded[index] = static_cast<unsigned char>(value >> (index * 8));
    return DigestBytes(context, encoded.data(), encoded.size());
}

bool DigestString(EVP_MD_CTX *context, std::string_view value) {
    return DigestUint64(context, value.size()) &&
           DigestBytes(context, value.data(), value.size());
}

std::string FinishDigest(EVP_MD_CTX *context) {
    std::array<unsigned char, EVP_MAX_MD_SIZE> digest {};
    unsigned int digestSize = 0;
    if (EVP_DigestFinal_ex(context, digest.data(), &digestSize) != 1 || digestSize != 32)
        return {};

    std::ostringstream encoded;
    encoded << std::hex << std::setfill('0');
    for (unsigned int index = 0; index < digestSize; ++index)
        encoded << std::setw(2) << static_cast<unsigned int>(digest[index]);
    return encoded.str();
}

uint64_t ProcessId() {
#if defined(_WIN32)
    return GetCurrentProcessId();
#else
    return static_cast<uint64_t>(getpid());
#endif
}

std::filesystem::path TemporaryPathFor(const std::filesystem::path &destination) {
    std::filesystem::path temporary = destination;
    temporary += ".tmp-" + std::to_string(ProcessId()) + "-" +
                 std::to_string(gTemporaryCounter.fetch_add(1, std::memory_order_relaxed));
    return temporary;
}

bool ReplaceAtomically(const std::filesystem::path &temporary,
                       const std::filesystem::path &destination,
                       std::string *error) {
#if defined(_WIN32)
    if (MoveFileExW(temporary.c_str(), destination.c_str(),
                    MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
        return true;
    }
    SetError(error, "could not atomically replace " + destination.string() +
                    " (Windows error " + std::to_string(GetLastError()) + ")");
    return false;
#else
    std::error_code code;
    std::filesystem::rename(temporary, destination, code);
    if (!code)
        return true;
    SetError(error, "could not atomically replace " + destination.string() +
                    ": " + code.message());
    return false;
#endif
}

bool WriteAtomically(const std::filesystem::path &destination,
                     std::span<const unsigned char> data, std::string *error) {
    std::error_code code;
    const std::filesystem::path parent = destination.parent_path();
    if (!parent.empty()) {
        std::filesystem::create_directories(parent, code);
        if (code) {
            SetError(error, "could not create " + parent.string() + ": " + code.message());
            return false;
        }
    }

    const std::filesystem::path temporary = TemporaryPathFor(destination);
    {
        std::ofstream stream(temporary, std::ios::binary | std::ios::trunc);
        if (!stream.is_open()) {
            SetError(error, "could not open " + temporary.string() + " for writing");
            return false;
        }
        stream.write(reinterpret_cast<const char *>(data.data()),
                     static_cast<std::streamsize>(data.size()));
        stream.close();
        if (!stream) {
            std::filesystem::remove(temporary, code);
            SetError(error, "could not completely write " + temporary.string());
            return false;
        }
    }

    if (ReplaceAtomically(temporary, destination, error))
        return true;
    std::filesystem::remove(temporary, code);
    return false;
}

std::filesystem::path SizePath(const std::filesystem::path &cachePath) {
    std::filesystem::path size = cachePath;
    size += ".size";
    return size;
}

// Entries are published by an atomic rename, so a short read means something outside noobWarrior
// truncated one. Recording the expected length costs a single stat on the hot path and turns that
// case into a rebuild instead of a server.rbxl that fails to load on every launch from then on.
bool ReadExpectedSize(const std::filesystem::path &cachePath, uint64_t &size) {
    std::ifstream stream(SizePath(cachePath), std::ios::binary);
    std::string line;
    if (!std::getline(stream, line))
        return false;
    const auto parsed = std::from_chars(line.data(), line.data() + line.size(), size);
    return parsed.ec == std::errc {} && parsed.ptr == line.data() + line.size() && size > 0;
}

enum class CopyResponse {
    Success,
    SourceUnavailable,
    Failed,
};

CopyResponse CopyAtomically(const std::filesystem::path &source,
                            const std::filesystem::path &destination,
                            std::string *error) {
    std::error_code code;
    const std::filesystem::path parent = destination.parent_path();
    if (!parent.empty()) {
        std::filesystem::create_directories(parent, code);
        if (code) {
            SetError(error, "could not create " + parent.string() + ": " + code.message());
            return CopyResponse::Failed;
        }
    }

    const std::filesystem::path temporary = TemporaryPathFor(destination);
    std::filesystem::copy_file(source, temporary,
                               std::filesystem::copy_options::overwrite_existing, code);
    if (code) {
        std::error_code ignored;
        std::filesystem::remove(temporary, ignored);
        if (!std::filesystem::exists(source, ignored)) {
            SetError(error, "cached Studio server place disappeared before publication");
            return CopyResponse::SourceUnavailable;
        }
        SetError(error, "could not copy the cached Studio server place: " + code.message());
        return CopyResponse::Failed;
    }

    if (ReplaceAtomically(temporary, destination, error))
        return CopyResponse::Success;
    std::filesystem::remove(temporary, code);
    return CopyResponse::Failed;
}

// Studio reads one fixed server.rbxl path, so concurrent noobWarrior processes are serialized
// here. Nothing else in this file needs a lock: entries are content-addressed, so racing builders
// produce identical bytes and every write lands through an atomic rename.
class PublishLock {
public:
    PublishLock() {
#if defined(_WIN32)
        mMutex = CreateMutexW(nullptr, FALSE,
                              L"Local\\noobWarrior.StudioServerPlace.Publish.v1");
        if (mMutex == nullptr)
            return;
        const DWORD result = WaitForSingleObject(mMutex, kTimeoutMilliseconds);
        mLocked = result == WAIT_OBJECT_0 || result == WAIT_ABANDONED;
#else
        mLock = std::unique_lock<std::mutex>(Mutex());
        mLocked = true;
#endif
    }

    ~PublishLock() {
#if defined(_WIN32)
        if (mLocked)
            ReleaseMutex(mMutex);
        if (mMutex != nullptr)
            CloseHandle(mMutex);
#endif
    }

    bool Locked() const {
        return mLocked;
    }

private:
#if defined(_WIN32)
    // A wedged peer must not hang the launch forever; the caller reports an ordinary failure.
    static constexpr DWORD kTimeoutMilliseconds = 30000;
    HANDLE mMutex {nullptr};
#else
    static std::mutex &Mutex() {
        static std::mutex mutex;
        return mutex;
    }
    std::unique_lock<std::mutex> mLock;
#endif
    bool mLocked {false};
};

// A cache entry is a place plus its ".size" sidecar, and only the place is touched on a hit, so
// the pair is aged as one: judging the two files separately drops the sidecar of a still-hot
// entry, and an entry without its sidecar reads back as a miss (ReadExpectedSize) and is rebuilt
// on every launch from then on.
void PruneCache(const std::filesystem::path &cacheDirectory,
                const std::filesystem::path &currentEntry) {
    const auto cutoff = std::filesystem::file_time_type::clock::now() - kCacheEntryLifetime;
    std::vector<std::filesystem::path> stale;
    std::error_code code;
    std::filesystem::directory_iterator iterator(cacheDirectory, code);
    const std::filesystem::directory_iterator end;
    for (; !code && iterator != end; iterator.increment(code)) {
        const std::filesystem::directory_entry &entry = *iterator;
        if (entry.path() == currentEntry || entry.path() == SizePath(currentEntry))
            continue;
        std::error_code entryError;
        if (!entry.is_regular_file(entryError) || entryError)
            continue;
        // A sidecar leaves with the place it belongs to; one whose place is already gone ages on
        // its own timestamp so an orphan cannot outlive the cache lifetime either.
        std::filesystem::path governing = entry.path();
        if (governing.extension() == ".size") {
            std::filesystem::path place = governing;
            place.replace_extension();
            std::error_code placeError;
            if (std::filesystem::exists(place, placeError) && !placeError)
                governing = std::move(place);
        }
        const auto modified = std::filesystem::last_write_time(governing, entryError);
        if (!entryError && modified < cutoff)
            stale.push_back(entry.path());
    }
    for (const std::filesystem::path &path : stale)
        std::filesystem::remove(path, code);
}
} // namespace

std::string ComputeStudioServerPlaceCacheKey(
    std::string_view sourceSha256, const StudioServerBootstrap &bootstrap,
    std::string_view studioFingerprint, uint32_t schemaVersion) {
    using Context = std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)>;
    Context context(EVP_MD_CTX_new(), EVP_MD_CTX_free);
    if (!context || EVP_DigestInit_ex(context.get(), EVP_sha256(), nullptr) != 1 ||
        !DigestString(context.get(), kCacheDomain) ||
        !DigestUint64(context.get(), schemaVersion) ||
        !DigestString(context.get(), sourceSha256) ||
        !DigestString(context.get(), studioFingerprint) ||
        !DigestUint64(context.get(), bootstrap.Plans.size()) ||
        !DigestUint64(context.get(), bootstrap.Scripts.size()) ||
        !DigestUint64(context.get(), bootstrap.Models.size())) {
        return {};
    }

    for (const std::string &plan : bootstrap.Plans) {
        if (!DigestString(context.get(), plan))
            return {};
    }
    for (const StudioServerScript &script : bootstrap.Scripts) {
        const unsigned char disabled = script.Disabled ? 1 : 0;
        if (!DigestString(context.get(), script.Key) ||
            !DigestString(context.get(), script.ClassName) ||
            !DigestString(context.get(), script.Source) ||
            !DigestString(context.get(), script.ParentClassName) ||
            !DigestBytes(context.get(), &disabled, sizeof(disabled))) {
            return {};
        }
    }
    for (const StudioServerModel &model : bootstrap.Models) {
        if (!DigestString(context.get(), model.SourcePath) ||
            !DigestUint64(context.get(), model.ParentPath.size())) {
            return {};
        }
        for (const StudioServerModelPathElement &element : model.ParentPath) {
            if (!DigestString(context.get(), element.Name) ||
                !DigestString(context.get(), element.ClassName)) {
                return {};
            }
        }
        if (!DigestString(context.get(), model.SingleRootName) ||
            !DigestUint64(context.get(), model.Data.size()) ||
            !DigestBytes(context.get(), model.Data.data(), model.Data.size())) {
            return {};
        }
    }
    return FinishDigest(context.get());
}

std::string ComputeStudioServerPlaceSourceHash(std::span<const unsigned char> place) {
    using Context = std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)>;
    Context context(EVP_MD_CTX_new(), EVP_MD_CTX_free);
    if (!context || EVP_DigestInit_ex(context.get(), EVP_sha256(), nullptr) != 1 ||
        !DigestBytes(context.get(), place.data(), place.size())) {
        return {};
    }
    return FinishDigest(context.get());
}

std::filesystem::path StudioServerPlaceCacheEntry(
    const std::filesystem::path &cacheDirectory, std::string_view cacheKey) {
    if (!IsHexDigest(cacheKey))
        return {};
    return cacheDirectory / (std::string(cacheKey) + ".rbxl");
}

StudioServerPlaceCacheResponse PublishCachedStudioServerPlace(
    const std::filesystem::path &cacheDirectory, std::string_view cacheKey,
    const std::filesystem::path &launchPath, uint64_t *placeBytes,
    std::string *error,
    const StudioServerPlacePublishCallback &publishCallback) {
    const std::filesystem::path cachePath =
        StudioServerPlaceCacheEntry(cacheDirectory, cacheKey);
    if (cachePath.empty()) {
        SetError(error, "invalid Studio server place cache key");
        return StudioServerPlaceCacheResponse::Failed;
    }

    uint64_t expectedSize = 0;
    if (!ReadExpectedSize(cachePath, expectedSize))
        return StudioServerPlaceCacheResponse::Miss;
    std::error_code code;
    if (std::filesystem::file_size(cachePath, code) != expectedSize || code)
        return StudioServerPlaceCacheResponse::Miss;
    if (publishCallback)
        publishCallback(expectedSize);

    PublishLock lock;
    if (!lock.Locked()) {
        SetError(error, "could not lock the Studio server launch path");
        return StudioServerPlaceCacheResponse::Failed;
    }
    const CopyResponse copied = CopyAtomically(cachePath, launchPath, error);
    if (copied == CopyResponse::SourceUnavailable)
        return StudioServerPlaceCacheResponse::Miss;
    if (copied != CopyResponse::Success)
        return StudioServerPlaceCacheResponse::Failed;

    if (placeBytes != nullptr)
        *placeBytes = expectedSize;
    // Both halves of the entry are touched, so a prune that still ages files independently -- an
    // older noobWarrior sharing this cache directory, or the user's own cleanup -- cannot take
    // the size record of an entry that is being hit.
    const auto touched = std::filesystem::file_time_type::clock::now();
    std::filesystem::last_write_time(cachePath, touched, code);
    std::filesystem::last_write_time(SizePath(cachePath), touched, code);
    return StudioServerPlaceCacheResponse::Hit;
}

bool StoreStudioServerPlaceCache(
    const std::filesystem::path &cacheDirectory, std::string_view cacheKey,
    std::span<const unsigned char> place, std::string *error) {
    const std::filesystem::path cachePath =
        StudioServerPlaceCacheEntry(cacheDirectory, cacheKey);
    if (cachePath.empty()) {
        SetError(error, "invalid Studio server place cache key");
        return false;
    }
    if (place.empty()) {
        SetError(error, "refusing to cache an empty Studio server place");
        return false;
    }
    if (!WriteAtomically(cachePath, place, error))
        return false;

    // The size record lands second, so an interrupted store reads back as a miss rather than as a
    // complete entry.
    const std::string size = std::to_string(place.size()) + "\n";
    const std::span<const unsigned char> sizeBytes(
        reinterpret_cast<const unsigned char *>(size.data()), size.size());
    // A size record that never lands leaves an entry that reads back as a miss and is pruned by
    // age, which is the whole reason it is written second. Deleting the place here instead would
    // let one failed store destroy an entry a concurrent builder had just published correctly.
    if (!WriteAtomically(SizePath(cachePath), sizeBytes, error))
        return false;

    PruneCache(cacheDirectory, cachePath);
    return true;
}

bool PublishStudioServerPlace(
    const std::filesystem::path &launchPath, std::span<const unsigned char> place,
    std::string *error) {
    PublishLock lock;
    if (!lock.Locked()) {
        SetError(error, "could not lock the Studio server launch path");
        return false;
    }
    return WriteAtomically(launchPath, place, error);
}

StudioServerPlacePreparationResponse PrepareStudioServerPlace(
    std::string_view sourceSha256, const StudioServerBootstrap &bootstrap,
    std::string_view studioFingerprint, const std::filesystem::path &cacheDirectory,
    const std::filesystem::path &launchPath, const StudioServerPlaceLoader &loader,
    uint64_t *placeBytes, std::string *error,
    const StudioServerPlacePublishCallback &publishCallback) {
    if (error != nullptr)
        error->clear();
    const std::string cacheKey = ComputeStudioServerPlaceCacheKey(
        sourceSha256, bootstrap, studioFingerprint);
    if (cacheKey.empty()) {
        SetError(error, "could not compute Studio server place cache key");
        return StudioServerPlacePreparationResponse::Failed;
    }

    const StudioServerPlaceCacheResponse cached = PublishCachedStudioServerPlace(
        cacheDirectory, cacheKey, launchPath, placeBytes, error, publishCallback);
    if (cached == StudioServerPlaceCacheResponse::Hit)
        return StudioServerPlacePreparationResponse::CacheHit;
    if (cached == StudioServerPlaceCacheResponse::Failed)
        return StudioServerPlacePreparationResponse::Failed;

    // A miss simply means this process builds the entry. Concurrent builders of the same key
    // produce identical bytes, so the loser's work is redundant rather than harmful.
    if (error != nullptr)
        error->clear();
    std::vector<unsigned char> place;
    if (!loader || !loader(place, error) || place.empty()) {
        if (error != nullptr && error->empty())
            *error = "could not load Studio server place";
        return StudioServerPlacePreparationResponse::Failed;
    }
    const std::string actualSourceHash = ComputeStudioServerPlaceSourceHash(place);
    if (actualSourceHash.empty() || actualSourceHash != sourceSha256) {
        SetError(error, "Studio server place bytes do not match AssetData.DataHash");
        return StudioServerPlacePreparationResponse::Failed;
    }

    if (!bootstrap.Empty() && !InjectStudioServerBootstrap(place, bootstrap, error))
        return StudioServerPlacePreparationResponse::Failed;

    if (publishCallback)
        publishCallback(place.size());
    std::string cacheError;
    if (!StoreStudioServerPlaceCache(cacheDirectory, cacheKey, place, &cacheError)) {
        // Not fatal -- the launch goes ahead with the place this process just built. It is still
        // worth printing: a store that keeps failing makes every single launch pay for a rebuild.
        Out("StudioServerPlaceCache",
            "WARNING! Could not cache the prepared Studio server place: {}",
            cacheError.empty() ? std::string("unknown error") : cacheError);
    }

    if (error != nullptr)
        error->clear();
    if (!PublishStudioServerPlace(launchPath, place, error))
        return StudioServerPlacePreparationResponse::Failed;
    if (placeBytes != nullptr)
        *placeBytes = place.size();
    return StudioServerPlacePreparationResponse::Built;
}
} // namespace NoobWarrior
