/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: StudioServerPlace.cpp
// Description: Mounts every plugin's tree into Studio's server place copy.
// (Disclaimer: This code was generated by GPT 5.6 Sol and Claude Opus 5.)
#include <NoobWarrior/Roblox/FileFormat/StudioServerPlace.h>

#include <NoobWarrior/PluginTreeMaterializer.h>
#include <NoobWarrior/Log.h>
#include <NoobWarrior/Roblox/FileFormat/BinaryFormat/BinaryRobloxFile.h>
#include <NoobWarrior/Roblox/FileFormat/RobloxFile.h>

#include <nlohmann/json.hpp>

#include <memory>
#include <vector>

namespace NoobWarrior {
namespace {
// Every .rbxm the plan walker met produced exactly one "model" node, and
// FinalizePlan in PluginDataModel.cpp rewrote that node's kind to
// "embeddedModel" in place. PluginManager::BuildStudioServerBootstrap flattens every plugin's
// plans and models into two lists, so this count is all that is left of the association between
// a plan and the models that were built alongside it.
size_t CountEmbeddedModels(const nlohmann::json &node) {
    size_t total = 0;
    if (node.is_array()) {
        for (const nlohmann::json &child : node)
            total += CountEmbeddedModels(child);
        return total;
    }
    if (!node.is_object())
        return 0;
    // Read without json::value(), which throws when a key holds an unexpected type.
    const auto kind = node.find("kind");
    if (kind != node.end() && kind->is_string() && kind->get_ref<const std::string &>() ==
        "embeddedModel") {
        ++total;
    }
    const auto children = node.find("children");
    if (children != node.end())
        total += CountEmbeddedModels(*children);
    return total;
}

bool SpliceBinaryModel(Roblox::BinaryFormat::BinaryRobloxFile &binary,
                       const StudioServerModel &model, PluginMountResult &mounted,
                       std::string *error) {
    std::vector<Roblox::BinaryFormat::BinaryModelPathElement> parentPath;
    parentPath.reserve(model.ParentPath.size());
    for (const StudioServerModelPathElement &element : model.ParentPath)
        parentPath.push_back({element.Name, element.ClassName});
    size_t replaced = 0;
    if (!binary.AppendBinaryModel(model.Data, parentPath, model.SingleRootName, error,
                                  &replaced)) {
        return false;
    }
    mounted.Replaced += static_cast<int>(replaced);
    return true;
}
} // namespace

bool InjectStudioServerBootstrap(std::vector<unsigned char> &place,
                                 const StudioServerBootstrap &bootstrap,
                                 std::string *error) {
    std::unique_ptr<Roblox::RobloxFile> file;
    const Roblox::FileResponse response = Roblox::RobloxFile::Open(file, place);
    if (response != Roblox::FileResponse::Success) {
        if (error != nullptr)
            *error = "could not deserialize Studio's server place";
        return false;
    }

    // Plugin content is written straight into the place, so the whole DataModel exists before the
    // engine runs a single script. That removes the ordering problem the old Lua bootstrap solved
    // by deferring activation.
    // Mounting works on the shared Instance tree, so an .rbxlx place stays XML and an .rbxl
    // place stays binary -- Save() is virtual and each keeps its own encoding.
    {
        PluginTreeMaterializer materializer(file.get());
        PluginMountResult mounted;

        // Embedded .rbxm blobs can only be spliced into a binary place.
        auto *binary = dynamic_cast<Roblox::BinaryFormat::BinaryRobloxFile *>(file.get());
        if (binary == nullptr && !bootstrap.Models.empty()) {
            if (error != nullptr)
                *error = "binary plugin models require a binary Studio server place";
            return false;
        }

        // Every plan is parsed before anything is mounted, so a malformed one fails the launch
        // instead of leaving a half-mounted place behind.
        std::vector<nlohmann::json> plans;
        plans.reserve(bootstrap.Plans.size());
        std::vector<size_t> modelsPerPlan;
        modelsPerPlan.reserve(bootstrap.Plans.size());
        size_t describedModels = 0;
        for (const std::string &plan : bootstrap.Plans) {
            nlohmann::json parsed;
            try {
                parsed = nlohmann::json::parse(plan);
            } catch (const nlohmann::json::exception &exception) {
                if (error != nullptr)
                    *error = std::string("could not parse a plugin plan: ") + exception.what();
                return false;
            }
            const size_t models = CountEmbeddedModels(parsed);
            describedModels += models;
            modelsPerPlan.push_back(models);
            plans.push_back(std::move(parsed));
        }

        // The per-plan counts only carve up the flat model list when every model still has its
        // node. If they disagree the association is unknown, so the models all go in after the
        // plans -- the old order, which can let one plugin's model outlive a later plugin's plan.
        const bool grouped = describedModels == bootstrap.Models.size();
        if (!grouped && !bootstrap.Models.empty()) {
            Out("StudioServerPlace",
                "WARNING! {} plugin plans describe {} embedded models but {} were built; "
                "splicing every model after every plan",
                plans.size(), describedModels, bootstrap.Models.size());
        }

        // Plans arrive in mount order; a later plugin replaces what an earlier one defined
        // (PluginTreeMaterializer.h:42-47). A model is spliced right after the plan it came from
        // rather than after every plan, because AppendBinaryModel destroys same-named children at
        // its destination (BinaryRobloxFile.cpp:853-861) -- deferring all of them would let an
        // earlier plugin's .rbxm take out a subtree a later plugin had already mounted.
        size_t nextModel = 0;
        for (size_t index = 0; index < plans.size(); ++index) {
            if (!materializer.Mount(plans[index], mounted, error))
                return false;
            if (!grouped)
                continue;
            for (const size_t end = nextModel + modelsPerPlan[index]; nextModel < end;
                 ++nextModel) {
                if (!SpliceBinaryModel(*binary, bootstrap.Models[nextModel], mounted, error))
                    return false;
            }
        }
        for (; nextModel < bootstrap.Models.size(); ++nextModel) {
            if (!SpliceBinaryModel(*binary, bootstrap.Models[nextModel], mounted, error))
                return false;
        }

        // Reported once everything has landed: the models contribute replacements of their own,
        // so a summary printed before them counts too few.
        for (const std::string &warning : mounted.Warnings)
            Out("StudioServerPlace", "{}", warning);
        if (!bootstrap.Plans.empty() || !bootstrap.Models.empty()) {
            Out("StudioServerPlace",
                "Mounted {} plugin plans and {} embedded models: {} created, {} merged, "
                "{} replaced",
                bootstrap.Plans.size(), bootstrap.Models.size(), mounted.Created, mounted.Merged,
                mounted.Replaced);
        }
    }

    // engine_autorun scripts stay separate: they are untrusted plugin text and are added as their
    // own script instances rather than being folded into any generated source.
    std::vector<Roblox::LuaSourceContainerSpec> containers;
    containers.reserve(bootstrap.Scripts.size());
    for (const StudioServerScript &script : bootstrap.Scripts) {
        containers.push_back({
            script.ClassName,
            script.Key,
            script.Source,
            script.Disabled,
            script.ParentClassName,
        });
    }
    if (!containers.empty() && !file->AppendLuaSourceContainers(containers, error))
        return false;

    if (file->Save(place) != Roblox::FileResponse::Success) {
        if (error != nullptr) {
            *error = file->GetLastError().empty()
                ? "could not serialize Studio's server place"
                : file->GetLastError();
        }
        return false;
    }
    return true;
}

} // namespace NoobWarrior
