/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: PluginTreeMaterializer.cpp
// Started by: Hattozo
// Started on: 8/18/2025
// Description: Writes a plugin's Rojo tree straight into a place, replacing the Lua replay bootstrap.
// (Disclaimer: This code was generated by Claude Opus 5.)

#include <NoobWarrior/PluginTreeMaterializer.h>

#include <NoobWarrior/Roblox/FileFormat/BinaryFormat/BinaryRobloxFile.h>
#include <NoobWarrior/Roblox/FileFormat/Utility/Formatting.h>

#ifdef NOOBWARRIOR_HAVE_GENERATED_ROBLOX_API
#include <NoobWarrior/Roblox/FileFormat/Generated/Registry.h>
#endif

#include <algorithm>
#include <cstdint>
#include <format>
#include <optional>
#include <string>
#include <utility>
#include <vector>

using namespace NoobWarrior;
using namespace NoobWarrior::Roblox;
using namespace NoobWarrior::Roblox::DataTypes;
using json = nlohmann::json;

bool NoobWarrior::IsDataModelServiceClass(std::string_view className) {
#ifdef NOOBWARRIOR_HAVE_GENERATED_ROBLOX_API
    // The API dump tags every service class, so the generated registry answers this for all of
    // them rather than the handful a hand-kept list can hold. BinaryRobloxFile.cpp:741-753 keeps
    // a third copy of the fallback list below and should call this instead.
    if (const ClassDescriptor *descriptor = FindClass(className))
        return descriptor->IsService;
#endif
    // Without the generated registry only the services a place is likely to carry are known.
    static constexpr std::string_view kServices[] = {
        "Chat", "Lighting", "Players", "ReplicatedFirst", "ReplicatedStorage",
        "ServerScriptService", "ServerStorage", "SoundService", "StarterGui", "StarterPack",
        "StarterPlayer", "Teams", "TextChatService", "Workspace", "HttpService",
        "CollectionService", "RunService", "InsertService",
    };
    return std::find(std::begin(kServices), std::end(kServices), className) !=
        std::end(kServices);
}

namespace {
bool IsContainerClass(std::string_view className) {
    // Services and plain Folders accumulate contributions rather than being swapped out.
    // StarterPlayer's two script containers are not services but behave like them here.
    static constexpr std::string_view kContainers[] = {
        "Folder", "StarterPlayerScripts", "StarterCharacterScripts",
    };
    if (std::find(std::begin(kContainers), std::end(kContainers), className) !=
        std::end(kContainers)) {
        return true;
    }
    return NoobWarrior::IsDataModelServiceClass(className);
}

float Number(const json &value) {
    return value.is_number() ? value.get<float>() : 0.0f;
}

// True when value is the one-key object the plan builder writes a tagged value as.
bool IsPlanTag(const json &value, std::string_view tag) {
    return value.is_object() && value.size() == 1 && value.begin().key() == tag;
}

// The plan carries a bare JSON number wherever a .meta.json author wrote one, and JSON has a
// single number type, so integrality was standing in for the column's width: {"Transparency": 1}
// produced an Int column on a Float property. The generated registry states the declared type, so
// let it pick the width -- and nothing else. The dump is 0.735 while the engines this ships for
// are 0.463/0.574/0.729, so it never overrides a tag the plan states outright, and a property it
// does not describe falls back to integrality.
std::optional<PropertyType> NumericWidthFromRegistry(std::string_view className,
                                                     std::string_view propertyName) {
#ifdef NOOBWARRIOR_HAVE_GENERATED_ROBLOX_API
    if (className.empty() || propertyName.empty())
        return std::nullopt;
    const PropertyDescriptor *descriptor = FindProperty(className, propertyName);
    if (descriptor == nullptr || descriptor->Category != "Primitive")
        return std::nullopt;
    if (descriptor->Type == "int")
        return PropertyType::Int;
    if (descriptor->Type == "int64")
        return PropertyType::Int64;
    if (descriptor->Type == "float")
        return PropertyType::Float;
    if (descriptor->Type == "double")
        return PropertyType::Double;
#else
    (void) className;
    (void) propertyName;
#endif
    return std::nullopt;
}
} // namespace

bool NoobWarrior::ConvertPlanValue(const json &value, PropertyType &type, std::any &out,
                                   std::string_view className, std::string_view propertyName) {
    if (value.is_string()) {
        type = PropertyType::String;
        out = value.get<std::string>();
        return true;
    }
    if (value.is_boolean()) {
        type = PropertyType::Bool;
        out = value.get<bool>();
        return true;
    }
    if (value.is_number()) {
        type = NumericWidthFromRegistry(className, propertyName)
            .value_or(value.is_number_integer() ? PropertyType::Int : PropertyType::Float);
        switch (type) {
        case PropertyType::Int64:
            out = value.get<int64_t>();
            break;
        case PropertyType::Double:
            out = value.get<double>();
            break;
        case PropertyType::Int:
            out = static_cast<int32_t>(value.get<int64_t>());
            break;
        default:
            type = PropertyType::Float;
            out = value.get<float>();
            break;
        }
        return true;
    }
    if (!value.is_object() || value.size() != 1)
        return false;

    const std::string kind = value.begin().key();
    const json &inner = value.begin().value();

    if (kind == "Enum") {
        type = PropertyType::Enum;
        out = static_cast<uint32_t>(inner.get<int64_t>());
    } else if (kind == "Int") {
        if (!inner.is_number())
            return false;
        type = PropertyType::Int;
        out = static_cast<int32_t>(inner.get<int64_t>());
    } else if (kind == "Float") {
        if (!inner.is_number())
            return false;
        type = PropertyType::Float;
        out = inner.get<float>();
    } else if (kind == "Int64") {
        // <int64> reads back as PropertyType::Int64 (Tokens/Int64.h:36-41). Letting it fall
        // through as an untagged number typed it Int, and the static_cast<int32_t> truncated
        // every asset id and UserId past 2^31.
        if (!inner.is_number())
            return false;
        type = PropertyType::Int64;
        out = inner.get<int64_t>();
    } else if (kind == "Double") {
        // Likewise <double> is PropertyType::Double (Tokens/Double.h:36-41); as an untagged
        // number it became a float and lost the mantissa the file actually stored.
        if (!inner.is_number())
            return false;
        type = PropertyType::Double;
        out = inner.get<double>();
    } else if (kind == "Ref") {
        // Plan referents are strings; the merge pass has no cross-plugin referent space yet, so a
        // reference is dropped rather than pointed somewhere wrong.
        return false;
    } else if (kind == "Content") {
        type = PropertyType::Content;
        out = Content(inner.is_string() ? inner.get<std::string>() : std::string());
    } else if (kind == "ContentId") {
        // A ContentId is a String on the wire; PROP::Write unwraps it.
        type = PropertyType::String;
        out = ContentId(inner.is_string() ? inner.get<std::string>() : std::string());
    } else if (kind == "BrickColor") {
        type = PropertyType::BrickColor;
        out = static_cast<int32_t>(inner.get<int64_t>());
    } else if (kind == "Vector2" && inner.size() == 2) {
        type = PropertyType::Vector2;
        out = Vector2(Number(inner[0]), Number(inner[1]));
    } else if (kind == "Vector3" && inner.size() == 3) {
        type = PropertyType::Vector3;
        out = Vector3(Number(inner[0]), Number(inner[1]), Number(inner[2]));
    } else if (kind == "Vector3int16" && inner.size() == 3) {
        type = PropertyType::Vector3int16;
        out = Vector3int16(static_cast<int16_t>(inner[0].get<int>()),
                           static_cast<int16_t>(inner[1].get<int>()),
                           static_cast<int16_t>(inner[2].get<int>()));
    } else if (kind == "Color3" && inner.size() == 3) {
        type = PropertyType::Color3;
        out = Color3(Number(inner[0]), Number(inner[1]), Number(inner[2]));
    } else if (kind == "Color3uint8" && inner.size() == 3) {
        type = PropertyType::Color3uint8;
        out = Color3uint8(static_cast<uint8_t>(inner[0].get<int>()),
                          static_cast<uint8_t>(inner[1].get<int>()),
                          static_cast<uint8_t>(inner[2].get<int>()));
    } else if (kind == "UDim" && inner.size() == 2) {
        type = PropertyType::UDim;
        out = UDim(Number(inner[0]), inner[1].get<int32_t>());
    } else if (kind == "UDim2" && inner.size() == 2) {
        type = PropertyType::UDim2;
        out = UDim2(Number(inner[0][0]), inner[0][1].get<int32_t>(),
                    Number(inner[1][0]), inner[1][1].get<int32_t>());
    } else if (kind == "Rect" && inner.size() == 2) {
        type = PropertyType::Rect;
        out = Rect({Number(inner[0][0]), Number(inner[0][1])},
                   {Number(inner[1][0]), Number(inner[1][1])});
    } else if (kind == "NumberRange" && inner.size() == 2) {
        type = PropertyType::NumberRange;
        out = NumberRange(Number(inner[0]), Number(inner[1]));
    } else if (kind == "CFrame" && inner.contains("position") && inner.contains("orientation")) {
        const json &p = inner["position"];
        const json &r = inner["orientation"];
        std::array<float, 12> components {};
        for (size_t i = 0; i < 3 && i < p.size(); ++i)
            components[i] = Number(p[i]);
        for (size_t i = 0; i < 9 && i < r.size(); ++i)
            components[i + 3] = Number(r[i]);
        type = PropertyType::CFrame;
        out = CFrame(components);
    } else if (kind == "Font") {
        // Tokens/Font.h:38-53 builds the face out of all four fields. Taking the family alone
        // made every mounted bold or italic label come back Regular/Normal, and dropped the
        // CachedFaceId the engine resolves the face through.
        if (!inner.is_object())
            return false;
        uint32_t weight = static_cast<uint32_t>(FontWeight::Regular);
        const auto weightValue = inner.find("weight");
        if (weightValue != inner.end()) {
            if (weightValue->is_number())
                weight = weightValue->get<uint32_t>();
            else if (weightValue->is_string())
                Tokens::ParseInteger(weightValue->get<std::string>(), weight);
        }
        const auto styleValue = inner.find("style");
        const bool italic = styleValue != inner.end() && styleValue->is_string() &&
            styleValue->get<std::string>() == "Italic";
        type = PropertyType::FontFace;
        out = FontFace(inner.value("family", std::string()), static_cast<FontWeight>(weight),
                       italic ? FontStyle::Italic : FontStyle::Normal,
                       inner.value("cachedFaceId", std::string()));
    } else if (kind == "Ray" && inner.contains("origin") && inner.contains("direction")) {
        const json &origin = inner["origin"];
        const json &direction = inner["direction"];
        if (origin.size() != 3 || direction.size() != 3)
            return false;
        type = PropertyType::Ray;
        out = Ray(Vector3(Number(origin[0]), Number(origin[1]), Number(origin[2])),
                  Vector3(Number(direction[0]), Number(direction[1]), Number(direction[2])));
    } else if (kind == "NumberSequence" && inner.is_array() && !inner.empty()) {
        // Tokens/NumberSequence.h:36-49. The default constructor seeds two keypoints, so the
        // list has to be emptied before the plan's own are appended.
        NumberSequence sequence;
        sequence.Keypoints.clear();
        for (const json &keypoint : inner) {
            if (keypoint.size() != 3)
                return false;
            sequence.Keypoints.emplace_back(Number(keypoint[0]), Number(keypoint[1]),
                                            Number(keypoint[2]));
        }
        type = PropertyType::NumberSequence;
        out = std::move(sequence);
    } else if (kind == "ColorSequence" && inner.is_array() && !inner.empty()) {
        // Tokens/ColorSequence.h:36-52. ColorSequenceKeypoint::Envelope is an int32, unlike the
        // NumberSequence one.
        ColorSequence sequence;
        sequence.Keypoints.clear();
        for (const json &keypoint : inner) {
            if (keypoint.size() != 5)
                return false;
            sequence.Keypoints.emplace_back(
                Number(keypoint[0]),
                Color3(Number(keypoint[1]), Number(keypoint[2]), Number(keypoint[3])),
                static_cast<int32_t>(Number(keypoint[4])));
        }
        type = PropertyType::ColorSequence;
        out = std::move(sequence);
    } else if (kind == "Axes" && inner.is_number()) {
        type = PropertyType::Axes;
        out = Axes(static_cast<uint8_t>(inner.get<uint32_t>()));
    } else if (kind == "Faces" && inner.is_number()) {
        type = PropertyType::Faces;
        out = Faces(static_cast<uint8_t>(inner.get<uint32_t>()));
    } else if (kind == "ProtectedString") {
        type = PropertyType::String;
        out = ProtectedString(inner.is_string() ? inner.get<std::string>() : std::string());
    } else if (kind == "BinaryString") {
        // Tokens/BinaryString.h:38-46 decodes before storing, and so must this: a place saved
        // with the base64 text where the payload belongs hands the engine characters where it
        // wants bytes (Terrain.SmoothGrid, mesh data). The plan carries the base64 because a
        // JSON string has to be valid UTF-8 and a payload is arbitrary bytes.
        std::vector<unsigned char> decoded;
        if (!inner.is_string() || !Tokens::Base64Decode(inner.get<std::string>(), decoded))
            return false;
        type = PropertyType::String;
        out = std::string(decoded.begin(), decoded.end());
    } else if (kind == "SecurityCapabilities") {
        uint64_t capabilities = 0;
        if (inner.is_number()) {
            capabilities = inner.get<uint64_t>();
        } else if (!inner.is_string() ||
                   !Tokens::ParseInteger(inner.get<std::string>(), capabilities)) {
            return false;
        }
        type = PropertyType::SecurityCapabilities;
        out = SecurityCapabilities(capabilities);
    } else if (kind == "PhysicalProperties") {
        type = PropertyType::PhysicalProperties;
        if (inner.is_string()) {
            out = std::optional<PhysicalProperties>();
        } else {
            PhysicalProperties properties(
                inner.value("density", 0.0f), inner.value("friction", 0.0f),
                inner.value("elasticity", 0.0f), inner.value("frictionWeight", 0.0f),
                inner.value("elasticityWeight", 0.0f));
            properties.Flags = 0x01;
            out = std::optional<PhysicalProperties>(properties);
        }
    } else {
        return false;
    }
    return true;
}

PluginTreeMaterializer::PluginTreeMaterializer(Roblox::RobloxFile *place) :
    mPlace(place),
    mBinaryReferents(dynamic_cast<BinaryFormat::BinaryRobloxFile *>(place) != nullptr) {}

void PluginTreeMaterializer::ForgetSubtree(Instance *instance) {
    if (instance == nullptr)
        return;
    // RobloxFile::DestroySubtree frees the unique_ptrs that own these, so anything still holding
    // a raw pointer to one would dereference freed memory in ResolveReferences.
    std::vector<Instance *> doomed = instance->GetDescendants();
    doomed.push_back(instance);
    for (const Instance *dead : doomed) {
        mMounted.erase(dead);
        std::erase_if(mReferents, [dead](const auto &entry) { return entry.second == dead; });
        std::erase_if(mPending, [dead](const PendingReference &pending) {
            return pending.Owner == dead;
        });
    }
}

void PluginTreeMaterializer::ResolveReferences(PluginMountResult &result) {
    for (const PendingReference &pending : mPending) {
        const auto found = mReferents.find(pending.Target);
        if (found == mReferents.end() || found->second == nullptr) {
            result.Warnings.push_back(std::format(
                "dropped {}.{}: no instance for referent {}", pending.Owner->ClassName,
                pending.PropertyName, pending.Target));
            continue;
        }
        Property property;
        property.Name = pending.PropertyName;
        property.Type = PropertyType::Ref;
        if (mBinaryReferents) {
            // Binary places address instances by integer referent; XML uses the string.
            int32_t referent = -1;
            if (!Tokens::ParseInteger(found->second->Referent, referent))
                continue;
            property.Value = referent;
        } else {
            property.XmlToken = "Ref";
            property.Value = found->second->Referent;
        }
        pending.Owner->AddProperty(std::move(property));
    }
    mPending.clear();
}

bool PluginTreeMaterializer::ApplyProperties(Instance &instance, const json &properties,
                                             bool strict, PluginMountResult &result,
                                             std::string *error) {
    if (!properties.is_object())
        return true;
    for (auto entry = properties.begin(); entry != properties.end(); ++entry) {
        if (entry.key() == "Name")
            continue;
        PropertyType type = PropertyType::Unknown;
        std::any value;
        // A Ref names another plan node, which may not exist yet; defer it.
        if (IsPlanTag(entry.value(), "Ref")) {
            const json &target = entry.value().begin().value();
            if (target.is_string() && !target.get<std::string>().empty())
                mPending.push_back({&instance, entry.key(), target.get<std::string>()});
            continue;
        }
        if (!ConvertPlanValue(entry.value(), type, value, instance.ClassName, entry.key())) {
            // A best-effort property came out of a .rbxmx and may legitimately be one the plan
            // format cannot carry. A strict one was named in the project file, so dropping it
            // would quietly ignore what the plugin author wrote.
            if (strict) {
                if (error != nullptr) {
                    *error = std::format("{}.{}: $properties value is not one the plan format "
                                         "can represent", instance.ClassName, entry.key());
                }
                return false;
            }
            result.Warnings.push_back(std::format("dropped {}.{}: unsupported plan value",
                                                  instance.ClassName, entry.key()));
            continue;
        }
        Property property;
        property.Name = entry.key();
        property.Type = type;
        property.Value = std::move(value);
        // A decoded BinaryString is raw bytes carried in a std::string, which XmlRobloxFile's
        // XmlTokenForType cannot tell apart from an ordinary string -- an XML place would get the
        // payload written back out as <string>. The element name is only knowable here, where the
        // tag the plan wrote is still in hand.
        if (IsPlanTag(entry.value(), "BinaryString"))
            property.XmlToken = "BinaryString";
        instance.AddProperty(std::move(property));
    }
    return true;
}

bool PluginTreeMaterializer::MountChildren(const json &node, Instance *parent,
                                           PluginMountResult &result, std::string *error) {
    if (!node.contains("children") || !node["children"].is_array())
        return true;
    for (const json &child : node["children"]) {
        if (MountNode(child, parent, result, error) == nullptr && error != nullptr &&
            !error->empty()) {
            return false;
        }
    }
    return true;
}

Instance *PluginTreeMaterializer::MountNode(const json &node, Instance *parent,
                                            PluginMountResult &result, std::string *error) {
    if (!node.is_object())
        return nullptr;

    // The plan builder emits four kinds and only "instance" describes an instance of its own.
    // Nothing read this field before, so the other three were all mounted as plain Folders.
    const std::string kind = node.value("kind", std::string("instance"));
    if (kind == "model" || kind == "embeddedModel") {
        // An .rbxm is spliced in whole by BinaryRobloxFile::AppendBinaryModel, beneath the path
        // the plan builder recorded -- a path that deliberately stops at this node's parent.
        // Creating an instance for the node as well left an empty Folder standing beside the
        // model's real roots, named after the file rather than after the model.
        if (!node.value("properties", json::object()).empty() ||
            !node.value("strictProperties", json::object()).empty()) {
            result.Warnings.push_back(std::format(
                "dropped properties on {}: an .rbxm contributes its own roots, so the plan has "
                "no instance of its own to write them onto", node.value("name", std::string())));
        }
        return parent;
    }
    if (kind == "root") {
        // "$className": "DataModel" names the place itself, not a child of it -- a stock Rojo
        // default.project.json opens with one, and creating a child for it hung the plugin's
        // whole service tree under a DataModel-classed instance inside the place.
        if (!ApplyProperties(*parent, node.value("properties", json::object()), false, result,
                             error)) {
            return nullptr;
        }
        if (node.contains("strictProperties") &&
            !ApplyProperties(*parent, node["strictProperties"], true, result, error)) {
            return nullptr;
        }
        return MountChildren(node, parent, result, error) ? parent : nullptr;
    }
    if (kind == "instances") {
        // A multi-root .rbxmx: its roots are siblings, not children of a wrapper named after the
        // file. The plan builder leaves this node out of an embedded model's parent path for the
        // same reason.
        if (!node.value("properties", json::object()).empty() ||
            !node.value("strictProperties", json::object()).empty()) {
            result.Warnings.push_back(std::format(
                "dropped properties on {}: a multi-root model has no single instance to write "
                "them onto", node.value("name", std::string())));
        }
        return MountChildren(node, parent, result, error) ? parent : nullptr;
    }

    const std::string name = node.value("name", std::string());
    const std::string className = node.value("className", std::string("Folder"));
    // Set when the project file pinned $className on a node whose class otherwise came from the
    // .rbxmx it was read out of.
    const bool pinnedClass = node.value("rbxmxStrictClass", false);

    Instance *existing = nullptr;
    for (Instance *child : parent->GetChildren()) {
        if (child->Name == name) {
            existing = child;
            break;
        }
    }

    // A class pinned by hand has to end up as exactly that class, so a same-named instance of
    // some other container class is replaced rather than merged into.
    const bool mergeable = existing != nullptr && IsContainerClass(existing->ClassName) &&
        IsContainerClass(className) && (!pinnedClass || existing->ClassName == className);

    Instance *target = nullptr;
    if (mergeable) {
        target = existing;
        ++result.Merged;
    } else {
        if (existing != nullptr) {
            // Later plugin wins: the whole subtree goes, not just the node.
            ForgetSubtree(existing);
            mPlace->DestroySubtree(existing);
            ++result.Replaced;
        } else {
            ++result.Created;
        }
        target = mPlace->CreateInstance(className, name, parent);
        if (target == nullptr) {
            if (error != nullptr)
                *error = "could not create " + className + " " + name;
            return nullptr;
        }
        // BuildTables writes a DataModel child as a service only when IsService is set, so
        // without this a plugin-supplied ReplicatedStorage was emitted as an ordinary instance
        // and the engine ended up with a second, unrooted copy of the service.
        // BinaryRobloxFile.cpp:718-730 and :798-804 flag the containers they create the same way.
        if (parent == static_cast<Instance *>(mPlace) && IsDataModelServiceClass(className))
            target->IsService = true;
    }
    // ApplyProperties writes onto target whether it was created or merged into, and a merged
    // target is an instance the place file already contained -- see MountedInstances().
    mMounted.insert(target);

    if (node.contains("referent") && node["referent"].is_string())
        mReferents[node["referent"].get<std::string>()] = target;

    if (!ApplyProperties(*target, node.value("properties", json::object()), false, result,
                         error)) {
        return nullptr;
    }
    // Applied second so a project file's $properties wins over the value harvested from the
    // .rbxmx, which is the whole point of writing one.
    if (node.contains("strictProperties") &&
        !ApplyProperties(*target, node["strictProperties"], true, result, error)) {
        return nullptr;
    }
    if (node.contains("source") && node["source"].is_string()) {
        Property source;
        source.Name = "Source";
        source.Type = PropertyType::String;
        source.XmlToken = "ProtectedString";
        source.Value = ProtectedString(node["source"].get<std::string>());
        target->AddProperty(std::move(source));
    }

    return MountChildren(node, target, result, error) ? target : nullptr;
}

bool PluginTreeMaterializer::Mount(const json &plan, PluginMountResult &result,
                                   std::string *error) {
    if (mPlace == nullptr || !plan.is_array())
        return false;
    for (const json &node : plan) {
        if (MountNode(node, mPlace, result, error) == nullptr && error != nullptr &&
            !error->empty()) {
            return false;
        }
    }
    // Every node of this plan now exists, so its internal references can be wired up.
    ResolveReferences(result);
    mReferents.clear();
    return true;
}
