/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: LocalRcc.cpp
// Description: (Disclaimer - This code was generated by Claude.)
// Port of rsblox/local_rcc (https://github.com/rsblox/local_rcc) into the
//              noobWarrior Hook system. Loaded by noobhook.dll only when running inside
//              RobloxStudioBeta.exe -- it patches Studio so that Player can connect to
//              a Studio-hosted team test server.
//
// Original work by 7ap & Epix (https://github.com/rsblox). Ported to MinHook +
// Hooking.Patterns so we don't pull in safetyhook / Pattern16 dependencies.

#include <windows.h>

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include <Luau/BytecodeBuilder.h>
#include <Luau/Compiler.h>

#include <Hooking.Patterns.h>
#include <MinHook.h>

#define XXH_INLINE_ALL
#include <xxhash.h>
#include <zstd.h>

// -----------------------------------------------------------------------------
// Logging -- own log file so it doesn't interleave with noobhook.log
// -----------------------------------------------------------------------------

static FILE* gLog = nullptr;

static void Log(const char* category, const char* format, ...) {
    if (!gLog) return;
    fprintf(gLog, "[LocalRcc::%s] ", category);
    va_list args;
    va_start(args, format);
    vfprintf(gLog, format, args);
    va_end(args);
    fprintf(gLog, "\n");
    fflush(gLog);
}

// -----------------------------------------------------------------------------
// Roblox-allocator-backed operator new/delete.
//
// Any std::string we return from compile_hook ends up owned by Roblox code; the
// pointer it holds must therefore have been produced by Roblox's allocator, not
// our CRT's. Studio exports rbxAllocate / rbxDeallocate exactly for this; we
// route global new/delete in *this DLL only* through those exports.
//
// This is also why LocalRcc lives in its own DLL: noobhook.dll runs inside
// Player and RCCService too, where these exports don't exist.
// -----------------------------------------------------------------------------

namespace {
using rbx_alloc_fn = void* (*)(size_t);
using rbx_dealloc_fn = void (*)(void*);

rbx_alloc_fn ResolveAllocate() {
    static rbx_alloc_fn fn = reinterpret_cast<rbx_alloc_fn>(
        GetProcAddress(GetModuleHandleA(nullptr), "rbxAllocate"));
    return fn;
}

rbx_dealloc_fn ResolveDeallocate() {
    static rbx_dealloc_fn fn = reinterpret_cast<rbx_dealloc_fn>(
        GetProcAddress(GetModuleHandleA(nullptr), "rbxDeallocate"));
    return fn;
}
} // namespace

void* operator new(size_t size)   { return ResolveAllocate()(size); }
void* operator new[](size_t size) { return ResolveAllocate()(size); }
void operator delete(void* p) noexcept   { if (p) ResolveDeallocate()(p); }
void operator delete[](void* p) noexcept { if (p) ResolveDeallocate()(p); }
void operator delete(void* p, size_t) noexcept   { if (p) ResolveDeallocate()(p); }
void operator delete[](void* p, size_t) noexcept { if (p) ResolveDeallocate()(p); }

// -----------------------------------------------------------------------------
// Target function typedefs & cached addresses
// -----------------------------------------------------------------------------

namespace types {
    using compile_fn         = std::string (*)(const std::string& source, int target, int options);
    using deserialize_item_fn = void* (*)(void* self, void* result, void* in_bitstream, int item_type);

    enum item_type           { client_qos = 0x1f };
    enum network_value_format { protected_string_bytecode = 0x2f };
}

static types::compile_fn          gCompile          = nullptr;
static types::compile_fn          gOrigCompile      = nullptr;
static types::deserialize_item_fn gDeserializeItem  = nullptr;
static types::deserialize_item_fn gOrigDeserialize  = nullptr;
static uintptr_t                  gTypeForPropertyImm = 0;

// -----------------------------------------------------------------------------
// Hook: LuaVM::compile
// -----------------------------------------------------------------------------

static std::string CompileHook(const std::string& source, int target, int options) {
    // Pre-Feb-2023 Studio sometimes spam-calls compile with garbage args that
    // crash the encoder. Per the rsblox/local_rcc fork, every legitimate call
    // from registerLegalSharedScript has target == 0 and options == 8. Anything
    // else, return empty so we no-op like vanilla Studio.
    if (target != 0 || options != 8)
        return std::string();

    Log("compile", "LuaVM::compile(source=%zu bytes, target=%d, options=%d)",
        source.size(), target, options);

    // Luau 0.575 changed the BytecodeEncoder interface: the framework now
    // walks instructions itself and calls encodeOp() per opcode byte, so the
    // encoder no longer needs to know about getOpLength or AUX-instruction
    // layout. Transform stays identical (op * 227, matching rsblox/local_rcc).
    class BytecodeEncoderClient : public Luau::BytecodeEncoder {
        uint8_t encodeOp(uint8_t op) override {
            return uint8_t(op * 227);
        }
    };

    static const char* kSpecialGlobals[] = {
        "game", "Game", "workspace", "Workspace",
        "script", "shared", "plugin",
        nullptr
    };

    Luau::CompileOptions opts {};
    opts.optimizationLevel = 2;
    opts.debugLevel        = 1;
    opts.vectorLib         = "Vector3";
    opts.vectorCtor        = "new";
    opts.mutableGlobals    = kSpecialGlobals;

    BytecodeEncoderClient encoder;
    std::string bytecode = Luau::compile(source, opts, {}, &encoder);

    const size_t compressedCapacity = ZSTD_compressBound(bytecode.size());
    const uint32_t uncompressedSize = static_cast<uint32_t>(bytecode.size());

    // [magic 4] [uncompressed_size 4] [compressed payload]
    std::vector<uint8_t> encoded(4 + 4 + compressedCapacity);
    std::memcpy(&encoded[0], "RSB1", 4);
    std::memcpy(&encoded[4], &uncompressedSize, 4);

    const size_t compressedSize = ZSTD_compress(
        &encoded[8], compressedCapacity,
        bytecode.data(), bytecode.size(),
        ZSTD_maxCLevel());

    const size_t encodedSize = 4 + 4 + compressedSize;
    const XXH32_hash_t hash = XXH32(encoded.data(), encodedSize, 42);
    uint8_t key[4];
    std::memcpy(key, &hash, 4);
    for (size_t i = 0; i < encodedSize; i++)
        encoded[i] ^= uint8_t(key[i % 4] + (i * 41));

    return std::string(reinterpret_cast<const char*>(encoded.data()), encodedSize);
}

// -----------------------------------------------------------------------------
// Hook: RBX::Network::Replicator::deserializeItem
// Drops ClientQoSItem (which Studio doesn't handle) before they kick Player.
// -----------------------------------------------------------------------------

static void* DeserializeItemHook(void* self, void* result, void* inBitstream, int itemType) {
    if (itemType == types::client_qos) {
        Log("deserializeItem", "Dropping ClientQoSItem (itemType=0x%x)", itemType);
        std::memset(result, 0, 16);
        return result;
    }
    return gOrigDeserialize(self, result, inBitstream, itemType);
}

// Forward decl -- ScanAny lives further down with the rest of the scan helpers.
static void* ScanAny(const char* label, std::initializer_list<const char*> patterns);

// -----------------------------------------------------------------------------
// Studio web stack rewrite (port of studio-offline, committed 2024-03-08)
//
// Studio constructs URLs and runs its own trust checks before any socket is
// opened. If those reject our local emulator, the connect()-level redirect in
// noobhook.dll never gets a chance to fire and Studio errors with
// "Studio is unable to connect."
//
// These three hooks force URL construction to "http://localhost" and make the
// trust checks accept it; from there the existing socket-layer hook routes
// port 80 to gEmuHttpPort.
//
// Source: studio-offline @ E:\Programs\WeirdRobloxShit\studio-offline-...
// Patterns confirmed to match Studio 0.574 (one hit each).
// -----------------------------------------------------------------------------

namespace offline {
    using from_components_fn = void  (*)(void* res16, void* schema, void* host, void* path, void* query, void* fragment);
    using trust_check_fn     = uint64_t* (*)(const char* url, char a2, char a3);
    using not_trusted_fn     = char* (*)(void* a1, void* a2);
}

static offline::from_components_fn gFromComponents     = nullptr;
static offline::from_components_fn gOrigFromComponents = nullptr;
static offline::trust_check_fn     gTrustCheck         = nullptr;
static offline::trust_check_fn     gOrigTrustCheck     = nullptr;
static offline::not_trusted_fn     gNotTrusted         = nullptr;
static offline::not_trusted_fn     gOrigNotTrusted     = nullptr;

// `schema` and `host` are pointers to std::string-shaped things laid out as
// {data ptr @ +0, length @ +8}. Studio-offline relies on the original strings
// being heap-allocated (long enough to break SSO); short literals like "http"
// would normally be SSO. In practice the call sites here pass strings whose
// data pointer at +0 IS what gets used downstream -- the layout assumption
// holds for these specific call paths in 0.574.
//
// The host includes ":8080" so the URL stays self-contained: WebView2 spawns
// its own subprocesses for navigation and those don't inherit Hook.cpp's
// connect() redirect (port 80 -> emulator). Embedding the emulator's HTTP
// port in the host means WebView2 (and any other consumer) lands on the
// emulator directly without needing per-process injection or a port-80 bind.
// Hook.cpp's redirect is still useful for code paths that bypass
// FromComponents and connect to localhost:80 by other means.
static void FromComponentsHook(void* res16, void* schema, void* host,
                               void* path, void* query, void* fragment) {
    static const char* kHost   = "localhost:8080";
    static const char* kScheme = "http";

    *reinterpret_cast<const char**>(host) = kHost;
    *reinterpret_cast<size_t*>(reinterpret_cast<uint8_t*>(host) + 8) = std::strlen(kHost);

    *reinterpret_cast<const char**>(schema) = kScheme;
    *reinterpret_cast<size_t*>(reinterpret_cast<uint8_t*>(schema) + 8) = std::strlen(kScheme);

    gOrigFromComponents(res16, schema, host, path, query, fragment);
}

static uint64_t* TrustCheckHook(const char* url, char a2, char a3) {
    if (url && a3 == 0 && std::strstr(url, "http://localhost")) {
        // Original trust check accepts roblox.com; pretend that's what we got.
        return gOrigTrustCheck("http://roblox.com", a2, a3);
    }
    return gOrigTrustCheck(url, a2, a3);
}

static char* NotTrustedHook(void* /*a1*/, void* /*a2*/) {
    // Caller treats this as a small status string ("1" == ok). Static buffer
    // so the pointer survives return (original code returned a stack array,
    // which was UB; we keep the value, drop the UB).
    static char kOne[2] = { '1', '\0' };
    return kOne;
}

static bool InstallOfflineHooks() {
    gFromComponents = reinterpret_cast<offline::from_components_fn>(ScanAny("offline.fromComponents", {
        "48 89 5C 24 18 4C 89 4C 24 20 48 89 4C 24 08 55 56 57 41 54 41 55 41 56 41 57 48 8B EC 48 83 EC 60",
    }));
    gTrustCheck = reinterpret_cast<offline::trust_check_fn>(ScanAny("offline.trustCheck", {
        "48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 55 41 56 41 57 48 8D AC 24 10 FF FF FF 48 81 EC F0 01 00 00 45",
    }));
    gNotTrusted = reinterpret_cast<offline::not_trusted_fn>(ScanAny("offline.httpReqNotTrusted", {
        "48 89 74 24 10 57 48 83 EC 40 48 8B FA 48 8B F1 E8",
    }));

    // All three are independent -- install whichever matched. Missing one just
    // means that codepath stays unhooked (Studio may still mostly work).
    auto install = [](const char* label, void* target, void* detour, void** orig) {
        if (!target) return;
        MH_STATUS st = MH_CreateHook(target, detour, orig);
        if (st != MH_OK) Log("offline", "MH_CreateHook(%s) failed: %d", label, (int)st);
        else             Log("offline", "Hooked %s", label);
    };
    install("FromComponents", (void*)gFromComponents, (void*)&FromComponentsHook, (void**)&gOrigFromComponents);
    install("TrustCheck",     (void*)gTrustCheck,     (void*)&TrustCheckHook,     (void**)&gOrigTrustCheck);
    install("NotTrusted",     (void*)gNotTrusted,     (void*)&NotTrustedHook,     (void**)&gOrigNotTrusted);
    return gFromComponents || gTrustCheck || gNotTrusted;
}

// -----------------------------------------------------------------------------
// Patch: NetworkSchema::typeForProperty
// Force ProtectedString columns to serialize as ProtectedStringBytecode.
// -----------------------------------------------------------------------------

static void PatchTypeForProperty() {
    if (!gTypeForPropertyImm) return;

    uint8_t byte = static_cast<uint8_t>(types::protected_string_bytecode);

    DWORD oldProtect;
    VirtualProtect(reinterpret_cast<void*>(gTypeForPropertyImm), 16,
                   PAGE_EXECUTE_READWRITE, &oldProtect);
    *reinterpret_cast<uint8_t*>(gTypeForPropertyImm) = byte;
    VirtualProtect(reinterpret_cast<void*>(gTypeForPropertyImm), 16,
                   oldProtect, &oldProtect);
}

// -----------------------------------------------------------------------------
// Patch: RakNet::RakPeer::verifyPreauthMac -> always "allow"
//
// Roblox gates every incoming connection on a "preauth MAC" -- a keyed MAC over
// the open-connection handshake, checked host-side in RakPeer::verifyPreauthMac
// (processRbxOpenRequest2 calls it). A cross-version Player (0.573) and Studio
// host (0.574) derive different MACs, so the host rejects the Player with
// ID_INVALID_PASSWORD: in the Player log, "handshake failed ... version is out
// of date" + "Invalid password from <host>". It looks like a race because the
// MAC is time-keyed -- occasionally the windows line up and it connects.
//
// verifyPreauthMac returns a PreauthResult enum, and returns 1 ("allow") on its
// preauth-disabled early-out (`if (this->preauthEnabled == 0) return 1;`), which
// the caller treats as success. So forcing the whole function to `mov eax,1; ret`
// makes the host accept any client regardless of the MAC.
//
// The prologue shifts between builds, so we anchor on the version-stable preauth
// blob length check -- cmp rax,0x21 / cmp rax,0x32 (the 33- and 50-byte MAC
// formats) -- then walk back over the function body (which contains no 0xCC
// bytes) to the int3-padded `mov rax,rsp` entry. Confirmed on Studio 0.574;
// entry was 0x...ECFC10, ~0x55 bytes before the anchor.
// -----------------------------------------------------------------------------

static void PatchVerifyPreauthMac() {
    // cmp rax,0x21 ; je ; cmp rax,0x32 ; je ; xor eax,eax
    auto* anchor = reinterpret_cast<uint8_t*>(ScanAny("verifyPreauthMac.lencheck", {
        "48 83 F8 21 74 ? 48 83 F8 32 74 ? 33 C0",
    }));
    if (!anchor) {
        Log("preauth", "length-check pattern not found -- host will reject cross-version clients");
        return;
    }

    // Walk back to the int3 padding that precedes the function, immediately
    // followed by the `mov rax,rsp` (48 8B C4) prologue. Requiring both bytes the
    // padding AND the prologue makes us robust against a stray 0xCC displacement.
    uint8_t* entry = nullptr;
    for (int i = 1; i <= 0x140; i++) {
        if (anchor[-i] == 0xCC &&
            anchor[-i + 1] == 0x48 && anchor[-i + 2] == 0x8B && anchor[-i + 3] == 0xC4) {
            entry = anchor - i + 1;
            break;
        }
    }
    if (!entry) {
        Log("preauth", "could not find int3-padded `mov rax,rsp` entry near %p", anchor);
        return;
    }

    // mov eax,1 ; ret  -> PreauthResult "allow", returned before any stack setup.
    static const uint8_t kPatch[] = { 0xB8, 0x01, 0x00, 0x00, 0x00, 0xC3 };
    DWORD oldProtect;
    if (!VirtualProtect(entry, sizeof(kPatch), PAGE_EXECUTE_READWRITE, &oldProtect)) {
        Log("preauth", "VirtualProtect failed @ %p", entry);
        return;
    }
    std::memcpy(entry, kPatch, sizeof(kPatch));
    VirtualProtect(entry, sizeof(kPatch), oldProtect, &oldProtect);
    FlushInstructionCache(GetCurrentProcess(), entry, sizeof(kPatch));
    Log("preauth", "patched verifyPreauthMac @ %p to always allow", entry);
}

// -----------------------------------------------------------------------------
// Pattern scanning
// -----------------------------------------------------------------------------

// Try patterns in order; first one that produces exactly-one match wins.
// Returns nullptr if every alternative misses (caller logs and bails).
static void* ScanAny(const char* label, std::initializer_list<const char*> patterns) {
    int idx = 0;
    for (const char* sig : patterns) {
        auto p = hook::pattern(sig);
        if (!p.count_hint(1).empty()) {
            void* addr = p.get(0).get<void>(0);
            Log("scan", "%s matched alt #%d @ %p", label, idx, addr);
            return addr;
        }
        idx++;
    }
    Log("scan", "%s: no pattern matched (tried %d)", label, idx);
    return nullptr;
}

static bool ScanForAddresses() {
#if defined(_WIN64) && defined(_M_X64)
    // Target: Roblox Studio 0.574 (May 2023). Patterns lifted from the
    // local_rcc fork's 2023M / 2023 modes, with the original "latest" patterns
    // kept as fallbacks so the same DLL still loads on adjacent builds.
    //
    // CRITICAL: Hooking.Patterns wildcards are SINGLE `?` (one char = one
    // wildcard byte). Two `??` parse as TWO wildcards and silently mis-match.

    // ---- LuaVM::compile -----------------------------------------------------
    // 2023M (May-Jun 2023) adds a trailing C3 (ret) right after the prologue;
    // older Studios have the same prologue without the ret. The C3 disambiguates
    // from another function with the identical 22-byte prologue (verified: plain
    // pattern hits twice in 0.574, with-C3 hits once at the right address).
    void* compileAddr = ScanAny("compile", {
        "33 C0 48 C7 41 18 0F 00 00 00 48 89 01 48 89 41 10 88 01 48 8B C1 C3",  // 2023M
        "33 C0 48 C7 41 18 0F 00 00 00 48 89 01 48 89 41 10 88 01 48 8B C1",     // pre-2023M (ambiguous)
    });
    if (!compileAddr) return false;
    gCompile = reinterpret_cast<types::compile_fn>(compileAddr);

    // ---- Replicator::deserializeItem ---------------------------------------
    // Confirmed against 0.574: May 2023 Studio uses the 2022-style prologue,
    // not the "2023" prologue the fork named (the fork's labeling is by
    // codepath used, not by calendar year). Try 2022 first; keep 2023 as
    // forward fallback.
    void* deserAddr = ScanAny("deserializeItem", {
        "48 89 5C 24 08 48 89 54 24 10 55 56 57 41 56 41 57 48 8D 6C 24 C9 48 81 EC C0 00 00 00 4D 8B F0",  // 2022 (0.574)
        "48 89 5C 24 ? 48 89 74 24 ? 48 89 54 24 ? 55 57 41 56 48 8B EC 48 83 EC 40 49 8B F8",              // 2023+
    });
    if (!deserAddr) return false;
    gDeserializeItem = reinterpret_cast<types::deserialize_item_fn>(deserAddr);

    // ---- NetworkSchema::generateSchemaDefinitionPacket ---------------------
    // We patch the immediate at +4 (the `06` byte in `mov byte ptr [rsp+disp], 6`).
    // 2023 ends in `48 3B 15` (cmp r/m64, [rip+disp32]); 2022 ends in `48 8D 05` (lea).
    void* schemaAddr = ScanAny("typeForProperty", {
        "C6 44 24 ? 06 EB ? 48 3B 15",  // 2023 (matches 0.574)
        "C6 44 24 ? 06 EB ? 48 8D 05",  // 2022
    });
    if (!schemaAddr) return false;
    gTypeForPropertyImm = reinterpret_cast<uintptr_t>(schemaAddr) + 4;
    Log("scan", "typeForProperty imm @ %p", (void*)gTypeForPropertyImm);

    return true;
#else
    Log("scan", "LocalRcc is x64-only");
    return false;
#endif
}

// -----------------------------------------------------------------------------
// DLL entrypoint
// -----------------------------------------------------------------------------

// Read by both code paths below. noobhook (via the Injector) sets NOOBHOOK_SIDE to
// the launch role: "client", "server", or "studio". Only "server" means this Studio
// is acting as a team-test host, so only then do we install the rsblox/local_rcc
// replication machinery. "studio" (regular Play Solo) and anything else -- including
// the variable being unset -- means vanilla script handling. Defaulting to the safe
// (solo) path is deliberate: an old or side-less injector, or LocalRcc loaded by
// hand, all stay out of the way of in-process script execution.
static bool IsTeamTestMode() {
    char buf[16] = {0};
    DWORD n = GetEnvironmentVariableA("NOOBHOOK_SIDE", buf, sizeof(buf));
    return n > 0 && n < sizeof(buf) && _stricmp(buf, "server") == 0;
}

static DWORD WINAPI WorkerThread(LPVOID) {
    gLog = freopen("noobhook_localrcc.log", "w", stderr);
    Log("main", "LocalRcc starting (rsblox/local_rcc port)");

    if (!ResolveAllocate() || !ResolveDeallocate()) {
        Log("main", "rbxAllocate/rbxDeallocate not exported -- aborting (not Studio?)");
        return 1;
    }

    if (MH_Initialize() != MH_OK && MH_Initialize() != MH_ERROR_ALREADY_INITIALIZED) {
        Log("main", "MH_Initialize failed");
        return 1;
    }

    const bool teamTest = IsTeamTestMode();
    Log("main", "Launch mode: %s", teamTest
        ? "teamtest -- local_rcc replication ON"
        : "solo -- vanilla script handling (connection hooks only)");

    // Studio-offline web-stack hooks are needed in BOTH modes -- they're what let
    // Studio reach the local emulator at all. Install them first, unconditionally.
    // If none of the three patterns match, log and keep going.
    if (!InstallOfflineHooks())
        Log("main", "No studio-offline patterns matched (connection bypass disabled)");

    // The compile hook, deserializeItem hook and typeForProperty patch together make
    // Studio serialize script Source as ProtectedStringBytecode and emit local_rcc's
    // RSB1 wire format. That is only correct when replicating to an EXTERNAL client.
    // In solo play those same scripts run in-process and are fed straight to
    // luau_load, which knows nothing about the wire format -> "bytecode version
    // mismatch". (NB: typeForProperty is the actual trigger -- it forces the bytecode
    // channel; the compile hook only decides which bytes flow through it.) So install
    // all three only for team test; solo falls back to vanilla source replication,
    // where the client compiles each script locally.
    if (teamTest) {
        if (!ScanForAddresses()) {
            Log("main", "Pattern scan failed -- LocalRcc must be updated for this Studio build");
            return 1;
        }

        MH_STATUS st = MH_CreateHook(reinterpret_cast<LPVOID>(gCompile),
                                     reinterpret_cast<LPVOID>(&CompileHook),
                                     reinterpret_cast<LPVOID*>(&gOrigCompile));
        if (st != MH_OK) { Log("main", "Hook(compile) failed: %d", (int)st); return 1; }

        st = MH_CreateHook(reinterpret_cast<LPVOID>(gDeserializeItem),
                           reinterpret_cast<LPVOID>(&DeserializeItemHook),
                           reinterpret_cast<LPVOID*>(&gOrigDeserialize));
        if (st != MH_OK) { Log("main", "Hook(deserializeItem) failed: %d", (int)st); return 1; }
    }

    MH_STATUS est = MH_EnableHook(MH_ALL_HOOKS);
    if (est != MH_OK) { Log("main", "EnableHook failed: %d", (int)est); return 1; }
    Log("main", "Enabled hooks (offline%s)",
        teamTest ? " + compile + deserializeItem" : " only");

    if (teamTest) {
        PatchTypeForProperty();
        Log("main", "Patched RBX::Network::NetworkSchema::typeForProperty");

        // Accept cross-version Players: neuter the host's preauth-MAC gate so the
        // 0.573 Player isn't rejected with ID_INVALID_PASSWORD ("version out of date").
        PatchVerifyPreauthMac();
    }

    Log("main", "LocalRcc ready -- credits: 7ap & Epix @ https://github.com/rsblox");
    return 0;
}

BOOL APIENTRY DllMain(HINSTANCE hModule, DWORD reason, LPVOID) {
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(hModule);
        HANDLE t = CreateThread(nullptr, 0, WorkerThread, nullptr, 0, nullptr);
        if (t) CloseHandle(t);
    }
    return TRUE;
}
