/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: BackupDialog.cpp
// Started by: Hattozo
// Started on: 11/3/2025
// Description:
#include "BackupDialog.h"
#include "Application.h"
#include "BackupTask.h"
#include "Sdk/Sdk.h"
#include "Sdk/Project/EmuDb/EmuDbProject.h"
#include "NoobWarrior/Backup.h"

#include <cassert>

#include <QMessageBox>

using namespace NoobWarrior;
using namespace NoobWarrior::Backup;

BackupDialog::BackupDialog(QWidget *parent) : QDialog(parent),
    mSource(ItemSource::OnlineItem),
    mItemType(ItemType::Universe)
{
    setWindowTitle(tr("Backup from Roblox"));
    setWindowIcon(QIcon(":/images/roblox_backup.png"));
    setSizePolicy(QSizePolicy::Minimum, QSizePolicy::Minimum);
    InitWidgets();
}

void BackupDialog::InitWidgets() {
    mMainLayout = new QVBoxLayout(this);

    mItemTypeCaption = new QLabel("Select which type of item you'd like to back up.\nIt is important to understand that a Place and a Universe are not the same thing.\nUniverses are the entire game, while places are just individual levels.\nIt is also important to know that an Asset can be one of many types, like audios or decals.");

    mItemTypeDropdown = new QComboBox();
    mItemTypeDropdown->addItem("Universe (Game)", static_cast<int>(ItemType::Universe));
    mItemTypeDropdown->addItem("Model/Place/Asset", static_cast<int>(ItemType::Asset));
    mItemTypeDropdown->addItem("User", static_cast<int>(ItemType::User));
    mItemTypeDropdown->addItem("Group", static_cast<int>(ItemType::Group));
    mItemTypeDropdown->addItem("Bundle", static_cast<int>(ItemType::Bundle));

    connect(mItemTypeDropdown, &QComboBox::currentIndexChanged, [this](int index) {
        mItemType = static_cast<ItemType>(mItemTypeDropdown->itemData(index).toInt());
        UpdateWidgets();
    });

    mIdCaption = new QLabel("Type in the ID of the item. Make sure you chose the correct type.");
    mIdField = new QLineEdit();
    mIdField->setPlaceholderText("Item ID");

    mButtons = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel);
    connect(mButtons, &QDialogButtonBox::accepted, [this]() {
        if (StartBackup())
            close();
    });
    connect(mButtons, &QDialogButtonBox::rejected, [this]() {
        close();
    });

    mMainLayout->addWidget(mItemTypeCaption);
    mMainLayout->addWidget(mItemTypeDropdown);
    mMainLayout->addWidget(mIdCaption);
    mMainLayout->addWidget(mIdField);
    mMainLayout->addWidget(mButtons);

    UpdateWidgets();
}

void BackupDialog::UpdateWidgets() {
    resize(minimumSizeHint());
}

bool BackupDialog::StartBackup() {
    EmuDb *db = GetDatabase();
    if (db == nullptr) {
        QMessageBox::critical(this, "Cannot Backup", "Your SDK window needs to be tabbed into a database project.");
        return false;
    }

    bool idOk = false;
    int64_t id = mIdField->text().trimmed().toLongLong(&idOk);
    if (!idOk || id <= 0) {
        QMessageBox::warning(this, "Invalid ID", "Please enter a valid numeric item ID.");
        return false;
    }

    Out("BackupDialog", "Started backup of {} id {}", GetTableNameFromItemType(mItemType), id);

    ProcessOptions opts;
    opts.TargetSource = mSource;
    opts.TargetItemType = mItemType;
    opts.TargetId = id;
    opts.DestinationType = DestinationType::Database;
    opts.Destination = db;
    opts.DownloadMetadata = true;
    opts.DownloadAutoGeneratedThumbnails = true;
    opts.ParseFilesAndBackupFoundAssets = false;

    auto *sdk = dynamic_cast<Sdk*>(parent());
    if (sdk == nullptr) {
        QMessageBox::critical(this, "Cannot Backup", "The backup window has no parent SDK window to run the task in.");
        return false;
    }

    // The task owns the Process and runs it on a worker thread; it is intentionally not deleted here
    // (the tree view keeps a pointer into the descriptor tree for the lifetime of the SDK window).
    auto *task = new BackupTask(gApp->GetCore(), std::move(opts));
    task->SetSdk(sdk);
    task->Register(sdk->GetBackgroundTasks());
    task->Start();
    return true;
}

EmuDb* BackupDialog::GetDatabase() {
    auto *sdk = dynamic_cast<Sdk*>(parent());
    if (sdk != nullptr) {
        auto* proj = dynamic_cast<EmuDbProject*>(sdk->GetFocusedProject());
        if (proj != nullptr) return proj->GetDb();
    }
    return nullptr;
}