/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// Repairs databases that recorded an earlier, incomplete "v17" (a pre-release attempt at the DataStore
// schema) in their Migration table. Because migrations are keyed by version string and applied only
// once, those databases skip v17 and never get the DataStore tables. This v18 re-creates them with
// IF NOT EXISTS, so it is a no-op on databases where v17 already created them and a real fix on the
// rest. Keep it identical to v17. (Code generated by Claude Opus 4.8)
static const char *migration_v18 = R"***(
CREATE TABLE IF NOT EXISTS DataStore (
    Id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    UniverseId          INTEGER NOT NULL,
    Name                TEXT NOT NULL,
    Type                INTEGER NOT NULL DEFAULT 0,   -- 0 = Standard, 1 = Ordered
    CreatedTime         INTEGER NOT NULL DEFAULT 0,   -- milliseconds since the Unix epoch
    VersioningEnabled   INTEGER NOT NULL DEFAULT 1,
    UNIQUE(UniverseId, Name, Type)
);

CREATE TABLE IF NOT EXISTS DataStoreEntry (
    Id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    UniverseId          INTEGER NOT NULL,
    DataStoreName       TEXT NOT NULL,
    Scope               TEXT NOT NULL DEFAULT 'global',
    EntryKey            TEXT NOT NULL,                -- the user's key within (datastore, scope)
    Type                INTEGER NOT NULL DEFAULT 0,   -- mirrors DataStore.Type
    CurrentVersionId    TEXT,                         -- DataStoreVersion.VersionId of the live value
    SortValue           INTEGER,                      -- numeric value for ordered stores / range queries; NULL otherwise
    Deleted             INTEGER NOT NULL DEFAULT 0,   -- 1 when the current version is a RemoveAsync tombstone
    CreatedTime         INTEGER NOT NULL DEFAULT 0,   -- milliseconds; when the key was first created
    UpdatedTime         INTEGER NOT NULL DEFAULT 0,   -- milliseconds; last successful write
    UNIQUE(UniverseId, DataStoreName, Scope, EntryKey, Type)
);

CREATE TABLE IF NOT EXISTS DataStoreVersion (
    Id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    EntryId             INTEGER NOT NULL,
    VersionId           TEXT NOT NULL,                -- opaque, lexicographically time-sortable id
    Value               TEXT,                         -- raw JSON value text; NULL for a tombstone
    ContentLength       INTEGER NOT NULL DEFAULT 0,   -- byte length of Value
    ContentMd5          TEXT,                         -- base64(md5(Value)), the content-md5 the engine checks
    UserIds             TEXT NOT NULL DEFAULT '[]',   -- JSON array of associated user ids
    Attributes          TEXT NOT NULL DEFAULT '{}',   -- JSON object of metadata (DataStoreSetOptions:SetMetadata)
    Deleted             INTEGER NOT NULL DEFAULT 0,   -- 1 when this version is a tombstone (RemoveAsync)
    CreatedTime         INTEGER NOT NULL DEFAULT 0,   -- milliseconds since the Unix epoch
    UNIQUE(EntryId, VersionId),
    FOREIGN KEY(EntryId) REFERENCES DataStoreEntry(Id)
);

CREATE INDEX IF NOT EXISTS idx_datastoreentry_lookup
    ON DataStoreEntry(UniverseId, DataStoreName, Scope, Type, EntryKey);

CREATE INDEX IF NOT EXISTS idx_datastoreentry_sort
    ON DataStoreEntry(UniverseId, DataStoreName, Scope, Type, SortValue);

CREATE INDEX IF NOT EXISTS idx_datastoreversion_entry
    ON DataStoreVersion(EntryId, VersionId);
)***";
