/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: VideoTranscoder.cpp
// Started by: Hattozo
// Started on: 8/26/2026
// Description: An ffmpeg driver
//              (Disclaimer: This code was generated by Claude Opus 5.)
#include <NoobWarrior/Video/VideoTranscoder.h>
#include <NoobWarrior/NoobWarrior.h>
#include <NoobWarrior/Paths.h>
#include <NoobWarrior/Registry.h>

#include <nlohmann/json.hpp>

#include <algorithm>
#include <atomic>
#include <cstdlib>
#include <format>
#include <fstream>
#include <system_error>

#if defined(_WIN32)
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <windows.h>
#else
#  include <sys/wait.h>
#  include <unistd.h>
#endif

using namespace NoobWarrior;

namespace {

// Monotonic suffix for scratch directories, so two concurrent transcodes never collide.
std::atomic<uint64_t> gTempCounter {0};

// Dropped into a finished cache directory. Its presence is what makes the directory trustworthy --
// without it a half-written or interrupted run would look complete on the next startup.
constexpr const char *kCompleteMarker = ".complete";
constexpr const char *kPlaylistName   = "index.m3u8";

bool WriteWholeFile(const std::filesystem::path &path, const std::vector<unsigned char> &data) {
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (out.fail())
        return false;
    if (!data.empty())
        out.write(reinterpret_cast<const char*>(data.data()), static_cast<std::streamsize>(data.size()));
    return out.good();
}

bool ReadWholeFile(const std::filesystem::path &path, std::vector<unsigned char> *data) {
    std::error_code ec;
    const auto size = std::filesystem::file_size(path, ec);
    if (ec)
        return false;

    std::ifstream in(path, std::ios::binary);
    if (in.fail())
        return false;

    data->resize(static_cast<size_t>(size));
    if (size == 0)
        return true;
    return static_cast<bool>(in.read(reinterpret_cast<char*>(data->data()),
                                     static_cast<std::streamsize>(size)));
}

// Quote one argv entry for the platform's command line. Windows parses the whole line in the child, so
// paths with spaces have to be quoted here; ffmpeg filter arguments carry commas and colons, which is
// exactly what breaks when a path is left bare.
std::string QuoteArg(const std::string &arg) {
#if defined(_WIN32)
    std::string out = "\"";
    size_t backslashes = 0;
    for (char c : arg) {
        if (c == '\\') {
            backslashes++;
            out += c;
            continue;
        }
        if (c == '"') {
            // Any run of backslashes immediately before a quote has to be doubled.
            out.append(backslashes, '\\');
            out += "\\\"";
        } else {
            out += c;
        }
        backslashes = 0;
    }
    out.append(backslashes, '\\'); // ...and again if the run ends the argument
    out += '"';
    return out;
#else
    std::string out = "'";
    for (char c : arg) {
        if (c == '\'')
            out += "'\\''";
        else
            out += c;
    }
    out += '\'';
    return out;
#endif
}

std::string BuildCommandLine(const std::filesystem::path &exe, const std::vector<std::string> &args) {
    std::string line = QuoteArg(exe.string());
    for (const std::string &arg : args)
        line += " " + QuoteArg(arg);
    return line;
}

// Runs a child to completion with stdout+stderr redirected into logPath, and reports its exit code.
// Redirecting to a file rather than a pipe is deliberate: a pipe that fills while nobody drains it
// deadlocks the child, and ffmpeg is extremely chatty on stderr.
bool RunProcess(const std::filesystem::path &exe, const std::vector<std::string> &args,
                const std::filesystem::path &logPath, int *exitCode) {
    const std::string commandLine = BuildCommandLine(exe, args);

#if defined(_WIN32)
    SECURITY_ATTRIBUTES sa {};
    sa.nLength = sizeof(sa);
    sa.bInheritHandle = TRUE;

    HANDLE log = CreateFileW(logPath.wstring().c_str(), GENERIC_WRITE, FILE_SHARE_READ, &sa,
                             CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (log == INVALID_HANDLE_VALUE)
        return false;

    STARTUPINFOW si {};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdInput  = nullptr;
    si.hStdOutput = log;
    si.hStdError  = log;

    PROCESS_INFORMATION pi {};

    // CreateProcessW may write to the command-line buffer, so it cannot share a literal's storage.
    std::wstring wide;
    {
        const int needed = MultiByteToWideChar(CP_UTF8, 0, commandLine.c_str(), -1, nullptr, 0);
        wide.resize(needed > 0 ? needed : 1);
        if (needed > 0)
            MultiByteToWideChar(CP_UTF8, 0, commandLine.c_str(), -1, wide.data(), needed);
    }

    // CREATE_NO_WINDOW: QtGui is a windowed application and must not flash a console per transcode.
    const BOOL ok = CreateProcessW(nullptr, wide.data(), nullptr, nullptr, TRUE,
                                   CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi);
    CloseHandle(log);
    if (!ok)
        return false;

    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD code = 1;
    GetExitCodeProcess(pi.hProcess, &code);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);

    *exitCode = static_cast<int>(code);
    return true;
#else
    const std::string full = commandLine + " > " + QuoteArg(logPath.string()) + " 2>&1";
    const int status = std::system(full.c_str());
    if (status == -1)
        return false;
    *exitCode = WIFEXITED(status) ? WEXITSTATUS(status) : 1;
    return true;
#endif
}

// The tail of ffmpeg's log, which is where it says why it gave up.
std::string LogTail(const std::filesystem::path &logPath, size_t maxBytes = 600) {
    std::vector<unsigned char> data;
    if (!ReadWholeFile(logPath, &data) || data.empty())
        return "";
    const size_t start = data.size() > maxBytes ? data.size() - maxBytes : 0;
    std::string tail(reinterpret_cast<const char*>(data.data()) + start, data.size() - start);
    std::replace(tail.begin(), tail.end(), '\r', ' ');
    std::replace(tail.begin(), tail.end(), '\n', ' ');
    return tail;
}

bool LooksExecutable(const std::filesystem::path &path) {
    std::error_code ec;
    return !path.empty() && std::filesystem::is_regular_file(path, ec);
}

/* True when a segment carries an H.264 sequence parameter set near its start, i.e. it can be decoded
 * without having seen an earlier segment.
 *
 * MPEG-TS has no container-level extradata, so the only place a decoder can get SPS/PPS is in-band. A
 * segment without them decodes only if playback happens to have arrived from the segment before, which
 * makes it invisible during ordinary start-at-zero playback and fatal on a seek. It happens when a
 * stream copy splits an open-GOP source: ffmpeg's TS muxer re-injects parameter sets only ahead of a
 * type-5 IDR, and an open GOP's random-access point is a plain slice carrying an SEI recovery_point.
 *
 * Scans for an Annex-B start code whose NAL header has type 7. A parameter set that is not in the
 * first chunk of the segment is no use for starting there, so a bounded scan is the right test. */
bool SegmentCanSelfStart(const std::filesystem::path &path) {
    std::ifstream in(path, std::ios::binary);
    if (in.fail())
        return false;

    constexpr size_t kScanBytes = 96 * 1024;
    std::vector<unsigned char> buf(kScanBytes);
    in.read(reinterpret_cast<char*>(buf.data()), static_cast<std::streamsize>(buf.size()));
    const size_t got = static_cast<size_t>(in.gcount());
    if (got < 5)
        return false;

    for (size_t i = 0; i + 4 < got; i++) {
        const bool startCode = buf[i] == 0 && buf[i + 1] == 0
                            && ((buf[i + 2] == 1) || (buf[i + 2] == 0 && buf[i + 3] == 1));
        if (!startCode)
            continue;
        const size_t nal = (buf[i + 2] == 1) ? i + 3 : i + 4;
        if (nal < got && (buf[nal] & 0x1F) == 7)
            return true;
    }
    return false;
}

// Segment names sort seg2 before seg10, which alphabetical order would get wrong.
bool SegmentNameLess(const std::string &a, const std::string &b) {
    if (a.size() != b.size())
        return a.size() < b.size();
    return a < b;
}

// HLSParser::parse rejects anything whose first line is not exactly "#EXTM3U" -- it compares the line
// length against 7 before it compares the bytes, so a BOM or trailing text on line one is fatal. It is
// worth catching that here rather than letting the engine fail with an opaque video error.
//
// Also rejects absolute segment URIs: those would be resolved as-is instead of against the playlist's
// own URL, which breaks the moment the playlist is served through a proxy layer from a remote host.
bool PlaylistIsAcceptable(const std::vector<unsigned char> &data, std::string *why) {
    if (data.size() < 7) {
        *why = "playlist is too short";
        return false;
    }
    if (std::string(reinterpret_cast<const char*>(data.data()), 7) != "#EXTM3U") {
        *why = "playlist does not begin with #EXTM3U";
        return false;
    }

    const std::string text(reinterpret_cast<const char*>(data.data()), data.size());
    size_t pos = 0;
    while (pos < text.size()) {
        size_t end = text.find('\n', pos);
        if (end == std::string::npos)
            end = text.size();
        std::string line = text.substr(pos, end - pos);
        pos = end + 1;

        if (!line.empty() && line.back() == '\r')
            line.pop_back();
        if (line.empty() || line[0] == '#')
            continue;

        /* A URI line. What must never appear is a URI carrying a HOST -- "https://cdn/seg0.ts" or the
         * protocol-relative "//cdn/seg0.ts" -- because that pins the segments to one machine and breaks
         * the moment the playlist is served to a client through a proxy layer from a remote host.
         *
         * An absolute PATH ("/video/v1/.../seg0.ts") is a different thing and is fine: it resolves
         * against whichever host served the playlist, which is exactly the routing we want. VideoHandler
         * rewrites the relative names ffmpeg emits into that form when it serves the playlist. */
        if (line.starts_with("//") || line.find("://") != std::string::npos) {
            *why = "playlist contains the host-qualified URI \"" + line + "\"";
            return false;
        }
    }
    return true;
}

#if defined(_WIN32)
constexpr const char *kFfmpegExeName  = "ffmpeg.exe";
constexpr const char *kFfprobeExeName = "ffprobe.exe";
#else
constexpr const char *kFfmpegExeName  = "ffmpeg";
constexpr const char *kFfprobeExeName = "ffprobe";
#endif

}

VideoTranscoder::VideoTranscoder(Core *core) : mCore(core) {
    mPreparationRunning = true;
    mPreparationWorker = std::thread(&VideoTranscoder::RunPreparationWorker, this);
}

VideoTranscoder::~VideoTranscoder() {
    mPreparationRunning = false;
    mPreparationCv.notify_all();
    if (mPreparationWorker.joinable())
        mPreparationWorker.join();
}

bool VideoTranscoder::IsPrepared(const std::string &blobHash, const Options &options) {
    if (blobHash.empty())
        return false;
    Segments unused;
    return ReadExistingSegments(GetSegmentCacheDir(blobHash, options), &unused);
}

bool VideoTranscoder::NeedsPreparation(const std::string &blobHash, const Options &options) {
    if (blobHash.empty())
        return false;
    if (IsPrepared(blobHash, options))
        return false;

    const std::string key = GetSegmentCacheDir(blobHash, options).string();
    std::lock_guard<std::mutex> lock(mPreparationMutex);
    return !mPreparing.contains(key) && !mUnusable.contains(key);
}

void VideoTranscoder::RequestPreparation(int64_t assetId, const std::string &blobHash,
                                         std::vector<unsigned char> video) {
    if (blobHash.empty() || video.empty())
        return;

    const std::filesystem::path cacheDir = GetSegmentCacheDir(blobHash, OptionsFromRegistry());

    Segments unused;
    if (ReadExistingSegments(cacheDir, &unused))
        return;

    {
        std::lock_guard<std::mutex> lock(mPreparationMutex);
        if (mUnusable.contains(cacheDir.string()))
            return;
        if (!mPreparing.insert(cacheDir.string()).second)
            return; // already queued or in flight
        mPreparationQueue.push_back({assetId, cacheDir, std::move(video)});
    }
    Out("VideoTranscoder", "queued asset {} for background preparation", assetId);
    mPreparationCv.notify_one();
}

void VideoTranscoder::RunPreparationWorker() {
    while (mPreparationRunning) {
        PendingPreparation job;
        {
            std::unique_lock<std::mutex> lock(mPreparationMutex);
            mPreparationCv.wait(lock, [&] { return !mPreparationRunning || !mPreparationQueue.empty(); });
            if (!mPreparationRunning)
                break;
            job = std::move(mPreparationQueue.front());
            mPreparationQueue.pop_front();
        }

        Segments segments;
        const Response result = Segment(job.Video, OptionsFromRegistry(), job.CacheDir, &segments);
        if (result == Response::Success)
            Out("VideoTranscoder", "asset {} is ready to stream", job.AssetId);
        else
            Out("VideoTranscoder", "preparing asset {} failed: {}", job.AssetId, ResponseToString(result));

        std::lock_guard<std::mutex> lock(mPreparationMutex);
        mPreparing.erase(job.CacheDir.string());
        // A failure leaves the cache directory empty, which reads exactly like "never tried". Remember
        // it, or every request for a video ffmpeg cannot handle queues another full re-encode of it.
        if (result != Response::Success)
            mUnusable.insert(job.CacheDir.string());
    }
}

const char *VideoTranscoder::ResponseToString(Response response) {
    switch (response) {
    case Response::Success:        return "Success";
    case Response::Disabled:       return "Disabled";
    case Response::NoEncoder:      return "NoEncoder";
    case Response::EmptyInput:     return "EmptyInput";
    case Response::TempFileFailed: return "TempFileFailed";
    case Response::ProbeFailed:    return "ProbeFailed";
    case Response::EncodeFailed:   return "EncodeFailed";
    case Response::OutputMissing:  return "OutputMissing";
    case Response::BadPlaylist:    return "BadPlaylist";
    }
    return "Unknown";
}

bool VideoTranscoder::IsEngineReadable(const Probe &probe) {
    if (!probe.Ok)
        return false;
    /* H.264 only, deliberately. WebmInputFormat exists in the engine but its registration is behind
     * DFFlag VideoRegisterNewWebm, and a WebM upload was observed to play nothing at all rather than
     * fail loudly -- so VP8/VP9 are NOT treated as directly playable and get re-encoded like anything
     * else. Mp4InputFormat is the one demuxer we have evidence works, so H.264/AAC in MP4 is the only
     * combination allowed to skip the encode. */
    const bool video = probe.VideoCodec == "h264";
    const bool audio = probe.AudioCodec.empty() || probe.AudioCodec == "aac" || probe.AudioCodec == "mp3";
    return video && audio;
}

void VideoTranscoder::ResolveTools() {
    std::lock_guard<std::mutex> lock(mResolveMutex);
    if (mResolved)
        return;
    mResolved = true;

    auto configured = mCore->GetRegistry()->GetKeyValue<std::string>("emu.video.ffmpeg_path")
                          .value_or(std::string {});
    if (!configured.empty()) {
        std::filesystem::path path(configured);
        // Accept either the executable itself or the directory holding it.
        std::error_code ec;
        if (std::filesystem::is_directory(path, ec)) {
            if (LooksExecutable(path / kFfmpegExeName))  mFfmpeg  = path / kFfmpegExeName;
            if (LooksExecutable(path / kFfprobeExeName)) mFfprobe = path / kFfprobeExeName;
        } else if (LooksExecutable(path)) {
            mFfmpeg = path;
            const std::filesystem::path sibling = path.parent_path() / kFfprobeExeName;
            if (LooksExecutable(sibling))
                mFfprobe = sibling;
        }
    }

    // Bundled next to the program, which is where packaging puts it.
    if (mFfmpeg.empty()) {
        const std::filesystem::path installed = mCore->GetInstallDataDir() / kFfmpegExeName;
        if (LooksExecutable(installed))
            mFfmpeg = installed;
    }
    if (mFfprobe.empty()) {
        const std::filesystem::path installed = mCore->GetInstallDataDir() / kFfprobeExeName;
        if (LooksExecutable(installed))
            mFfprobe = installed;
    }

    // Otherwise trust PATH and let the process spawn fail if it isn't really there.
    if (mFfmpeg.empty())
        mFfmpeg = kFfmpegExeName;
    if (mFfprobe.empty())
        mFfprobe = kFfprobeExeName;

    Out("VideoTranscoder", "ffmpeg=\"{}\" ffprobe=\"{}\"", mFfmpeg.string(), mFfprobe.string());
}

VideoTranscoder::Options VideoTranscoder::OptionsFromRegistry() {
    Registry *reg = mCore->GetRegistry();
    Options options;
    options.MaxHeight      = static_cast<int>(reg->GetKeyValue<int64_t>("emu.video.max_height").value_or(720));
    options.BitrateKbps    = static_cast<int>(reg->GetKeyValue<int64_t>("emu.video.bitrate_kbps").value_or(2000));
    options.AudioKbps      = static_cast<int>(reg->GetKeyValue<int64_t>("emu.video.audio_kbps").value_or(128));
    options.SegmentSeconds = static_cast<int>(reg->GetKeyValue<int64_t>("emu.video.segment_seconds").value_or(6));
    options.AllowRemux     = reg->GetKeyValue<bool>("emu.video.allow_remux").value_or(true);
    return options;
}

std::filesystem::path VideoTranscoder::MakeTempDir() {
    const uint64_t serial = gTempCounter.fetch_add(1);
    const std::filesystem::path dir =
        mCore->GetUserDataDir() / NW_PATH_TEMP / std::format("video-work-{}", serial);

    std::error_code ec;
    std::filesystem::remove_all(dir, ec);
    std::filesystem::create_directories(dir, ec);
    if (ec)
        return {};
    return dir;
}

std::filesystem::path VideoTranscoder::GetSegmentCacheDir(const std::string &blobHash,
                                                          const Options &options) {
    // The segment length is part of the key rather than the schema constant: changing it in the
    // registry has to regenerate, but it should not invalidate every other setting's cache too.
    return mCore->GetUserDataDir() / NW_PATH_TEMP / "video-segments"
         / std::format("v{}-s{}", kVideoSegmentCacheSchema, options.SegmentSeconds)
         / (blobHash.empty() ? std::string("unknown") : blobHash);
}

VideoTranscoder::Response VideoTranscoder::Inspect(const std::vector<unsigned char> &input, Probe *out) {
    ResolveTools();

    const std::filesystem::path workDir = MakeTempDir();
    if (workDir.empty())
        return Response::TempFileFailed;

    struct Cleanup {
        std::filesystem::path dir;
        ~Cleanup() { std::error_code ec; std::filesystem::remove_all(dir, ec); }
    } cleanup {workDir};

    const std::filesystem::path inFile = workDir / "in.bin";
    if (!WriteWholeFile(inFile, input))
        return Response::TempFileFailed;

    const std::filesystem::path jsonFile = workDir / "probe.json";
    int exitCode = 1;
    const bool spawned = RunProcess(mFfprobe, {
        "-v", "quiet",
        "-print_format", "json",
        "-show_format",
        "-show_streams",
        "-o", jsonFile.string(),
        inFile.string(),
    }, workDir / "probe.log", &exitCode);

    if (!spawned)
        return Response::NoEncoder;
    if (exitCode != 0)
        return Response::ProbeFailed;

    std::vector<unsigned char> jsonBytes;
    if (!ReadWholeFile(jsonFile, &jsonBytes) || jsonBytes.empty())
        return Response::ProbeFailed;

    const nlohmann::json json = nlohmann::json::parse(
        std::string(reinterpret_cast<const char*>(jsonBytes.data()), jsonBytes.size()), nullptr, false);
    if (json.is_discarded() || !json.is_object())
        return Response::ProbeFailed;

    Probe probe;
    probe.Ok = true;

    if (auto fmt = json.find("format"); fmt != json.end() && fmt->is_object()) {
        probe.Container = fmt->value("format_name", std::string {});
        const std::string duration = fmt->value("duration", std::string {});
        if (!duration.empty()) {
            try { probe.DurationSeconds = std::stod(duration); } catch (...) {}
        }
    }

    if (auto streams = json.find("streams"); streams != json.end() && streams->is_array()) {
        for (const auto &stream : *streams) {
            const std::string type = stream.value("codec_type", std::string {});
            if (type == "video" && probe.VideoCodec.empty()) {
                probe.VideoCodec = stream.value("codec_name", std::string {});
                probe.Width  = stream.value("width", 0);
                probe.Height = stream.value("height", 0);
            } else if (type == "audio" && probe.AudioCodec.empty()) {
                probe.AudioCodec = stream.value("codec_name", std::string {});
            }
        }
    }

    if (probe.VideoCodec.empty())
        return Response::ProbeFailed; // audio-only, or not a media file at all

    *out = std::move(probe);
    return Response::Success;
}

bool VideoTranscoder::ReadExistingSegments(const std::filesystem::path &dir, Segments *out) {
    std::error_code ec;
    if (!std::filesystem::exists(dir / kCompleteMarker, ec))
        return false;

    std::vector<unsigned char> playlist;
    if (!ReadWholeFile(dir / kPlaylistName, &playlist) || playlist.empty())
        return false;

    Segments segments;
    segments.PlaylistName = kPlaylistName;
    segments.Names.push_back(kPlaylistName);
    segments.TotalBytes = playlist.size();

    std::vector<std::string> names;
    for (const auto &entry : std::filesystem::directory_iterator(dir, ec)) {
        if (!entry.is_regular_file())
            continue;
        const std::string name = entry.path().filename().string();
        if (name == kPlaylistName || name == kCompleteMarker)
            continue;
        names.push_back(name);
        segments.TotalBytes += static_cast<uint64_t>(entry.file_size(ec));
    }
    if (ec || names.empty())
        return false;

    std::sort(names.begin(), names.end(), SegmentNameLess);
    for (std::string &name : names)
        segments.Names.push_back(std::move(name));

    *out = std::move(segments);
    return true;
}

VideoTranscoder::Response VideoTranscoder::Segment(const std::vector<unsigned char> &video,
                                                   const Options &options,
                                                   const std::filesystem::path &outDir,
                                                   Segments *out) {
    if (video.empty())
        return Response::EmptyInput;

    // Already generated by an earlier request (or an earlier run of the program).
    if (ReadExistingSegments(outDir, out))
        return Response::Success;

    ResolveTools();

    const std::filesystem::path workDir = MakeTempDir();
    if (workDir.empty())
        return Response::TempFileFailed;

    struct Cleanup {
        std::filesystem::path dir;
        ~Cleanup() { std::error_code ec; std::filesystem::remove_all(dir, ec); }
    } cleanup {workDir};

    const std::filesystem::path inFile = workDir / "in.mp4";
    if (!WriteWholeFile(inFile, video))
        return Response::TempFileFailed;

    // Build into the scratch directory and move the finished result into place, so a concurrent
    // request never reads a playlist that references segments that are still being written.
    const std::filesystem::path stageDir = workDir / "out";
    std::error_code ec;
    std::filesystem::create_directories(stageDir, ec);
    if (ec)
        return Response::TempFileFailed;

    // The cache directory is named for the blob hash (GetSegmentCacheDir), so this ties each segment
    // filename to exactly one video. See the -hls_segment_filename comment below for why that matters.
    const std::string segmentPrefix = outDir.filename().string();
    if (segmentPrefix.empty())
        return Response::TempFileFailed;

    /* Decide per input whether a stream copy is actually legal.
     *
     * What arrives here is whatever the user uploaded. Stream-copying a VP9/Opus WebM into MPEG-TS
     * silently produces segments whose video track is muxed as codec_type=data / codec_name=bin_data
     * -- MPEG-TS has no VP9 stream type -- and ffmpeg exits 0 while emitting something with no video
     * in it at all. The engine then fetches segment 0, finds nothing decodable, and stops without a
     * word. That was observed on two real assets before this check existed.
     *
     * So probe first and only copy when the streams are genuinely carriable in MPEG-TS. */
    VideoTranscoder::Probe probe;
    const Response probeResult = Inspect(video, &probe);
    if (probeResult != Response::Success)
        return probeResult;


    /* Stream-copy when the input is ALREADY something MPEG-TS can carry, and re-encode only when it
     * is not. That split is empirical, and both halves cost a regression to learn:
     *
     * - Re-encoding is REQUIRED for anything that is not H.264/AAC. MpegTsInputFormat::parsePmt only
     *   recognises stream_type 0x1B (H.264) and 0x0F (AAC in ADTS); everything else is ignored. A
     *   VP9/Opus WebM stream-copied into TS is muxed as 0x06 (PES private data), so the demuxer finds
     *   zero streams and gives up silently. That is how two real assets failed.
     *
     * - Copying is REQUIRED for material that already works. An H.264/AAC MP4 copied straight through
     *   plays; the same file re-encoded did not. The one sample the engine is known to decode is
     *   Main profile, level 3.0 -- so the re-encode below targets Main/3.1 rather than High, on the
     *   principle that the safest thing to emit is the thing already observed to work.
     *
     * KNOWN GAP, deliberately accepted: ffmpeg's TS muxer only re-injects SPS/PPS ahead of a type-5
     * IDR, so copying an OPEN-GOP source yields later segments that open on a non-IDR slice with no
     * parameter sets (measured: segment 1 began AUD/SEI/non-IDR). Segment 0 still plays, so playback
     * starts, but a seek into such a segment will not decode. Fixing that by always re-encoding broke
     * the copy path outright, which is worse. Revisit by detecting closed-GOP alignment and
     * re-encoding only the sources that need it. */
    const bool canCopy = options.AllowRemux && IsEngineReadable(probe)
                      && (options.MaxHeight <= 0 || probe.Height <= options.MaxHeight);

    // emu.video.transcode only governs re-encoding; repackaging already-suitable streams is cheap and
    // always allowed. With it off, a video the engine could not have played is refused rather than
    // silently costing an encode.
    if (!canCopy && !mCore->GetRegistry()->GetKeyValue<bool>("emu.video.transcode").value_or(true)) {
        Out("VideoTranscoder", "{}/{} needs re-encoding but emu.video.transcode is off",
            probe.VideoCodec, probe.AudioCodec.empty() ? "none" : probe.AudioCodec);
        return Response::Disabled;
    }

    Out("VideoTranscoder", "segmenting {}x{} {}/{} -> {}", probe.Width, probe.Height,
        probe.VideoCodec, probe.AudioCodec.empty() ? "none" : probe.AudioCodec,
        canCopy ? "stream copy" : "re-encode to H.264 Main/3.1 + AAC");

    std::vector<std::string> args {
        "-hide_banner", "-y",
        "-i", inFile.string(),
    };

    if (canCopy) {
        args.insert(args.end(), {"-c", "copy"});
    } else {
        args.insert(args.end(), {
            "-c:v", "libx264",
            /* Main/3.1, never High.
             *
             * MPEG-TS carries no container-level extradata, so MpegTsInputFormat builds the decoder's
             * extradata by parsing the in-band SPS itself -- 0.719 carries the log strings
             * "MpegTsInputFormat: Parsed SPS/PPS - {}x{}, extradata={} bytes" and
             * "MpegTsInputFormat: Failed to extract SPS dimensions" for exactly that. A hand-rolled
             * SPS reader that does not special-case profile_idc 100/110/122/244 misparses a High
             * profile SPS, because High inserts chroma_format_idc, bit depths and the scaling matrix
             * ahead of pic_order_cnt_type. Roblox's own CDN ships avc1.4d40xx, i.e. Main -- so Main is
             * both the safe choice and the one this decoder is actually exercised against. Costs a few
             * percent bitrate and removes the whole risk class. */
            "-profile:v", "main",
            "-level", "3.1",
            "-pix_fmt", "yuv420p",
            "-preset", "veryfast",
            "-b:v", std::format("{}k", options.BitrateKbps),
            "-maxrate", std::format("{}k", options.BitrateKbps),
            "-bufsize", std::format("{}k", options.BitrateKbps * 2),
            // Closed GOP, no scene-cut splits, and an IDR exactly on every segment boundary, so each
            // segment really does begin AUD/SPS/PPS/IDR. Expressed in seconds so it does not depend on
            // knowing the source frame rate.
            "-x264opts", "open-gop=0:scenecut=0",
            "-force_key_frames", std::format("expr:gte(t,n_forced*{})", options.SegmentSeconds),
        });

        if (options.MaxHeight > 0 && probe.Height > options.MaxHeight)
            args.insert(args.end(), {"-vf", std::format("scale=-2:{}", options.MaxHeight)});
        else
            args.insert(args.end(), {"-vf", "scale=trunc(iw/2)*2:trunc(ih/2)*2"});

        if (probe.AudioCodec.empty())
            args.push_back("-an");
        else
            args.insert(args.end(), {"-c:a", "aac", "-b:a", std::format("{}k", options.AudioKbps)});
    }

    args.insert(args.end(), {
        // Segment timestamps start at zero. A stream copy otherwise carries the source's own timebase
        // through -- observed starting at 1.43 s -- which disagrees with #EXT-X-MEDIA-SEQUENCE:0 and is
        // a needless thing for a player to have to reconcile.
        "-muxdelay", "0",
        "-muxpreload", "0",
        "-avoid_negative_ts", "make_zero",
        "-f", "hls",
        "-hls_time", std::to_string(options.SegmentSeconds),
        "-hls_playlist_type", "vod",  // emits #EXT-X-ENDLIST, which is what marks this seekable VOD
        "-hls_list_size", "0",        // keep every segment in the playlist
        "-hls_flags", "independent_segments",
        // Explicit: fMP4 segments would need #EXT-X-MAP and an init segment, and the engine's TS
        // demuxer cannot read them at all.
        "-hls_segment_type", "mpegts",
        /* Segments are named "<blob hash>-<n>.ts" rather than "seg<n>.ts", and the name is what makes
         * them findable.
         *
         * The engine does not resolve a playlist's relative URIs against the URL the playlist was
         * served from; observed behaviour is that it uses the URL the ASSET was requested from
         * (/v1/asset/), so a bare "seg0.ts" is fetched as /v1/asset/seg0.ts. VideoHandler rewrites the
         * playlist to absolute paths to avoid that, but a name carrying its own blob hash means even a
         * request that arrives at the wrong path still identifies exactly one video, so VideoHandler
         * can answer it from /v1/asset/<name> too. Two independent mechanisms, because the base URI is
         * the engine's choice and not ours.
         *
         * Still relative, still no directory component -- see the header for why an absolute host in a
         * playlist would break the EmulatorProxy path. %d is ffmpeg's segment index. */
        "-hls_segment_filename", (stageDir / (segmentPrefix + "-%d.ts")).string(),
        (stageDir / kPlaylistName).string(),
    });

    int exitCode = 1;
    const std::filesystem::path logPath = workDir / "ffmpeg.log";
    if (!RunProcess(mFfmpeg, args, logPath, &exitCode))
        return Response::NoEncoder;
    if (exitCode != 0) {
        Out("VideoTranscoder", "segmenting failed (exit {}): {}", exitCode, LogTail(logPath));
        return Response::EncodeFailed;
    }

    std::vector<unsigned char> playlist;
    if (!ReadWholeFile(stageDir / kPlaylistName, &playlist) || playlist.empty())
        return Response::OutputMissing;

    std::string why;
    if (!PlaylistIsAcceptable(playlist, &why)) {
        Out("VideoTranscoder", "refusing generated playlist: {}", why);
        return Response::BadPlaylist;
    }

    // Count what was produced before publishing, so an empty run is caught here.
    size_t segmentCount = 0;
    for (const auto &entry : std::filesystem::directory_iterator(stageDir, ec)) {
        if (entry.is_regular_file() && entry.path().filename() != kPlaylistName)
            segmentCount++;
    }
    if (ec || segmentCount == 0) {
        Out("VideoTranscoder", "segmenting produced a playlist with no segments");
        return Response::OutputMissing;
    }

    /* A stream copy can produce segments that cannot be started from. Verify rather than assume.
     *
     * Copying an open-GOP source leaves later segments opening on a plain slice with no SPS/PPS -- the
     * decoder can only get through them by having decoded the previous segment, so start-at-zero
     * playback looks fine and any seek into them fails. Measured on a real cached video before this
     * check existed. There is no cheap way to know in advance, so segment first and check the output;
     * if any segment cannot self-start, throw it away and re-encode, which forces an IDR onto every
     * boundary. Costs one wasted copy on the videos that need it and nothing on the ones that do not. */
    if (canCopy) {
        std::string unstartable;
        for (const auto &entry : std::filesystem::directory_iterator(stageDir, ec)) {
            if (!entry.is_regular_file() || entry.path().filename() == kPlaylistName)
                continue;
            if (!SegmentCanSelfStart(entry.path())) {
                unstartable = entry.path().filename().string();
                break;
            }
        }
        if (!unstartable.empty()) {
            Out("VideoTranscoder",
                "stream copy left \"{}\" without parameter sets (open-GOP source); re-encoding instead",
                unstartable);
            std::error_code cleanupEc;
            std::filesystem::remove_all(stageDir, cleanupEc);
            Options forced = options;
            forced.AllowRemux = false;   // take the re-encode branch on the retry
            return Segment(video, forced, outDir, out);
        }
    }

    if (!WriteWholeFile(stageDir / kCompleteMarker, {}))
        return Response::TempFileFailed;

    std::filesystem::create_directories(outDir.parent_path(), ec);
    std::filesystem::remove_all(outDir, ec);
    std::filesystem::rename(stageDir, outDir, ec);
    if (ec) {
        // Cross-device rename (the scratch and cache trees can land on different mounts): fall back to
        // copying, which is slower but correct.
        std::error_code copyEc;
        std::filesystem::copy(stageDir, outDir,
                              std::filesystem::copy_options::recursive
                            | std::filesystem::copy_options::overwrite_existing, copyEc);
        if (copyEc) {
            Out("VideoTranscoder", "could not publish segments to \"{}\": {}",
                outDir.string(), copyEc.message());
            return Response::TempFileFailed;
        }
    }

    if (!ReadExistingSegments(outDir, out))
        return Response::OutputMissing;

    Out("VideoTranscoder", "segmented into {} file(s), {} bytes at \"{}\"",
        out->Names.size(), out->TotalBytes, outDir.string());
    return Response::Success;
}
