/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: loader_shellcode.cpp
// Started by: Hattozo
// Started on: 8/12/2025
// Description: loader_shellcode.cpp — compiled as a minimal shellcode
// Usage: the injector extracts this function's machine code and writes it
// into the target process, then CreateRemoteThread's to it.
//
// Build:  cl /c /O1 /GS- /Gs9999999 loader_shellcode.cpp
//         link /SUBSYSTEM:CONSOLE loader_shellcode.obj
// (Code was generated by DeepSeek V4 Pro and GPT 5.6 Sol)

#include <windows.h>
#include <cstdint>

#pragma comment(linker, "/ENTRY:ShellcodeEntry")
#pragma comment(linker, "/NODEFAULTLIB")
#pragma comment(linker, "/SUBSYSTEM:WINDOWS")

// This struct is written to remote memory before the shellcode runs.
struct LoaderParams {
    HMODULE hNtdll;
    FARPROC pLdrLoadDll;
    wchar_t dllPath[MAX_PATH];
    HMODULE resultModule;
};

extern "C" void ShellcodeEntry() {
    LoaderParams* params = (LoaderParams*)0x1000000000;  // hardcoded address
    
    // Build UNICODE_STRING for the DLL path
    UNICODE_STRING us;
    us.Buffer = params->dllPath;
    us.Length = 0;
    us.MaximumLength = MAX_PATH * sizeof(wchar_t);
    for (int i = 0; i < MAX_PATH && params->dllPath[i]; i++)
        us.Length += sizeof(wchar_t);

    // Call LdrLoadDll with DONT_RESOLVE_DLL_REFERENCES (0x2) flag
    // This maps the DLL but skips DllMain.
    using LdrLoadDll_t = NTSTATUS(NTAPI*)(PWSTR, ULONG, PUNICODE_STRING, PHANDLE);
    auto pLdrLoadDll = (LdrLoadDll_t)params->pLdrLoadDll;
    
    HANDLE hModule = NULL;
    NTSTATUS st = pLdrLoadDll(nullptr, 0x2, &us, &hModule);
    params->resultModule = (HMODULE)hModule;
}
