// === noobWarrior ===
// File: Application.cpp
// Started by: Hattozo
// Started on: 5/18/2025
// Description: Main entrypoint for Qt application
#include "Application.h"

#include <NoobWarrior/Config.h>

#include <QApplication>
#include <QFontDatabase>
#include <QLabel>
#include <QMessageBox>
#include <QFile>

#include <curl/curl.h>

#define USE_CUSTOM_STYLESHEET 0

using namespace NoobWarrior;

Application *NoobWarrior::gApp = nullptr;

Application::Application(int &argc, char **argv) : QApplication(argc, argv)
{}

int Application::Run() {
    int ret = 1;

    Init init;
    init.Portable = std::filesystem::exists(Config::GetInstallationDir().append("NW_PORTABLE"));

    mCore = new Core(init);
    mCore->StartHttpServer(8080);
    CURLcode curlRet = curl_global_init(CURL_GLOBAL_ALL);
    if (curlRet != CURLE_OK) {
        QMessageBox::critical(nullptr, "Error", "Could not initialize curl");
        return curlRet;
    }
    int cfgRet = mCore->GetConfig()->ReadFromFile();
    if (!cfgRet) {
        QMessageBox::critical(nullptr, "Error", QString("Could not read config file.\n\n%1").arg(cfgRet == -1 ?
            "The JSON data could not be parsed correctly. Delete the file so that it is regenerated by the program, or fix any syntax errors that are preventing it from being parsed correctly." :
            "Cannot read the contents of the file. Check if you have the appropriate permissions to be able to read from it."));
        return 0xC03F16DD; // Kind of reads out as "Config Dead Dead?"
    }
    QFontDatabase::addApplicationFont(":/fonts/SourceSansPro-Regular.ttf");
    QFontDatabase::addApplicationFont(":/fonts/SourceSansPro-Bold.ttf");
    QFontDatabase::addApplicationFont(":/fonts/FiraMono-Regular.ttf");
    QFontDatabase::addApplicationFont(":/fonts/FiraMono-Medium.ttf");
    QFontDatabase::addApplicationFont(":/fonts/FiraMono-Bold.ttf");
    mLauncher = new Launcher();
#if USE_CUSTOM_STYLESHEET
    QFile styleFile(":/css/style.css");
    if (styleFile.open(QIODevice::ReadOnly | QIODevice::Text)) {
        QTextStream in(&styleFile);
        app.setStyleSheet(in.readAll());
    }
#endif
#if !defined(Q_OS_MACOS)
    QMessageBox::StandardButton res = QMessageBox::question(nullptr, "Warning",
        "What you are running is incomplete software. Nothing here is suitable for production. Things are bound to change, especially the way critical data is parsed by the program.\n\nBy clicking Yes, you agree to the statement that anything you try to create with this version of the software will eventually be corrupted due to unforeseen consequences.",
        QMessageBox::Yes | QMessageBox::No,
        QMessageBox::No);
#else
    QMessageBox msg;
    msg.setText("You are running software that is likely broken");
    msg.setInformativeText("Nothing here is suitable for production. Things are bound to change, especially the way critical data is parsed by the program.\n\nBy clicking Yes, you agree to the statement that anything you try to create with this version of the software will eventually be corrupted due to unforeseen consequences.");
    msg.setStandardButtons(QMessageBox::Yes | QMessageBox::No);
    msg.setDefaultButton(QMessageBox::No);
    int res = msg.exec();
#endif
    if (res != QMessageBox::Yes)
        goto cleanup;
    mLauncher->show();
    ret = exec();
cleanup:
    Out("QtApplication", "Cleaning up!");

    mLauncher->deleteLater();
    mLauncher = nullptr;

    curl_global_cleanup();
    mCore->StopHttpServer();
    mCore->GetConfig()->WriteToFile();
    return ret;
}

Core *Application::GetCore() {
    return mCore;
}

int main(int argc, char **argv) {
    Q_INIT_RESOURCE(resources);
    Application app(argc, argv);
    gApp = &app;
    return app.Run();
}
