/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: AssetEnricher.cpp
// Started by: Hattozo
// Started on: 5/28/2026
// Description: See AssetEnricher.h.
//              (Disclaimer: This code was created by Claude Opus 4.8 and Fable 5.)
#include <cpr/cpr.h>

#include <NoobWarrior/EmuDb/AssetEnricher.h>
#include <NoobWarrior/EmuDb/EmuDb.h>
#include <NoobWarrior/EmuDb/ItemType.h>
#include <NoobWarrior/Roblox/Api/Asset.h>
#include <NoobWarrior/NoobWarrior.h>
#include <NoobWarrior/Log.h>

#include <nlohmann/json.hpp>
#include <curl/curl.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdio>
#include <ctime>
#include <thread>
#include <unordered_map>

using namespace NoobWarrior;
using json = nlohmann::json;

// develop.roblox.com returns the asset type as a (space-less) PascalCase string. This is
// best-effort: an unmapped type just leaves Type unset, which is fine because the SDK falls
// back to the autogenerated thumbnail for the preview either way. Declared in AssetEnricher.h so
// the backup's file-found-asset enrichment shares one mapping.
Roblox::AssetType NoobWarrior::AssetTypeFromApiString(const std::string &s) {
    static const std::unordered_map<std::string, Roblox::AssetType> map = {
        {"Image", Roblox::AssetType::Image}, {"TShirt", Roblox::AssetType::TShirt},
        {"Audio", Roblox::AssetType::Audio}, {"Mesh", Roblox::AssetType::Mesh},
        {"Lua", Roblox::AssetType::Lua}, {"Hat", Roblox::AssetType::Hat},
        {"Place", Roblox::AssetType::Place}, {"Model", Roblox::AssetType::Model},
        {"Shirt", Roblox::AssetType::Shirt}, {"Pants", Roblox::AssetType::Pants},
        {"Decal", Roblox::AssetType::Decal}, {"Head", Roblox::AssetType::Head},
        {"Face", Roblox::AssetType::Face}, {"Gear", Roblox::AssetType::Gear},
        {"Badge", Roblox::AssetType::Badge}, {"Animation", Roblox::AssetType::Animation},
        {"Torso", Roblox::AssetType::Torso}, {"RightArm", Roblox::AssetType::RightArm},
        {"LeftArm", Roblox::AssetType::LeftArm}, {"LeftLeg", Roblox::AssetType::LeftLeg},
        {"RightLeg", Roblox::AssetType::RightLeg}, {"Package", Roblox::AssetType::Package},
        {"GamePass", Roblox::AssetType::Gamepass}, {"Gamepass", Roblox::AssetType::Gamepass},
        {"Plugin", Roblox::AssetType::Plugin}, {"MeshPart", Roblox::AssetType::MeshPart},
        {"HairAccessory", Roblox::AssetType::HairAccessory}, {"FaceAccessory", Roblox::AssetType::FaceAccessory},
        {"NeckAccessory", Roblox::AssetType::NeckAccessory}, {"ShoulderAccessory", Roblox::AssetType::ShoulderAccessory},
        {"FrontAccessory", Roblox::AssetType::FrontAccessory}, {"BackAccessory", Roblox::AssetType::BackAccessory},
        {"WaistAccessory", Roblox::AssetType::WaistAccessory}, {"ClimbAnimation", Roblox::AssetType::ClimbAnimation},
        {"DeathAnimation", Roblox::AssetType::DeathAnimation}, {"FallAnimation", Roblox::AssetType::FallAnimation},
        {"IdleAnimation", Roblox::AssetType::IdleAnimation}, {"JumpAnimation", Roblox::AssetType::JumpAnimation},
        {"RunAnimation", Roblox::AssetType::RunAnimation}, {"SwimAnimation", Roblox::AssetType::SwimAnimation},
        {"WalkAnimation", Roblox::AssetType::WalkAnimation}, {"PoseAnimation", Roblox::AssetType::PoseAnimation},
        {"EarAccessory", Roblox::AssetType::EarAccessory}, {"EyeAccessory", Roblox::AssetType::EyeAccessory},
        {"EmoteAnimation", Roblox::AssetType::EmoteAnimation}, {"Video", Roblox::AssetType::Video},
        {"TShirtAccessory", Roblox::AssetType::TShirtAccessory}, {"ShirtAccessory", Roblox::AssetType::ShirtAccessory},
        {"PantsAccessory", Roblox::AssetType::PantsAccessory}, {"JacketAccessory", Roblox::AssetType::JacketAccessory},
        {"SweaterAccessory", Roblox::AssetType::SweaterAccessory}, {"ShortsAccessory", Roblox::AssetType::ShortsAccessory},
        {"LeftShoeAccessory", Roblox::AssetType::LeftShoeAccessory}, {"RightShoeAccessory", Roblox::AssetType::RightShoeAccessory},
        {"DressSkirtAccessory", Roblox::AssetType::DressSkirtAccessory}, {"FontFamily", Roblox::AssetType::FontFamily},
        {"EyebrowAccessory", Roblox::AssetType::EyebrowAccessory}, {"EyelashAccessory", Roblox::AssetType::EyelashAccessory},
        {"MoodAnimation", Roblox::AssetType::MoodAnimation}, {"DynamicHead", Roblox::AssetType::DynamicHead},
        {"FaceMakeup", Roblox::AssetType::FaceMakeup}, {"LipMakeup", Roblox::AssetType::LipMakeup},
        {"EyeMakeup", Roblox::AssetType::EyeMakeup},
        {"SolidModel", Roblox::AssetType::SolidModel},
    };
    auto it = map.find(s);
    return it != map.end() ? it->second : Roblox::AssetType::None;
}

// Declared in AssetEnricher.h; the one shared ISO-8601 parser for every metadata fetcher. Unlike
// the old per-file copies this both accepts a trailing "+HH:MM"/"-HH:MM" offset (shifting back to
// UTC) and returns 0 on failure.
int64_t NoobWarrior::ParseIso8601Utc(const std::string &s) {
    if (s.empty()) return 0;
    int year, mon, day, hour = 0, min = 0;
    double sec = 0;
    if (std::sscanf(s.c_str(), "%d-%d-%dT%d:%d:%lf", &year, &mon, &day, &hour, &min, &sec) < 3)
        return 0;
    std::tm tm{};
    tm.tm_year = year - 1900;
    tm.tm_mon  = mon - 1;
    tm.tm_mday = day;
    tm.tm_hour = hour;
    tm.tm_min  = min;
    tm.tm_sec  = static_cast<int>(sec);
#if defined(_WIN32)
    time_t t = _mkgmtime(&tm);
#else
    time_t t = timegm(&tm);
#endif
    if (t < 0)
        return 0;

    // A trailing "+HH:MM"/"-HH:MM" names a local offset; shift back to UTC. ("Z" needs nothing.)
    size_t tpos = s.find('T');
    if (tpos != std::string::npos) {
        size_t off = s.find_first_of("+-", tpos);
        if (off != std::string::npos) {
            int oh = 0, om = 0;
            std::sscanf(s.c_str() + off + 1, "%2d:%2d", &oh, &om);
            t -= (oh * 3600 + om * 60) * (s[off] == '-' ? -1 : 1);
        }
    }
    return static_cast<int64_t>(t);
}

AssetEnricher::AssetEnricher(Core *core) :
    mCore(core)
{}

AssetEnricher::~AssetEnricher() {
    Stop();
}

void AssetEnricher::Start() {
    bool expected = false;
    if (!mRunning.compare_exchange_strong(expected, true))
        return; // already running
    mThread = std::thread(&AssetEnricher::WorkerLoop, this);
}

void AssetEnricher::Stop() {
    {
        // The flag must flip under the same mutex the worker's wait predicate reads, or the
        // notify can land in the gap between the predicate check and the actual block; a lost
        // wakeup that leaves this join()ing a worker that sleeps forever (and the app hanging on
        // exit, since ServerEmulator's teardown runs through here).
        std::lock_guard<std::mutex> lock(mMutex);
        if (!mRunning.exchange(false))
            return;
    }
    mCv.notify_all();
    if (mThread.joinable())
        mThread.join();
    CloseConnections(); // safe: worker thread has exited
}

void AssetEnricher::Enqueue(const std::string &dbFilePath, int64_t assetId) {
    // Snapshot the auth cookie here, on the caller's (event-loop) thread, so the worker never
    // touches the keychain concurrently. It travels with the job: a later login/logout must not
    // retroactively change how the already-queued backlog is fetched.
    std::string cookie;
    if (auto *acc = mCore->GetRbxKeychain()->GetActiveAccount())
        cookie = ".ROBLOSECURITY=" + acc->Token + ";";

    {
        std::lock_guard<std::mutex> lock(mMutex);
        if (!mPending.insert({dbFilePath, assetId}).second)
            return; // already queued or in flight for this database
        mQueue.push_back(Job{dbFilePath, assetId, std::move(cookie), 0});
    }
    mCv.notify_one();
}

void AssetEnricher::WorkerLoop() {
    while (mRunning) {
        std::string dbFilePath;
        std::vector<Job> jobs;

        {
            std::unique_lock<std::mutex> lock(mMutex);
            mCv.wait(lock, [&] { return !mRunning || !mQueue.empty(); });
            if (!mRunning)
                break;

            // Collect up to a batch of jobs sharing the FRONT job's database from anywhere in the
            // queue; taking only the contiguous front would fragment interleaved targets down to
            // one-id batches. The ids stay in mPending while the batch is in flight, so duplicate
            // grabs during processing still dedupe.
            dbFilePath = mQueue.front().DbFilePath;
            for (auto it = mQueue.begin(); it != mQueue.end() && jobs.size() < kMaxBatchSize;) {
                if (it->DbFilePath == dbFilePath) {
                    jobs.push_back(std::move(*it));
                    it = mQueue.erase(it);
                } else {
                    ++it;
                }
            }
        }

        if (!jobs.empty()) {
            BatchResult result = ProcessBatch(dbFilePath, jobs);

            std::lock_guard<std::mutex> lock(mMutex);
            if (result == BatchResult::RetryLater && mRunning) {
                // Transient failure (network blip, exhausted rate-limit retries, connection lost
                // to a lock race): a batch used to be dropped on the floor here, permanently
                // stranding up to 50 assets with placeholder names. Re-queue at the back with a
                // per-job attempt cap instead.
                for (Job &job : jobs) {
                    if (++job.Attempts < kMaxJobAttempts) {
                        mQueue.push_back(std::move(job));
                    } else {
                        mCore->Out("AssetEnricher", "Giving up on asset {} after {} failed batches",
                            job.AssetId, kMaxJobAttempts);
                        mPending.erase({dbFilePath, job.AssetId});
                    }
                }
            } else {
                for (const Job &job : jobs)
                    mPending.erase({dbFilePath, job.AssetId});
            }
        }

        // Keep develop.roblox.com calls comfortably under its 100/min budget.
        if (mRunning)
            std::this_thread::sleep_for(std::chrono::milliseconds(kInterBatchDelayMs));
    }
}

EmuDb* AssetEnricher::GetConnection(const std::string &dbFilePath) {
    auto it = mConnections.find(dbFilePath);
    if (it != mConnections.end())
        return it->second;

    // This is a second, private connection to the same file, so a read-only mount does not constrain
    // it. Honor the database's own Mutable flag here or enrichment would quietly write name, type and
    // thumbnails into a database that asked not to be modified. Probing is safe from this thread: it
    // opens its own read-only connection and touches no shared state. The refusal is NOT cached;
    // the user is told to flip the Mutable setting back on, and doing so must start working on the
    // next batch, not after a restart. (The probe is one cheap read-only query per batch.)
    if (!EmuDb::ProbeIsMutable(dbFilePath)) {
        if (mWarnedImmutable.insert(dbFilePath).second)
            mCore->Out("AssetEnricher", "Refusing to enrich \"{}\" because its Mutable setting is off", dbFilePath);
        return nullptr;
    }
    mWarnedImmutable.erase(dbFilePath); // mutable again: warn afresh if it ever flips back

    auto *db = new EmuDb(dbFilePath, true);
    if (db->Fail()) {
        // Not cached either: this can be a transient lock race against the mounted connection.
        mCore->Out("AssetEnricher", "Failed to open enrichment connection to \"{}\"", dbFilePath);
        delete db;
        return nullptr;
    }
    // The busy_timeout every connection now gets at open (SqlDb constructor) covers the write
    // contention with the mounted main-thread connection.
    mConnections[dbFilePath] = db;
    return db;
}

void AssetEnricher::CloseConnections() {
    for (auto &[path, db] : mConnections)
        delete db;
    mConnections.clear();
}

AssetEnricher::BatchResult AssetEnricher::ProcessBatch(const std::string &dbFilePath, const std::vector<Job> &jobs) {
    EmuDb *db = GetConnection(dbFilePath);
    if (db == nullptr)
        return BatchResult::RetryLater; // could be a lock race or a Mutable flag about to be fixed

    std::string idList;
    for (size_t i = 0; i < jobs.size(); i++) {
        if (i) idList += ",";
        idList += std::to_string(jobs[i].AssetId);
    }

    // Freshest cookie in the batch (jobs queue in arrival order).
    std::string cookie;
    for (auto it = jobs.rbegin(); it != jobs.rend(); ++it) {
        if (!it->Cookie.empty()) {
            cookie = it->Cookie;
            break;
        }
    }

    // A plain GET against a Roblox endpoint, verifying against the OS certificate store. The
    // timeouts matter: without them a stalled connection (sleep/resume, Wi-Fi drop) blocks this
    // worker forever; and Stop() joins it, so app exit would hang too.
    auto fetchGet = [](const std::string &url, const std::string &cookie) -> cpr::Response {
        cpr::Session session;
        session.SetUrl(cpr::Url{url});
        session.SetUserAgent(cpr::UserAgent{"Roblox/WinINet"});
        session.SetConnectTimeout(cpr::ConnectTimeout{10000});
        session.SetTimeout(cpr::Timeout{30000});
        if (!cookie.empty())
            session.SetHeader(cpr::Header{{"Cookie", cookie}});
        curl_easy_setopt(session.GetCurlHolder()->handle, CURLOPT_SSL_OPTIONS, (long)CURLSSLOPT_NATIVE_CA);
        return session.Get();
    };
    // Ride out 429s with a short backoff; both batch endpoints share this.
    auto fetchWithRetry = [&](const std::string &url, const std::string &ck) -> cpr::Response {
        cpr::Response r;
        for (int attempt = 0; attempt < 3; attempt++) {
            r = fetchGet(url, ck);
            if (r.error.code == cpr::ErrorCode::OK && r.status_code == 429 && mRunning) {
                std::this_thread::sleep_for(std::chrono::milliseconds(1000 * (attempt + 1)));
                continue;
            }
            break;
        }
        return r;
    };

    bool transientFailure = false;

    //////////////// Metadata: develop.roblox.com/v1/assets (batch, needs auth) ////////////////
    if (cookie.empty()) {
        static std::atomic<bool> warned{false};
        if (!warned.exchange(true))
            mCore->Out("AssetEnricher", "No logged-in Roblox account; grabbed assets will keep placeholder names (thumbnails still work). Log in to fetch real names/descriptions.");
    } else {
        std::string metaUrl = "https://develop.roblox.com/v1/assets?assetIds=" + idList;
        cpr::Response meta = fetchWithRetry(metaUrl, cookie);

        if (meta.error.code == cpr::ErrorCode::OK && meta.status_code == 200) {
            json root = json::parse(meta.text, nullptr, false);
            if (root.is_discarded() || !root.contains("data") || !root["data"].is_array()) {
                std::string preview = meta.text.substr(0, std::min<size_t>(meta.text.size(), 300));
                mCore->Out("AssetEnricher", "Unexpected develop /v1/assets response shape: {}", preview);
            } else {
                for (auto &a : root["data"]) {
                    int64_t id = a.contains("id") && a["id"].is_number() ? a["id"].get<int64_t>() : 0;
                    if (id == 0)
                        continue;

                    SqlRow row;
                    if (a.contains("name") && a["name"].is_string())
                        row.push_back({"Name", a["name"].get<std::string>()});
                    if (a.contains("description") && a["description"].is_string())
                        row.push_back({"Description", a["description"].get<std::string>()});
                    if (a.contains("created") && a["created"].is_string()) {
                        int64_t ts = ParseIso8601Utc(a["created"].get<std::string>());
                        if (ts) row.push_back({"Created", ts});
                    }
                    if (a.contains("updated") && a["updated"].is_string()) {
                        int64_t ts = ParseIso8601Utc(a["updated"].get<std::string>());
                        if (ts) row.push_back({"Updated", ts});
                    }
                    if (a.contains("type") && a["type"].is_string()) {
                        Roblox::AssetType t = AssetTypeFromApiString(a["type"].get<std::string>());
                        if (t != Roblox::AssetType::None)
                            row.push_back({"Type", static_cast<int>(t)});
                    }
                    if (a.contains("creator") && a["creator"].is_object()) {
                        const json &c = a["creator"];
                        int64_t creatorId = c.contains("targetId") && c["targetId"].is_number() ? c["targetId"].get<int64_t>()
                                          : (c.contains("id") && c["id"].is_number() ? c["id"].get<int64_t>() : 0);
                        std::string cType = c.contains("type") && c["type"].is_string() ? c["type"].get<std::string>() : "";
                        if (creatorId != 0)
                            row.push_back({cType == "Group" ? "GroupId" : "UserId", creatorId});
                    }

                    if (!row.empty()) {
                        // No MarkDirty here: this private connection runs autocommit, and the
                        // dirty flag belongs to the mounted connection anyway. Failures used to
                        // vanish silently; a Busy after the 5s timeout or a vanished row
                        // (NotFound) at least leaves a trace now.
                        SqlDb::Response updateRes = db->UpdateItem(ItemType::Asset, id, row);
                        if (updateRes != SqlDb::Response::Success)
                            mCore->Out("AssetEnricher", "Metadata update for asset {} failed (code={})",
                                id, (int)updateRes);
                    }
                }
            }
        } else {
            mCore->Out("AssetEnricher", "develop /v1/assets fetch failed (curl={} http={}) for ids {}",
                (int)meta.error.code, meta.status_code, idList);
            transientFailure = true; // network blip or exhausted 429 retries: worth another pass
        }
    }

    //////////////// Images: thumbnails.roblox.com/v1/assets (batch, no auth) ////////////////
    std::string thumbUrl = "https://thumbnails.roblox.com/v1/assets?assetIds=" + idList + "&size=420x420&format=Png&isCircular=false";
    cpr::Response thumbRes = fetchWithRetry(thumbUrl, "");
    if (thumbRes.error.code != cpr::ErrorCode::OK || thumbRes.status_code != 200) {
        // This used to bail with no log and no retry, silently skipping every thumbnail in the
        // batch forever.
        mCore->Out("AssetEnricher", "thumbnails /v1/assets fetch failed (curl={} http={}) for ids {}",
            (int)thumbRes.error.code, thumbRes.status_code, idList);
        return BatchResult::RetryLater;
    }

    json troot = json::parse(thumbRes.text, nullptr, false);
    if (troot.is_discarded() || !troot.contains("data") || !troot["data"].is_array()) {
        mCore->Out("AssetEnricher", "Unexpected thumbnails /v1/assets response shape for ids {}", idList);
        return transientFailure ? BatchResult::RetryLater : BatchResult::Ok;
    }

    std::vector<int64_t> thumbIds;
    std::vector<std::string> imageUrls;
    for (auto &t : troot["data"]) {
        if (!t.contains("state") || !t["state"].is_string() || t["state"].get<std::string>() != "Completed")
            continue;
        if (!t.contains("imageUrl") || !t["imageUrl"].is_string())
            continue;
        int64_t targetId = t.contains("targetId") && t["targetId"].is_number() ? t["targetId"].get<int64_t>() : 0;
        if (targetId == 0)
            continue;

        thumbIds.push_back(targetId);
        imageUrls.push_back(t["imageUrl"].get<std::string>());
    }

    if (imageUrls.empty())
        return transientFailure ? BatchResult::RetryLater : BatchResult::Ok;

    std::vector<std::vector<unsigned char>> imageBodies(imageUrls.size());
    std::vector<char> imageOk(imageUrls.size(), 0);

    const size_t kMaxConcurrency = 8;
    size_t hw = std::thread::hardware_concurrency();
    if (hw == 0) hw = 4;
    size_t workers = std::min({imageUrls.size(), kMaxConcurrency, hw});

    std::atomic<size_t> nextIndex{0};
    std::vector<std::thread> threads;
    threads.reserve(workers);
    for (size_t w = 0; w < workers; w++) {
        threads.emplace_back([&]() {
            for (;;) {
                size_t i = nextIndex.fetch_add(1, std::memory_order_relaxed);
                if (i >= imageUrls.size()) return;
                cpr::Response img = fetchGet(imageUrls[i], "");
                if (img.error.code == cpr::ErrorCode::OK && img.status_code == 200 && !img.text.empty()) {
                    imageBodies[i].assign(img.text.begin(), img.text.end());
                    imageOk[i] = 1;
                }
            }
        });
    }
    for (auto &t : threads) t.join();

    size_t attachFailures = 0;
    for (size_t i = 0; i < imageBodies.size() && i < thumbIds.size(); i++) {
        if (!imageOk[i] || imageBodies[i].empty()) {
            attachFailures++;
            continue;
        }
        if (db->AttachThumbnailDataToAsset(thumbIds[i], imageBodies[i]) != SqlDb::Response::Success)
            attachFailures++;
    }
    if (attachFailures > 0)
        mCore->Out("AssetEnricher", "{} of {} thumbnails could not be downloaded or stored for ids {}",
            attachFailures, imageUrls.size(), idList);

    return transientFailure ? BatchResult::RetryLater : BatchResult::Ok;
}
