/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: AssetEnricher.cpp
// Started by: Hattozo
// Started on: 5/28/2026
// Description: See AssetEnricher.h.
//              (Disclaimer: This code was created by Claude Opus 4.8.)
#include <NoobWarrior/EmuDb/AssetEnricher.h>
#include <NoobWarrior/EmuDb/EmuDb.h>
#include <NoobWarrior/EmuDb/ItemType.h>
#include <NoobWarrior/Roblox/Api/Asset.h>
#include <NoobWarrior/NetClient.h>
#include <NoobWarrior/NoobWarrior.h>
#include <NoobWarrior/Log.h>

#include <nlohmann/json.hpp>

#include <chrono>
#include <cstdio>
#include <ctime>
#include <unordered_map>

using namespace NoobWarrior;
using json = nlohmann::json;

namespace {
// develop.roblox.com returns the asset type as a (space-less) PascalCase string. This is
// best-effort: an unmapped type just leaves Type unset, which is fine because the SDK falls
// back to the autogenerated thumbnail for the preview either way.
Roblox::AssetType AssetTypeFromString(const std::string &s) {
    static const std::unordered_map<std::string, Roblox::AssetType> map = {
        {"Image", Roblox::AssetType::Image}, {"TShirt", Roblox::AssetType::TShirt},
        {"Audio", Roblox::AssetType::Audio}, {"Mesh", Roblox::AssetType::Mesh},
        {"Lua", Roblox::AssetType::Lua}, {"Hat", Roblox::AssetType::Hat},
        {"Place", Roblox::AssetType::Place}, {"Model", Roblox::AssetType::Model},
        {"Shirt", Roblox::AssetType::Shirt}, {"Pants", Roblox::AssetType::Pants},
        {"Decal", Roblox::AssetType::Decal}, {"Head", Roblox::AssetType::Head},
        {"Face", Roblox::AssetType::Face}, {"Gear", Roblox::AssetType::Gear},
        {"Badge", Roblox::AssetType::Badge}, {"Animation", Roblox::AssetType::Animation},
        {"Torso", Roblox::AssetType::Torso}, {"RightArm", Roblox::AssetType::RightArm},
        {"LeftArm", Roblox::AssetType::LeftArm}, {"LeftLeg", Roblox::AssetType::LeftLeg},
        {"RightLeg", Roblox::AssetType::RightLeg}, {"Package", Roblox::AssetType::Package},
        {"GamePass", Roblox::AssetType::Gamepass}, {"Gamepass", Roblox::AssetType::Gamepass},
        {"Plugin", Roblox::AssetType::Plugin}, {"MeshPart", Roblox::AssetType::MeshPart},
        {"HairAccessory", Roblox::AssetType::HairAccessory}, {"FaceAccessory", Roblox::AssetType::FaceAccessory},
        {"NeckAccessory", Roblox::AssetType::NeckAccessory}, {"ShoulderAccessory", Roblox::AssetType::ShoulderAccessory},
        {"FrontAccessory", Roblox::AssetType::FrontAccessory}, {"BackAccessory", Roblox::AssetType::BackAccessory},
        {"WaistAccessory", Roblox::AssetType::WaistAccessory}, {"ClimbAnimation", Roblox::AssetType::ClimbAnimation},
        {"DeathAnimation", Roblox::AssetType::DeathAnimation}, {"FallAnimation", Roblox::AssetType::FallAnimation},
        {"IdleAnimation", Roblox::AssetType::IdleAnimation}, {"JumpAnimation", Roblox::AssetType::JumpAnimation},
        {"RunAnimation", Roblox::AssetType::RunAnimation}, {"SwimAnimation", Roblox::AssetType::SwimAnimation},
        {"WalkAnimation", Roblox::AssetType::WalkAnimation}, {"PoseAnimation", Roblox::AssetType::PoseAnimation},
        {"EarAccessory", Roblox::AssetType::EarAccessory}, {"EyeAccessory", Roblox::AssetType::EyeAccessory},
        {"EmoteAnimation", Roblox::AssetType::EmoteAnimation}, {"Video", Roblox::AssetType::Video},
        {"TShirtAccessory", Roblox::AssetType::TShirtAccessory}, {"ShirtAccessory", Roblox::AssetType::ShirtAccessory},
        {"PantsAccessory", Roblox::AssetType::PantsAccessory}, {"JacketAccessory", Roblox::AssetType::JacketAccessory},
        {"SweaterAccessory", Roblox::AssetType::SweaterAccessory}, {"ShortsAccessory", Roblox::AssetType::ShortsAccessory},
        {"LeftShoeAccessory", Roblox::AssetType::LeftShoeAccessory}, {"RightShoeAccessory", Roblox::AssetType::RightShoeAccessory},
        {"DressSkirtAccessory", Roblox::AssetType::DressSkirtAccessory}, {"FontFamily", Roblox::AssetType::FontFamily},
        {"EyebrowAccessory", Roblox::AssetType::EyebrowAccessory}, {"EyelashAccessory", Roblox::AssetType::EyelashAccessory},
        {"MoodAnimation", Roblox::AssetType::MoodAnimation}, {"DynamicHead", Roblox::AssetType::DynamicHead},
    };
    auto it = map.find(s);
    return it != map.end() ? it->second : Roblox::AssetType::None;
}

// Parses "2013-12-09T23:53:36.957Z" into a Unix timestamp. Returns 0 on failure.
int64_t ParseIso8601(const std::string &s) {
    if (s.empty()) return 0;
    int year, mon, day, hour = 0, min = 0;
    double sec = 0;
    if (std::sscanf(s.c_str(), "%d-%d-%dT%d:%d:%lf", &year, &mon, &day, &hour, &min, &sec) < 3)
        return 0;
    std::tm tm{};
    tm.tm_year = year - 1900;
    tm.tm_mon  = mon - 1;
    tm.tm_mday = day;
    tm.tm_hour = hour;
    tm.tm_min  = min;
    tm.tm_sec  = static_cast<int>(sec);
#if defined(_WIN32)
    time_t t = _mkgmtime(&tm);
#else
    time_t t = timegm(&tm);
#endif
    return t < 0 ? 0 : static_cast<int64_t>(t);
}
} // namespace

AssetEnricher::AssetEnricher(Core *core) :
    mCore(core)
{}

AssetEnricher::~AssetEnricher() {
    Stop();
}

void AssetEnricher::Start() {
    bool expected = false;
    if (!mRunning.compare_exchange_strong(expected, true))
        return; // already running
    mThread = std::thread(&AssetEnricher::WorkerLoop, this);
}

void AssetEnricher::Stop() {
    if (!mRunning.exchange(false))
        return;
    mCv.notify_all();
    if (mThread.joinable())
        mThread.join();
    CloseConnections(); // safe: worker thread has exited
}

void AssetEnricher::Enqueue(const std::string &dbFilePath, int64_t assetId) {
    // Snapshot the auth cookie here, on the caller's (event-loop) thread, so the worker never
    // touches the keychain concurrently.
    std::string cookie;
    if (auto *acc = mCore->GetRbxKeychain()->GetActiveAccount())
        cookie = ".ROBLOSECURITY=" + acc->Token + ";";

    {
        std::lock_guard<std::mutex> lock(mMutex);
        if (!mPending.insert(assetId).second)
            return; // already queued
        mQueue.push_back(Job{dbFilePath, assetId});
        mAuthCookie = cookie;
    }
    mCv.notify_one();
}

void AssetEnricher::WorkerLoop() {
    while (mRunning) {
        std::string dbFilePath;
        std::string cookie;
        std::vector<int64_t> ids;

        {
            std::unique_lock<std::mutex> lock(mMutex);
            mCv.wait(lock, [&] { return !mRunning || !mQueue.empty(); });
            if (!mRunning)
                break;

            // Pull a batch of jobs that share a target database.
            dbFilePath = mQueue.front().DbFilePath;
            cookie = mAuthCookie;
            while (!mQueue.empty() && ids.size() < kMaxBatchSize && mQueue.front().DbFilePath == dbFilePath) {
                ids.push_back(mQueue.front().AssetId);
                mPending.erase(mQueue.front().AssetId);
                mQueue.pop_front();
            }
        }

        if (!ids.empty())
            ProcessBatch(dbFilePath, ids, cookie);

        // Keep develop.roblox.com calls comfortably under its 100/min budget.
        if (mRunning)
            std::this_thread::sleep_for(std::chrono::milliseconds(kInterBatchDelayMs));
    }
}

EmuDb* AssetEnricher::GetConnection(const std::string &dbFilePath) {
    auto it = mConnections.find(dbFilePath);
    if (it != mConnections.end())
        return it->second;

    auto *db = new EmuDb(dbFilePath, true);
    if (db->Fail()) {
        Out("AssetEnricher", "Failed to open enrichment connection to \"{}\"", dbFilePath);
        delete db;
        mConnections[dbFilePath] = nullptr;
        return nullptr;
    }
    // We share the file with the mounted (main-thread) connection; wait out brief write locks
    // instead of failing immediately.
    db->SetPragma("busy_timeout", "5000");
    mConnections[dbFilePath] = db;
    return db;
}

void AssetEnricher::CloseConnections() {
    for (auto &[path, db] : mConnections)
        delete db;
    mConnections.clear();
}

void AssetEnricher::ProcessBatch(const std::string &dbFilePath, const std::vector<int64_t> &ids, const std::string &cookie) {
    EmuDb *db = GetConnection(dbFilePath);
    if (db == nullptr)
        return;

    std::string idList;
    for (size_t i = 0; i < ids.size(); i++) {
        if (i) idList += ",";
        idList += std::to_string(ids[i]);
    }

    NetClient client;

    //////////////// Metadata: develop.roblox.com/v1/assets (batch, needs auth) ////////////////
    if (cookie.empty()) {
        static std::atomic<bool> warned{false};
        if (!warned.exchange(true))
            Out("AssetEnricher", "No logged-in Roblox account; grabbed assets will keep placeholder names (thumbnails still work). Log in to fetch real names/descriptions.");
    } else {
        HttpRequest req;
        req.Url = "https://develop.roblox.com/v1/assets?assetIds=" + idList;
        req.UserAgent = "Roblox/WinINet";
        req.Cookie = cookie;

        HttpResponse meta;
        for (int attempt = 0; attempt < 3; attempt++) {
            meta = client.Fetch(req);
            if (meta.Code == CURLE_OK && meta.HttpStatus == 429) {
                std::this_thread::sleep_for(std::chrono::milliseconds(1000 * (attempt + 1)));
                continue;
            }
            break;
        }

        if (meta.Code == CURLE_OK && meta.HttpStatus == 200) {
            json root = json::parse(meta.Body, nullptr, false);
            if (root.is_discarded() || !root.contains("data") || !root["data"].is_array()) {
                std::string preview(meta.Body.begin(), meta.Body.begin() + std::min<size_t>(meta.Body.size(), 300));
                Out("AssetEnricher", "Unexpected develop /v1/assets response shape: {}", preview);
            } else {
                for (auto &a : root["data"]) {
                    int64_t id = a.contains("id") && a["id"].is_number() ? a["id"].get<int64_t>() : 0;
                    if (id == 0)
                        continue;

                    SqlRow row;
                    if (a.contains("name") && a["name"].is_string())
                        row.push_back({"Name", a["name"].get<std::string>()});
                    if (a.contains("description") && a["description"].is_string())
                        row.push_back({"Description", a["description"].get<std::string>()});
                    if (a.contains("created") && a["created"].is_string()) {
                        int64_t ts = ParseIso8601(a["created"].get<std::string>());
                        if (ts) row.push_back({"Created", ts});
                    }
                    if (a.contains("updated") && a["updated"].is_string()) {
                        int64_t ts = ParseIso8601(a["updated"].get<std::string>());
                        if (ts) row.push_back({"Updated", ts});
                    }
                    if (a.contains("type") && a["type"].is_string()) {
                        Roblox::AssetType t = AssetTypeFromString(a["type"].get<std::string>());
                        if (t != Roblox::AssetType::None)
                            row.push_back({"Type", static_cast<int>(t)});
                    }
                    if (a.contains("creator") && a["creator"].is_object()) {
                        const json &c = a["creator"];
                        int64_t creatorId = c.contains("targetId") && c["targetId"].is_number() ? c["targetId"].get<int64_t>()
                                          : (c.contains("id") && c["id"].is_number() ? c["id"].get<int64_t>() : 0);
                        std::string cType = c.contains("type") && c["type"].is_string() ? c["type"].get<std::string>() : "";
                        if (creatorId != 0)
                            row.push_back({cType == "Group" ? "GroupId" : "UserId", creatorId});
                    }

                    if (!row.empty()) {
                        if (db->UpdateItem(ItemType::Asset, id, row) == SqlDb::Response::Success)
                            db->MarkDirty();
                    }
                }
            }
        } else {
            Out("AssetEnricher", "develop /v1/assets fetch failed (curl={} http={}) for ids {}",
                (int)meta.Code, meta.HttpStatus, idList);
        }
    }

    //////////////// Images: thumbnails.roblox.com/v1/assets (batch, no auth) ////////////////
    HttpRequest thumbReq;
    thumbReq.Url = "https://thumbnails.roblox.com/v1/assets?assetIds=" + idList + "&size=420x420&format=Png&isCircular=false";
    thumbReq.UserAgent = "Roblox/WinINet";
    HttpResponse thumbRes = client.Fetch(thumbReq);
    if (thumbRes.Code != CURLE_OK || thumbRes.HttpStatus != 200)
        return;

    json troot = json::parse(thumbRes.Body, nullptr, false);
    if (troot.is_discarded() || !troot.contains("data") || !troot["data"].is_array())
        return;

    std::vector<int64_t> thumbIds;
    std::vector<HttpRequest> imageReqs;
    for (auto &t : troot["data"]) {
        if (!t.contains("state") || !t["state"].is_string() || t["state"].get<std::string>() != "Completed")
            continue;
        if (!t.contains("imageUrl") || !t["imageUrl"].is_string())
            continue;
        int64_t targetId = t.contains("targetId") && t["targetId"].is_number() ? t["targetId"].get<int64_t>() : 0;
        if (targetId == 0)
            continue;

        HttpRequest ir;
        ir.Url = t["imageUrl"].get<std::string>();
        ir.UserAgent = "Roblox/WinINet";
        thumbIds.push_back(targetId);
        imageReqs.push_back(std::move(ir));
    }

    if (imageReqs.empty())
        return;

    std::vector<HttpResponse> images = client.FetchMany(imageReqs);
    for (size_t i = 0; i < images.size() && i < thumbIds.size(); i++) {
        const HttpResponse &img = images[i];
        if (img.Code != CURLE_OK || img.HttpStatus != 200 || img.Body.empty())
            continue;
        if (db->AttachThumbnailDataToAsset(thumbIds[i], img.Body) == SqlDb::Response::Success)
            db->MarkDirty();
    }
}
