/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: AssetPermissionsHandler.cpp
// Started by: Hattozo
// Started on: 6/7/2026
// Description: (This code was generated by Claude Opus 4.8.)
//              Grants every batch asset-permission request. Reverse-engineered from AudioDiscovery.rbxm:
//              _sendBatchCheckUniversePermission POSTs {requests:[{subject:{subjectType:"Universe",
//              subjectId:<GameId>}, action:"use", assetId:<id>}]} here, and
//              _onBatchCheckUniversePermissionResponse reads responseBody.results[].value.status, only
//              showing a track when status == "HasPermission". So we echo one granted result per request.
#include <NoobWarrior/HttpServer/Emulator/AssetPermissionsHandler.h>
#include <NoobWarrior/HttpServer/Base/HttpServer.h>

#include <nlohmann/json.hpp>

#include <zlib.h>

#include <string>

using namespace NoobWarrior;

// Inflates a gzip-/zlib-wrapped buffer (Studio gzip-compresses POST bodies). Returns false on a partial
// or non-gzip stream so the caller can fall back to the raw bytes.
static bool Inflate(const std::string& in, std::string& out) {
    if (in.empty()) return false;
    z_stream zs{};
    if (inflateInit2(&zs, 15 + 32) != Z_OK) // auto-detect gzip or zlib header
        return false;
    zs.next_in = reinterpret_cast<Bytef*>(const_cast<char*>(in.data()));
    zs.avail_in = static_cast<uInt>(in.size());

    char buf[8192];
    int ret;
    do {
        zs.next_out = reinterpret_cast<Bytef*>(buf);
        zs.avail_out = sizeof(buf);
        ret = inflate(&zs, Z_NO_FLUSH);
        if (ret != Z_OK && ret != Z_STREAM_END && ret != Z_BUF_ERROR) {
            inflateEnd(&zs);
            return false;
        }
        out.append(buf, sizeof(buf) - zs.avail_out);
    } while (ret == Z_OK);

    inflateEnd(&zs);
    return ret == Z_STREAM_END;
}

// Pulls assetId out of a request entry whether it's a string or a number.
static std::string AssetIdOf(const nlohmann::json& r) {
    if (auto it = r.find("assetId"); it != r.end()) {
        if (it->is_string()) return it->get<std::string>();
        if (it->is_number_integer()) return std::to_string(it->get<int64_t>());
    }
    return "";
}

void AssetPermissionsHandler::OnRequest(evhttp_request *req, void *userdata) {
    std::string body;
    if (evbuffer* in = evhttp_request_get_input_buffer(req)) {
        size_t len = evbuffer_get_length(in);
        body.resize(len);
        if (len > 0)
            evbuffer_copyout(in, body.data(), len);
    }
    // Studio gzip-compresses the POST body; inflate when it doesn't already look like JSON.
    if (!body.empty() && body.front() != '{' && body.front() != '[') {
        std::string inflated;
        if (Inflate(body, inflated))
            body = std::move(inflated);
    }

    nlohmann::json reqJson = nlohmann::json::parse(body, nullptr, false);

    // One granted result per requested asset, echoed in order (the plugin pairs results to its pending
    // sound entries). value.status == "HasPermission" is the field the response handler checks.
    nlohmann::json results = nlohmann::json::array();
    if (reqJson.is_object() && reqJson.contains("requests") && reqJson["requests"].is_array()) {
        for (const auto& r : reqJson["requests"]) {
            nlohmann::json value;
            value["assetId"] = AssetIdOf(r);
            value["action"] = r.value("action", std::string("use"));
            value["status"] = "HasPermission";
            if (auto it = r.find("subject"); it != r.end())
                value["subject"] = *it;
            results.push_back(nlohmann::json{{"value", std::move(value)}});
        }
    }

    nlohmann::json j;
    j["results"] = std::move(results);

    const std::string out = j.dump();
    evhttp_add_header(evhttp_request_get_output_headers(req), "Content-Type", "application/json");
    evbuffer* buf = evbuffer_new();
    evbuffer_add(buf, out.data(), out.size());
    evhttp_send_reply(req, HTTP_OK, nullptr, buf);
    evbuffer_free(buf);
}
