/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: AssetPermissionsHandler.cpp
// Started by: Hattozo
// Started on: 6/7/2026
// Description: (Disclaimer: This code was generated by Claude Opus 4.8 / Opus 5.)
#include <NoobWarrior/HttpServer/Emulator/AssetPermissionsHandler.h>
#include <NoobWarrior/HttpServer/Base/HttpServer.h>
#include <NoobWarrior/NoobWarrior.h>

#include <nlohmann/json.hpp>

#include "../../algorithm/gzip.h"

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

using namespace NoobWarrior;

// Asset ids cross the wire as numbers in assetIds[] but as strings elsewhere; normalise to int64 so the
// response can echo them back in the numeric form BatchGrantAssetPermissionsResponseModel expects.
static bool AssetIdValue(const nlohmann::json &v, int64_t &out) {
    if (v.is_number_integer()) {
        out = v.get<int64_t>();
        return true;
    }
    if (v.is_string()) {
        const std::string &s = v.get_ref<const std::string &>();
        try {
            size_t consumed = 0;
            out = std::stoll(s, &consumed);
            return consumed == s.size();
        } catch (...) {
            return false;
        }
    }
    return false;
}

// Pulls assetId out of a request entry whether it's a string or a number.
static std::string AssetIdOf(const nlohmann::json &r) {
    if (auto it = r.find("assetId"); it != r.end()) {
        if (it->is_string()) return it->get<std::string>();
        if (it->is_number_integer()) return std::to_string(it->get<int64_t>());
    }
    return "";
}

// The request URI split at '?', so route dispatch never trips over query parameters.
static void SplitUri(evhttp_request *req, std::string &path, std::string &query) {
    const char *uri = evhttp_request_get_uri(req);
    path = uri ? uri : "";
    if (auto q = path.find('?'); q != std::string::npos) {
        query = path.substr(q + 1);
        path.resize(q);
    }
}

static std::string ReadBody(evhttp_request *req) {
    std::string body;
    if (evbuffer *in = evhttp_request_get_input_buffer(req)) {
        size_t len = evbuffer_get_length(in);
        body.resize(len);
        if (len > 0)
            evbuffer_copyout(in, body.data(), len);
    }
    GunzipIfNeeded(body);
    return body;
}

static const char *MethodName(evhttp_request *req) {
    switch (evhttp_request_get_command(req)) {
    case EVHTTP_REQ_GET:    return "GET";
    case EVHTTP_REQ_POST:   return "POST";
    case EVHTTP_REQ_PUT:    return "PUT";
    case EVHTTP_REQ_PATCH:  return "PATCH";
    case EVHTTP_REQ_DELETE: return "DELETE";
    default:                return "?";
    }
}

// Deliberately unconditional: permission calls are low-volume (throttled engine-side by
// AssetPermissionsUserThrottle) and a wrong-shaped body here is otherwise invisible, surfacing only as an
// unrelated-looking "not authorized" failure several layers up.
static void LogRequest(evhttp_request *req, const std::string &path, const std::string &query,
                       const std::string &body) {
    Out("AssetPermissions", "{} {}{}{} body={}", MethodName(req), path,
        query.empty() ? "" : "?", query,
        body.empty() ? std::string("<empty>") : body);
}

static void SendJson(evhttp_request *req, const nlohmann::json &j) {
    const std::string out = j.dump();
    evhttp_add_header(evhttp_request_get_output_headers(req), "Content-Type", "application/json");
    evbuffer *buf = evbuffer_new();
    evbuffer_add(buf, out.data(), out.size());
    evhttp_send_reply(req, HTTP_OK, nullptr, buf);
    evbuffer_free(buf);
}

// One granted permission record, shaped like the object check-permissions returns inside "value".
static nlohmann::json GrantedPermission(const std::string &assetId, const std::string &action,
                                        const nlohmann::json *subject) {
    nlohmann::json v;
    v["assetId"] = assetId;
    v["action"] = action.empty() ? "Use" : action;
    v["status"] = "HasPermission";
    if (subject != nullptr)
        v["subject"] = *subject;
    return v;
}

// A long-running operation that has already finished. DEPRECATED_PermissionsUtil::pollCrossPublishGrantRequest
// polls operations/{operationId} until done and logs "Operation Status Failed. GRPC Code {}" on failure, so
// report done + Success immediately and it stops polling.
static nlohmann::json DoneOperation(const std::string &id) {
    nlohmann::json op;
    op["path"] = "operations/" + id;
    op["operationId"] = id;
    op["done"] = true;
    op["status"] = "Success";
    op["response"] = nlohmann::json::object();
    return op;
}

void AssetPermissionsHandler::OnRequest(evhttp_request *req, void *userdata) {
    std::string path, query;
    SplitUri(req, path, query);
    const std::string body = ReadBody(req);
    LogRequest(req, path, query, body);

    const nlohmann::json reqJson = nlohmann::json::parse(body, nullptr, false);
    const std::string_view pathView = path;

    // ---- /operations/{operationId} -------------------------------------------------------------------
    if (auto pos = pathView.find("/operations/"); pos != std::string_view::npos) {
        std::string id(pathView.substr(pos + std::string_view("/operations/").size()));
        if (id.empty())
            id = "noobwarrior";
        SendJson(req, DoneOperation(id));
        return;
    }

    // ---- /universes/{universeId}/permissions:copyInto ------------------------------------------------
    // Copies one universe's asset permissions onto another when a place is published or copied. There is
    // nothing to copy here, so it completes immediately.
    if (pathView.find("permissions:copyInto") != std::string_view::npos) {
        SendJson(req, DoneOperation("copy-into"));
        return;
    }

    // ---- /assets/check-permissions (and the RCC alias) -----------------------------------------------
    // Unchanged from the original AudioDiscovery-derived implementation: one granted result per request,
    // echoed in order, because the caller pairs results positionally to its pending entries.
    if (pathView.ends_with("/check-permissions")) {
        nlohmann::json results = nlohmann::json::array();
        if (reqJson.is_object() && reqJson.contains("requests") && reqJson["requests"].is_array()) {
            for (const auto &r : reqJson["requests"]) {
                const nlohmann::json *subject = nullptr;
                if (auto it = r.find("subject"); it != r.end())
                    subject = &(*it);
                results.push_back(nlohmann::json{
                    {"value", GrantedPermission(AssetIdOf(r), r.value("action", std::string("use")), subject)}});
            }
        }
        SendJson(req, nlohmann::json{{"results", std::move(results)}});
        return;
    }

    // ---- /assets/permissions (batch grant) and /assets/{assetId}/permissions -------------------------
    // Collect every asset the caller named. batchGrantAssetPermissions puts them in a flat assetIds[] with
    // the subject/action hoisted to the top level; the per-entry requests[] form carries its own assetId.
    // Accept both, plus an id baked into the path, and report them all as granted.
    std::string pathAssetId;
    if (auto pos = pathView.find("/assets/"); pos != std::string_view::npos) {
        std::string_view rest = pathView.substr(pos + std::string_view("/assets/").size());
        if (rest.ends_with("/permissions"))
            pathAssetId = std::string(rest.substr(0, rest.size() - std::string_view("/permissions").size()));
    }

    std::vector<int64_t> granted;
    if (reqJson.is_object()) {
        if (auto it = reqJson.find("assetIds"); it != reqJson.end() && it->is_array()) {
            for (const auto &v : *it) {
                int64_t id = 0;
                if (AssetIdValue(v, id))
                    granted.push_back(id);
            }
        }
        if (auto it = reqJson.find("requests"); it != reqJson.end() && it->is_array()) {
            for (const auto &r : *it) {
                if (!r.is_object())
                    continue;
                if (auto a = r.find("assetId"); a != r.end()) {
                    int64_t id = 0;
                    if (AssetIdValue(*a, id))
                        granted.push_back(id);
                }
            }
        }
    }
    if (granted.empty() && !pathAssetId.empty()) {
        int64_t id = 0;
        if (AssetIdValue(nlohmann::json(pathAssetId), id))
            granted.push_back(id);
    }

    // BatchGrantAssetPermissionsResponseModel. An empty successAssetIds is still a 200 with no errors --
    // failing here is exactly what produced the "not authorized" message in the first place.
    nlohmann::json j;
    j["successAssetIds"] = granted;
    j["dependenciesGrantResults"] = nlohmann::json::array();
    j["errors"] = nlohmann::json::array();
    SendJson(req, j);
}
