/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: DataStorePersistenceHandler.cpp
// Started by: Hattozo
// Started on: 6/23/2026
// Description: Implements the DataStoreService persistence wire protocol over the EmuDb v17 tables.
//
//   The modern engine (0.574+) talks to gamepersistence.roblox.com:
//     GET    /v2/persistence/{universeId}/datastores/objects/object?datastore=&objectKey=     GetAsync
//     POST   /v2/persistence/{universeId}/datastores/objects/object?datastore=&objectKey=     SetAsync
//     POST   .../objects/object?...&incrementBy=N      (or .../object/increment)              IncrementAsync
//     DELETE /v2/persistence/{universeId}/datastores/objects/object?datastore=&objectKey=     RemoveAsync
//     GET    .../objects/object?...&sortOrder=  (or .../object/versions)                      ListVersionsAsync
//     GET    /v2/persistence/{universeId}/datastores/objects?datastore=&prefix=               ListKeysAsync
//     GET    /v2/persistence/{universeId}/datastores?prefix=                                  ListDataStoresAsync
//   The value is carried in the request/response BODY; version id, created times, user ids and
//   attributes ride in Roblox-Object-* headers and the checksum in Content-MD5 (all verified against
//   the 0.574 RobloxStudioBeta.exe string table).
//
//   Older engines use the legacy form where the query param "key" is the datastore name, "target" is
//   the entry key and "scope" is the scope:
//     POST/GET /persistence/getV2     GetAsync (single via query, or batch via qkeys[] body)
//     POST     /persistence/set       SetAsync (value in body, valueLength query)
//     POST     /persistence/increment IncrementAsync
//     POST     /persistence/remove    RemoveAsync
//     GET      /persistence/getSortedValues   OrderedDataStore:GetSortedAsync
//
//   (Code generated by Claude Opus 4.8)
#include <NoobWarrior/HttpServer/Emulator/DataStorePersistenceHandler.h>
#include <NoobWarrior/HttpServer/Base/HttpServer.h>
#include <NoobWarrior/NoobWarrior.h>

#include "../../algorithm/base64.h"

#include <nlohmann/json.hpp>
#include <openssl/evp.h>
#include <zlib.h>

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <optional>
#include <string>
#include <vector>

using namespace NoobWarrior;
using json = nlohmann::json;

// ============================================================================================
// Small HTTP / encoding helpers
// ============================================================================================

// One decoded query parameter, or "" when absent. evhttp_parse_query url-decodes values, so an
// objectKey of "global%2Ftest_key" comes back as "global/test_key".
static std::string QueryParam(const char *uri, const char *key) {
    std::string out;
    if (uri == nullptr) return out;
    evkeyvalq query;
    if (evhttp_parse_query(uri, &query) == 0) {
        if (const char *val = evhttp_find_header(&query, key))
            out = val;
        evhttp_clear_headers(&query);
    }
    return out;
}

static bool HasQueryParam(const char *uri, const char *key) {
    if (uri == nullptr) return false;
    bool found = false;
    evkeyvalq query;
    if (evhttp_parse_query(uri, &query) == 0) {
        found = evhttp_find_header(&query, key) != nullptr;
        evhttp_clear_headers(&query);
    }
    return found;
}

static std::string RequestHeader(evhttp_request *req, const char *name) {
    const char *v = evhttp_find_header(evhttp_request_get_input_headers(req), name);
    return v ? std::string(v) : std::string();
}

// Inflates gzip/zlib in place (Studio gzip-compresses POST bodies). Auto-detects the wrapper.
static bool Inflate(const std::string &in, std::string &out) {
    if (in.empty()) return false;
    z_stream zs{};
    if (inflateInit2(&zs, 15 + 32) != Z_OK)
        return false;
    zs.next_in = reinterpret_cast<Bytef *>(const_cast<char *>(in.data()));
    zs.avail_in = static_cast<uInt>(in.size());
    char buf[8192];
    int ret;
    do {
        zs.next_out = reinterpret_cast<Bytef *>(buf);
        zs.avail_out = sizeof(buf);
        ret = inflate(&zs, Z_NO_FLUSH);
        if (ret != Z_OK && ret != Z_STREAM_END && ret != Z_BUF_ERROR) {
            inflateEnd(&zs);
            return false;
        }
        out.append(buf, sizeof(buf) - zs.avail_out);
    } while (ret == Z_OK);
    inflateEnd(&zs);
    return ret == Z_STREAM_END;
}

// The full request body, transparently inflated when gzip-encoded.
static std::string ReadBody(evhttp_request *req) {
    std::string body;
    if (evbuffer *in = evhttp_request_get_input_buffer(req)) {
        size_t len = evbuffer_get_length(in);
        body.resize(len);
        if (len > 0)
            evbuffer_copyout(in, body.data(), len);
    }
    if (body.empty()) return body;
    const char *enc = evhttp_find_header(evhttp_request_get_input_headers(req), "Content-Encoding");
    bool looksGzip = body.size() >= 2 && static_cast<unsigned char>(body[0]) == 0x1f &&
                     static_cast<unsigned char>(body[1]) == 0x8b;
    if ((enc && std::strstr(enc, "gzip")) || looksGzip) {
        std::string inflated;
        if (Inflate(body, inflated))
            body = std::move(inflated);
    }
    return body;
}

static int64_t NowMs() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(
               std::chrono::system_clock::now().time_since_epoch())
        .count();
}

// ISO-8601 UTC with a numeric offset and no fractional seconds ("2026-06-23T20:45:38+00:00"). This is
// exactly what PHP date('c') emits, which the engine's DataStoreKeyInfo time parser accepts; the
// fractional ".sssZ" form is rejected by GetAsync (it builds KeyInfo and parses these), surfacing as
// the 504 even though SetAsync — which only reads "version" — tolerated it.
static std::string MsToIso8601(int64_t ms) {
    std::time_t secs = static_cast<std::time_t>(ms / 1000);
    std::tm tmv{};
#if defined(_WIN32)
    gmtime_s(&tmv, &secs);
#else
    gmtime_r(&secs, &tmv);
#endif
    char buf[40];
    std::snprintf(buf, sizeof(buf), "%04d-%02d-%02dT%02d:%02d:%02d+00:00",
                  tmv.tm_year + 1900, tmv.tm_mon + 1, tmv.tm_mday, tmv.tm_hour, tmv.tm_min, tmv.tm_sec);
    return buf;
}

// base64(md5(data)) — the Content-MD5 value the engine validates.
static std::string Md5Base64(const std::string &data) {
    unsigned char digest[EVP_MAX_MD_SIZE];
    unsigned int len = 0;
    if (EVP_Digest(data.data(), data.size(), digest, &len, EVP_md5(), nullptr) != 1)
        return "";
    return base64_encode(digest, len);
}

static const char *ReasonFor(int code) {
    switch (code) {
    case 200: return "OK";
    case 204: return "No Content";
    case 400: return "Bad Request";
    case 403: return "Forbidden";
    case 404: return "Not Found";
    case 409: return "Conflict";
    case 429: return "Too Many Requests";
    case 500: return "Internal Server Error";
    default:  return "OK";
    }
}

static void SendRaw(evhttp_request *req, int code, const std::string &contentType, const std::string &body) {
    if (!contentType.empty())
        evhttp_add_header(evhttp_request_get_output_headers(req), "Content-Type", contentType.c_str());
    evbuffer *buf = evbuffer_new();
    if (!body.empty())
        evbuffer_add(buf, body.data(), body.size());
    evhttp_send_reply(req, code, ReasonFor(code), buf);
    evbuffer_free(buf);
}

static void SendJson(evhttp_request *req, int code, const json &j) {
    SendRaw(req, code, "application/json", j.dump());
}

// The DataStore error envelope. The engine surfaces these as e.g. "DataStoreService: <message>".
static void SendError(evhttp_request *req, int code, const std::string &message) {
    json e;
    e["code"] = code;
    e["message"] = message;
    json j;
    j["errors"] = json::array({e});
    SendRaw(req, code, "application/json", j.dump());
}

// 404 the engine treats as "key not found" -> GetAsync/RemoveAsync return nil instead of throwing.
static void SendKeyNotFound(evhttp_request *req) {
    json e;
    e["code"] = 11;
    e["message"] = "The requested key does not exist.";
    e["retryable"] = false;
    json j;
    j["errors"] = json::array({e});
    SendRaw(req, 404, "application/json", j.dump());
}

// Splits an objectKey ("scope/key") into its scope and key. Scope can't contain '/', keys can, so we
// split on the first slash. A bare value (no slash) is treated as a key in the default "global" scope.
static void SplitObjectKey(const std::string &objectKey, std::string &scope, std::string &key) {
    auto slash = objectKey.find('/');
    if (slash == std::string::npos) {
        scope = "global";
        key = objectKey;
    } else {
        scope = objectKey.substr(0, slash);
        key = objectKey.substr(slash + 1);
    }
    if (scope.empty()) scope = "global";
}

static std::optional<int64_t> ParseInt(const std::string &s) {
    if (s.empty()) return std::nullopt;
    char *end = nullptr;
    long long v = strtoll(s.c_str(), &end, 10);
    if (end == s.c_str() || *end != '\0') return std::nullopt;
    return static_cast<int64_t>(v);
}

// ============================================================================================
// SqlRow column readers
// ============================================================================================

static const SqlValue *FindCol(const SqlRow &row, const char *name) {
    for (const auto &c : row)
        if (c.first == name) return &c.second;
    return nullptr;
}
static int64_t RowI64(const SqlRow &row, const char *name, int64_t def = 0) {
    const SqlValue *v = FindCol(row, name);
    if (!v) return def;
    if (auto p = std::get_if<int64_t>(v)) return *p;
    if (auto p = std::get_if<int>(v)) return *p;
    if (auto p = std::get_if<double>(v)) return static_cast<int64_t>(*p);
    return def;
}
static std::string RowStr(const SqlRow &row, const char *name) {
    const SqlValue *v = FindCol(row, name);
    if (!v) return "";
    if (auto p = std::get_if<std::string>(v)) return *p;
    return "";
}
static bool RowIsNull(const SqlRow &row, const char *name) {
    const SqlValue *v = FindCol(row, name);
    return !v || std::holds_alternative<std::monostate>(*v);
}

// ============================================================================================
// Storage layer (operates on the v17 DataStore* tables of a single EmuDb)
// ============================================================================================

static bool ExecWrite(EmuDb *db, const std::string &sql, std::initializer_list<SqlValue> binds) {
    Statement stmt = db->PrepareStatement(sql);
    if (stmt.Fail()) return false;
    int i = 0;
    for (const auto &b : binds) {
        i++;
        stmt.Bind(i, b);
    }
    return stmt.Step() == SQLITE_DONE;
}

struct EntryInfo {
    int64_t Id = 0;
    std::string CurrentVersionId;
    bool Deleted = false;
    int64_t CreatedTime = 0;
    int64_t UpdatedTime = 0;
};

struct VersionInfo {
    std::string VersionId;
    std::string Value;
    bool ValueNull = true;
    std::string Md5;
    std::string UserIds = "[]";
    std::string Attributes = "{}";
    bool Deleted = false;
    int64_t CreatedTime = 0;
    int64_t ContentLength = 0;
};

struct WriteResult {
    bool Ok = false;
    std::string VersionId;
    int64_t ObjectCreatedTime = 0;
    int64_t VersionCreatedTime = 0;
    std::string Md5;
};

static void EnsureDataStore(EmuDb *db, int64_t universeId, const std::string &name, int type, int64_t nowMs) {
    // INSERT OR IGNORE leans on UNIQUE(UniverseId, Name, Type) to make this idempotent.
    ExecWrite(db, "INSERT OR IGNORE INTO DataStore (UniverseId, Name, Type, CreatedTime) VALUES (?,?,?,?);",
              {SqlValue(universeId), SqlValue(name), SqlValue(type), SqlValue(nowMs)});
}

static std::optional<EntryInfo> FetchEntry(EmuDb *db, int64_t universeId, const std::string &name,
                                           const std::string &scope, const std::string &key, int type) {
    SqlRows rows = db->QueryTyped(
        "SELECT Id, CurrentVersionId, Deleted, CreatedTime, UpdatedTime FROM DataStoreEntry "
        "WHERE UniverseId=? AND DataStoreName=? AND Scope=? AND EntryKey=? AND Type=? LIMIT 1;",
        SqlValue(universeId), SqlValue(name), SqlValue(scope), SqlValue(key), SqlValue(type));
    if (rows.empty()) return std::nullopt;
    const SqlRow &r = rows[0];
    EntryInfo e;
    e.Id = RowI64(r, "Id");
    e.CurrentVersionId = RowStr(r, "CurrentVersionId");
    e.Deleted = RowI64(r, "Deleted") != 0;
    e.CreatedTime = RowI64(r, "CreatedTime");
    e.UpdatedTime = RowI64(r, "UpdatedTime");
    return e;
}

static std::optional<VersionInfo> FetchVersion(EmuDb *db, int64_t entryId, const std::string &versionId) {
    SqlRows rows;
    if (versionId.empty())
        rows = db->QueryTyped(
            "SELECT VersionId, Value, ContentMd5, UserIds, Attributes, Deleted, CreatedTime, ContentLength "
            "FROM DataStoreVersion WHERE EntryId=? ORDER BY Id DESC LIMIT 1;",
            SqlValue(entryId));
    else
        rows = db->QueryTyped(
            "SELECT VersionId, Value, ContentMd5, UserIds, Attributes, Deleted, CreatedTime, ContentLength "
            "FROM DataStoreVersion WHERE EntryId=? AND VersionId=? LIMIT 1;",
            SqlValue(entryId), SqlValue(versionId));
    if (rows.empty()) return std::nullopt;
    const SqlRow &r = rows[0];
    VersionInfo v;
    v.VersionId = RowStr(r, "VersionId");
    v.ValueNull = RowIsNull(r, "Value");
    v.Value = RowStr(r, "Value");
    v.Md5 = RowStr(r, "ContentMd5");
    v.UserIds = RowStr(r, "UserIds");
    if (v.UserIds.empty()) v.UserIds = "[]";
    v.Attributes = RowStr(r, "Attributes");
    if (v.Attributes.empty()) v.Attributes = "{}";
    v.Deleted = RowI64(r, "Deleted") != 0;
    v.CreatedTime = RowI64(r, "CreatedTime");
    v.ContentLength = RowI64(r, "ContentLength");
    return v;
}

// Roblox version-id GUID format: "08<14 hex>.<10-digit seq>.08<14 hex>.01". The engine PARSES this for
// DataStoreKeyInfo.Version and rejects a plain hex string with "Unexpected Version number format" (which
// surfaces as the 504 on GetAsync). The hex parts encode the FILETIME so ids stay chronological; the
// 10-digit middle is a per-key sequence for uniqueness.
static std::string MakeVersionId(int64_t ms, int64_t seq) {
    uint64_t ft = static_cast<uint64_t>(ms) * 10000ULL + 116444736000000000ULL;
    uint64_t lo = ft & 0x00FFFFFFFFFFFFFFULL; // low 56 bits -> 14 hex chars
    char b[80];
    std::snprintf(b, sizeof(b), "08%014llX.%010lld.08%014llX.01",
                  static_cast<unsigned long long>(lo), static_cast<long long>(seq % 10000000000LL),
                  static_cast<unsigned long long>(lo));
    return b;
}

static int64_t CountVersions(EmuDb *db, int64_t entryId) {
    SqlRows rows = db->QueryTyped("SELECT COUNT(*) AS C FROM DataStoreVersion WHERE EntryId=?;", SqlValue(entryId));
    return rows.empty() ? 0 : RowI64(rows[0], "C");
}

// Writes a new value (or, with deleted=true, a tombstone) as a fresh immutable version and repoints the
// entry at it. Creates the datastore and entry rows on first use. Returns the new version's metadata.
static WriteResult WriteVersion(EmuDb *db, int64_t universeId, const std::string &name, const std::string &scope,
                                const std::string &key, int type, const std::optional<std::string> &value,
                                const std::string &userIds, const std::string &attributes, bool deleted,
                                int64_t nowMs) {
    WriteResult res;
    EnsureDataStore(db, universeId, name, type, nowMs);

    std::optional<EntryInfo> existing = FetchEntry(db, universeId, name, scope, key, type);
    int64_t entryId;
    int64_t objectCreated;
    if (existing) {
        entryId = existing->Id;
        objectCreated = existing->CreatedTime ? existing->CreatedTime : nowMs;
    } else {
        if (!ExecWrite(db,
                "INSERT INTO DataStoreEntry (UniverseId, DataStoreName, Scope, EntryKey, Type, CreatedTime, UpdatedTime) "
                "VALUES (?,?,?,?,?,?,?);",
                {SqlValue(universeId), SqlValue(name), SqlValue(scope), SqlValue(key), SqlValue(type),
                 SqlValue(nowMs), SqlValue(nowMs)}))
            return res;
        entryId = sqlite3_last_insert_rowid(db->Get());
        objectCreated = nowMs;
    }

    int64_t seq = CountVersions(db, entryId);
    std::string versionId = MakeVersionId(nowMs, seq);
    std::string md5 = value ? Md5Base64(*value) : "";
    int64_t contentLength = value ? static_cast<int64_t>(value->size()) : 0;

    if (!ExecWrite(db,
            "INSERT INTO DataStoreVersion (EntryId, VersionId, Value, ContentLength, ContentMd5, UserIds, Attributes, Deleted, CreatedTime) "
            "VALUES (?,?,?,?,?,?,?,?,?);",
            {SqlValue(entryId), SqlValue(versionId), value ? SqlValue(*value) : SqlValue(),
             SqlValue(contentLength), SqlValue(md5), SqlValue(userIds), SqlValue(attributes),
             SqlValue(deleted ? 1 : 0), SqlValue(nowMs)}))
        return res;

    std::optional<int64_t> sortVal = (value && !deleted) ? ParseInt(*value) : std::nullopt;
    if (sortVal)
        ExecWrite(db, "UPDATE DataStoreEntry SET CurrentVersionId=?, UpdatedTime=?, Deleted=?, SortValue=? WHERE Id=?;",
                  {SqlValue(versionId), SqlValue(nowMs), SqlValue(deleted ? 1 : 0), SqlValue(*sortVal), SqlValue(entryId)});
    else
        ExecWrite(db, "UPDATE DataStoreEntry SET CurrentVersionId=?, UpdatedTime=?, Deleted=?, SortValue=NULL WHERE Id=?;",
                  {SqlValue(versionId), SqlValue(nowMs), SqlValue(deleted ? 1 : 0), SqlValue(entryId)});

    db->MarkDirty();
    res.Ok = true;
    res.VersionId = versionId;
    res.ObjectCreatedTime = objectCreated;
    res.VersionCreatedTime = nowMs;
    res.Md5 = md5;
    return res;
}

// Stamps the v2 metadata headers onto a response.
static void AddObjectHeaders(evhttp_request *req, const std::string &versionId, int64_t objectCreatedMs,
                             int64_t versionCreatedMs, const std::string &userIds, const std::string &attributes,
                             const std::string &md5) {
    evkeyvalq *out = evhttp_request_get_output_headers(req);
    if (!versionId.empty()) {
        evhttp_add_header(out, "Roblox-Object-Version-Id", versionId.c_str());
        // The engine also reads the version as the ETag; SYNTAX sets both and omitting it is a candidate
        // cause of the GetAsync 504.
        std::string etag = "\"" + versionId + "\"";
        evhttp_add_header(out, "ETag", etag.c_str());
    }
    evhttp_add_header(out, "Roblox-Object-Created-Time", MsToIso8601(objectCreatedMs).c_str());
    evhttp_add_header(out, "Roblox-Object-Version-Created-Time", MsToIso8601(versionCreatedMs).c_str());
    if (!userIds.empty())
        evhttp_add_header(out, "Roblox-Object-Userids", userIds.c_str());
    if (!attributes.empty())
        evhttp_add_header(out, "Roblox-Object-Attributes", attributes.c_str());
    if (!md5.empty())
        evhttp_add_header(out, "Content-MD5", md5.c_str());
}

// ============================================================================================
// Handler
// ============================================================================================

DataStorePersistenceHandler::DataStorePersistenceHandler(HttpServer *srv, EmuDbManager *dbm)
    : mHttpServer(srv), mEmuDbManager(dbm) {}

EmuDb *DataStorePersistenceHandler::SelectDb(int64_t universeId) {
    EmuDb *db = mEmuDbManager->GetFirstDbWhereItemExists(ItemType::Universe, universeId);
    if (db == nullptr)
        db = mEmuDbManager->GetMasterDatabase();
    return db;
}

int64_t DataStorePersistenceHandler::ResolveUniverseFromHeaders(evhttp_request *req) {
    if (auto u = ParseInt(RequestHeader(req, "Roblox-Universe-Id")))
        return *u;
    if (auto p = ParseInt(RequestHeader(req, "Roblox-Place-Id")))
        if (auto u = mEmuDbManager->GetUniverseIdForPlace(*p))
            return *u;
    return 0; // shared local universe
}

void DataStorePersistenceHandler::OnRequest(evhttp_request *req, void *userdata) {
    const char *uri = evhttp_request_get_uri(req);
    std::string path = uri ? uri : "";
    if (auto q = path.find('?'); q != std::string::npos)
        path.resize(q);
    std::string lpath = path;
    std::transform(lpath.begin(), lpath.end(), lpath.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // ---- Legacy /persistence/* family ----
    if (lpath.find("/persistence/") != std::string::npos && lpath.find("/v2/persistence/") == std::string::npos) {
        if (lpath.find("getsortedvalues") != std::string::npos || lpath.find("sorted/list") != std::string::npos)
            HandleLegacySorted(req);
        else if (lpath.find("/increment") != std::string::npos)
            HandleLegacyIncrement(req);
        else if (lpath.find("/remove") != std::string::npos)
            HandleLegacyRemove(req);
        else if (lpath.find("/set") != std::string::npos)
            HandleLegacySet(req);
        else
            HandleLegacyGet(req); // getV2 + bare reads
        return;
    }

    // ---- Modern /v2/persistence/:universeId/... family ----
    int64_t universeId = 0;
    if (auto u = ParseInt(mHttpServer->GetRouteParam("universeId")))
        universeId = *u;

    auto endsWith = [&](const char *s) {
        size_t n = std::strlen(s);
        return lpath.size() >= n && lpath.compare(lpath.size() - n, n, s) == 0;
    };
    evhttp_cmd_type method = evhttp_request_get_command(req);

    if (endsWith("/object/versions/version")) {
        HandleV2Object(req, universeId, 0); // get/remove a specific version (read via the version query)
    } else if (endsWith("/object/versions")) {
        HandleV2ListVersions(req, universeId);
    } else if (endsWith("/object/increment")) {
        HandleV2Increment(req, universeId);
    } else if (endsWith("/objects/object")) {
        if (method == EVHTTP_REQ_POST && HasQueryParam(uri, "incrementBy"))
            HandleV2Increment(req, universeId);
        else if (method == EVHTTP_REQ_GET && HasQueryParam(uri, "sortOrder"))
            HandleV2ListVersions(req, universeId);
        else
            HandleV2Object(req, universeId, 0);
    } else if (endsWith("/objects")) {
        HandleV2ListObjects(req, universeId);
    } else if (endsWith("/datastores")) {
        if (HasQueryParam(uri, "datastore"))
            HandleV2ListObjects(req, universeId); // list keys within a named datastore
        else
            HandleV2ListDataStores(req, universeId);
    } else {
        HandleV2Object(req, universeId, 0);
    }
}

// GET = GetAsync (latest or a specific version), POST = SetAsync, DELETE = RemoveAsync.
void DataStorePersistenceHandler::HandleV2Object(evhttp_request *req, int64_t universeId, int dataStoreType) {
    const char *uri = evhttp_request_get_uri(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }

    std::string datastore = QueryParam(uri, "datastore");
    std::string objectKey = QueryParam(uri, "objectKey");
    if (datastore.empty() || objectKey.empty()) {
        SendError(req, 400, "datastore and objectKey are required");
        return;
    }
    std::string scope, key;
    SplitObjectKey(objectKey, scope, key);

    evhttp_cmd_type method = evhttp_request_get_command(req);

    if (method == EVHTTP_REQ_GET) {
        std::string wantVersion = QueryParam(uri, "version");
        if (wantVersion.empty()) wantVersion = QueryParam(uri, "versionId");

        std::optional<EntryInfo> entry = FetchEntry(db, universeId, datastore, scope, key, dataStoreType);
        if (!entry) {
            SendKeyNotFound(req); // GetAsync -> nil
            return;
        }
        std::optional<VersionInfo> ver = FetchVersion(db, entry->Id, wantVersion);
        if (!ver || (ver->Deleted && wantVersion.empty()) || ver->ValueNull) {
            SendKeyNotFound(req);
            return;
        }
        std::string md5 = ver->Md5.empty() ? Md5Base64(ver->Value) : ver->Md5;
        AddObjectHeaders(req, ver->VersionId, entry->CreatedTime, ver->CreatedTime, ver->UserIds, ver->Attributes, md5);
        // GetAsync wants the raw value as the body (octet-stream); metadata rides in the headers above.
        // Sending application/json makes the engine parse the body as an envelope and 504.
        SendRaw(req, 200, "application/octet-stream", ver->Value);
        return;
    }

    if (method == EVHTTP_REQ_POST) {
        std::string value = ReadBody(req);
        std::string userIds = RequestHeader(req, "Roblox-Object-Userids");
        if (userIds.empty()) userIds = "[]";
        std::string attributes = RequestHeader(req, "Roblox-Object-Attributes");
        if (attributes.empty()) attributes = "{}";

        WriteResult w = WriteVersion(db, universeId, datastore, scope, key, dataStoreType, value, userIds,
                                     attributes, false, NowMs());
        if (!w.Ok) {
            SendError(req, 500, "An internal server error occurred");
            return;
        }
        AddObjectHeaders(req, w.VersionId, w.ObjectCreatedTime, w.VersionCreatedTime, userIds, attributes, w.Md5);
        // SetAsync expects the metadata envelope in the body (NOT the value echoed) — the engine reads
        // the new version from here and rejects anything else with "504: response not formatted correctly".
        json meta;
        meta["version"] = w.VersionId;
        meta["deleted"] = false;
        meta["contentLength"] = static_cast<int64_t>(value.size());
        meta["createdTime"] = MsToIso8601(w.VersionCreatedTime);
        meta["objectCreatedTime"] = MsToIso8601(w.ObjectCreatedTime);
        SendJson(req, 200, meta);
        return;
    }

    if (method == EVHTTP_REQ_DELETE) {
        std::optional<EntryInfo> entry = FetchEntry(db, universeId, datastore, scope, key, dataStoreType);
        std::string oldValue;
        bool hadValue = false;
        if (entry) {
            if (std::optional<VersionInfo> ver = FetchVersion(db, entry->Id, "")) {
                if (!ver->Deleted && !ver->ValueNull) {
                    oldValue = ver->Value;
                    hadValue = true;
                }
            }
        }
        // RemoveAsync writes a tombstone version so history (and GetVersionAsync) still works.
        WriteResult w = WriteVersion(db, universeId, datastore, scope, key, dataStoreType, std::nullopt, "[]",
                                     "{}", true, NowMs());
        if (hadValue) {
            AddObjectHeaders(req, w.VersionId, w.ObjectCreatedTime, w.VersionCreatedTime, "[]", "{}", Md5Base64(oldValue));
            SendRaw(req, 200, "application/octet-stream", oldValue);
        } else {
            SendKeyNotFound(req);
        }
        return;
    }

    SendError(req, 400, "Unsupported method");
}

void DataStorePersistenceHandler::HandleV2Increment(evhttp_request *req, int64_t universeId) {
    const char *uri = evhttp_request_get_uri(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }
    std::string datastore = QueryParam(uri, "datastore");
    std::string objectKey = QueryParam(uri, "objectKey");
    if (datastore.empty() || objectKey.empty()) {
        SendError(req, 400, "datastore and objectKey are required");
        return;
    }
    std::string scope, key;
    SplitObjectKey(objectKey, scope, key);

    int64_t delta = 1;
    if (auto d = ParseInt(QueryParam(uri, "incrementBy")))
        delta = *d;

    int64_t current = 0;
    if (std::optional<EntryInfo> entry = FetchEntry(db, universeId, datastore, scope, key, 0))
        if (std::optional<VersionInfo> ver = FetchVersion(db, entry->Id, ""))
            if (!ver->Deleted)
                if (auto cur = ParseInt(ver->Value))
                    current = *cur;

    int64_t next = current + delta;
    std::string value = std::to_string(next);
    std::string userIds = RequestHeader(req, "Roblox-Object-Userids");
    if (userIds.empty()) userIds = "[]";
    std::string attributes = RequestHeader(req, "Roblox-Object-Attributes");
    if (attributes.empty()) attributes = "{}";

    WriteResult w = WriteVersion(db, universeId, datastore, scope, key, 0, value, userIds, attributes, false, NowMs());
    if (!w.Ok) {
        SendError(req, 500, "An internal server error occurred");
        return;
    }
    AddObjectHeaders(req, w.VersionId, w.ObjectCreatedTime, w.VersionCreatedTime, userIds, attributes, w.Md5);
    // IncrementAsync reads the new numeric value from the raw body (octet-stream), like GetAsync.
    SendRaw(req, 200, "application/octet-stream", value);
}

void DataStorePersistenceHandler::HandleV2ListVersions(evhttp_request *req, int64_t universeId) {
    const char *uri = evhttp_request_get_uri(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }
    std::string datastore = QueryParam(uri, "datastore");
    std::string objectKey = QueryParam(uri, "objectKey");
    std::string scope, key;
    SplitObjectKey(objectKey, scope, key);

    std::string sortOrder = QueryParam(uri, "sortOrder");
    bool ascending = !sortOrder.empty() && (sortOrder[0] == 'A' || sortOrder[0] == 'a');

    json versions = json::array();
    std::optional<EntryInfo> entry = FetchEntry(db, universeId, datastore, scope, key, 0);
    if (entry) {
        SqlRows rows = db->QueryTyped(
            std::string("SELECT VersionId, Deleted, CreatedTime, ContentLength FROM DataStoreVersion WHERE EntryId=? ORDER BY Id ") +
                (ascending ? "ASC" : "DESC") + " LIMIT 200;",
            SqlValue(entry->Id));
        for (const SqlRow &r : rows) {
            json v;
            v["version"] = RowStr(r, "VersionId");
            v["deleted"] = RowI64(r, "Deleted") != 0;
            v["contentLength"] = RowI64(r, "ContentLength");
            v["createdTime"] = MsToIso8601(RowI64(r, "CreatedTime"));
            v["objectCreatedTime"] = MsToIso8601(entry->CreatedTime);
            versions.push_back(std::move(v));
        }
    }
    json j;
    j["versions"] = std::move(versions);
    j["lastReturnedKey"] = "";
    SendJson(req, 200, j);
}

void DataStorePersistenceHandler::HandleV2ListObjects(evhttp_request *req, int64_t universeId) {
    const char *uri = evhttp_request_get_uri(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }
    std::string datastore = QueryParam(uri, "datastore");
    std::string prefix = QueryParam(uri, "prefix");
    std::string scope = QueryParam(uri, "scope");
    if (scope.empty()) scope = "global";
    bool allScopes = QueryParam(uri, "allScopes") == "true" || QueryParam(uri, "AllScopes") == "true";
    int limit = 50;
    if (auto m = ParseInt(QueryParam(uri, "maxItemsToReturn")))
        limit = std::clamp(static_cast<int>(*m), 1, 500);

    json keys = json::array();
    SqlRows rows;
    if (allScopes)
        rows = db->QueryTyped(
            "SELECT EntryKey, Scope FROM DataStoreEntry WHERE UniverseId=? AND DataStoreName=? AND Deleted=0 ORDER BY EntryKey ASC;",
            SqlValue(universeId), SqlValue(datastore));
    else
        rows = db->QueryTyped(
            "SELECT EntryKey, Scope FROM DataStoreEntry WHERE UniverseId=? AND DataStoreName=? AND Scope=? AND Deleted=0 ORDER BY EntryKey ASC;",
            SqlValue(universeId), SqlValue(datastore), SqlValue(scope));
    for (const SqlRow &r : rows) {
        std::string k = RowStr(r, "EntryKey");
        if (!prefix.empty() && k.rfind(prefix, 0) != 0)
            continue;
        keys.push_back(k); // ListKeysAsync expects a flat array of key strings
        if (static_cast<int>(keys.size()) >= limit)
            break;
    }
    json j;
    j["keys"] = std::move(keys);
    j["lastReturnedKey"] = "";
    SendJson(req, 200, j);
}

void DataStorePersistenceHandler::HandleV2ListDataStores(evhttp_request *req, int64_t universeId) {
    const char *uri = evhttp_request_get_uri(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }
    std::string prefix = QueryParam(uri, "prefix");
    int limit = 50;
    if (auto m = ParseInt(QueryParam(uri, "maxItemsToReturn")))
        limit = std::clamp(static_cast<int>(*m), 1, 500);

    json datastores = json::array();
    SqlRows rows = db->QueryTyped(
        "SELECT Name, CreatedTime FROM DataStore WHERE UniverseId=? AND Type=0 ORDER BY Name ASC;",
        SqlValue(universeId));
    for (const SqlRow &r : rows) {
        std::string name = RowStr(r, "Name");
        if (!prefix.empty() && name.rfind(prefix, 0) != 0)
            continue;
        json d;
        d["name"] = name;
        d["createdTime"] = RowI64(r, "CreatedTime");
        datastores.push_back(std::move(d));
        if (static_cast<int>(datastores.size()) >= limit)
            break;
    }
    json j;
    j["datastores"] = std::move(datastores);
    j["nextPageCursor"] = nullptr;
    SendJson(req, 200, j);
}

// ============================================================================================
// Legacy /persistence/* (key=datastore, target=entry key, scope=scope)
// ============================================================================================

// Builds one legacy result object: {"Key":{"Scope":..,"Target":..,"Key":..},"Value":"<json text>"}.
static json LegacyEntryJson(const std::string &scope, const std::string &target, const std::string &datastore,
                            const std::string &value) {
    json k;
    k["Scope"] = scope;
    k["Target"] = target;
    k["Key"] = datastore;
    json e;
    e["Key"] = std::move(k);
    e["Value"] = value; // nlohmann emits the stored JSON text as a JSON string, matching Roblox
    return e;
}

void DataStorePersistenceHandler::HandleLegacyGet(evhttp_request *req) {
    const char *uri = evhttp_request_get_uri(req);
    int64_t universeId = ResolveUniverseFromHeaders(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }

    json data = json::array();

    // Batch form: qkeys[i].scope / qkeys[i].target / qkeys[i].key in the POST body.
    std::string body = ReadBody(req);
    bool didBatch = false;
    if (!body.empty() && body.find("qkeys") != std::string::npos) {
        evkeyvalq form;
        if (evhttp_parse_query_str(body.c_str(), &form) == 0) {
            for (int i = 0;; i++) {
                std::string base = "qkeys[" + std::to_string(i) + "].";
                const char *ds = evhttp_find_header(&form, (base + "key").c_str());
                if (!ds) break;
                const char *tg = evhttp_find_header(&form, (base + "target").c_str());
                const char *sc = evhttp_find_header(&form, (base + "scope").c_str());
                std::string datastore = ds;
                std::string target = tg ? tg : "";
                std::string scope = (sc && *sc) ? sc : "global";
                if (auto entry = FetchEntry(db, universeId, datastore, scope, target, 0))
                    if (auto ver = FetchVersion(db, entry->Id, ""))
                        if (!ver->Deleted && !ver->ValueNull)
                            data.push_back(LegacyEntryJson(scope, target, datastore, ver->Value));
                didBatch = true;
            }
            evhttp_clear_headers(&form);
        }
    }

    // Single form: ?key=<datastore>&scope=<scope>&target=<key>
    if (!didBatch) {
        std::string datastore = QueryParam(uri, "key");
        std::string target = QueryParam(uri, "target");
        std::string scope = QueryParam(uri, "scope");
        if (scope.empty()) scope = "global";
        if (!datastore.empty()) {
            if (auto entry = FetchEntry(db, universeId, datastore, scope, target, 0))
                if (auto ver = FetchVersion(db, entry->Id, ""))
                    if (!ver->Deleted && !ver->ValueNull)
                        data.push_back(LegacyEntryJson(scope, target, datastore, ver->Value));
        }
    }

    json j;
    j["data"] = std::move(data);
    SendJson(req, 200, j);
}

void DataStorePersistenceHandler::HandleLegacySet(evhttp_request *req) {
    const char *uri = evhttp_request_get_uri(req);
    int64_t universeId = ResolveUniverseFromHeaders(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }
    std::string datastore = QueryParam(uri, "key");
    std::string target = QueryParam(uri, "target");
    std::string scope = QueryParam(uri, "scope");
    if (scope.empty()) scope = "global";
    if (datastore.empty()) {
        SendError(req, 400, "key is required");
        return;
    }
    // The legacy set carries the value either in the body or a value query param.
    std::string value = ReadBody(req);
    if (value.empty())
        value = QueryParam(uri, "value");

    WriteResult w = WriteVersion(db, universeId, datastore, scope, target, 0, value, "[]", "{}", false, NowMs());
    if (!w.Ok) {
        SendError(req, 500, "An internal server error occurred");
        return;
    }
    json j;
    j["data"] = json::array({LegacyEntryJson(scope, target, datastore, value)});
    SendJson(req, 200, j);
}

void DataStorePersistenceHandler::HandleLegacyIncrement(evhttp_request *req) {
    const char *uri = evhttp_request_get_uri(req);
    int64_t universeId = ResolveUniverseFromHeaders(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }
    std::string datastore = QueryParam(uri, "key");
    std::string target = QueryParam(uri, "target");
    std::string scope = QueryParam(uri, "scope");
    if (scope.empty()) scope = "global";
    int64_t delta = 0;
    if (auto d = ParseInt(QueryParam(uri, "by")))
        delta = *d;

    int64_t current = 0;
    if (auto entry = FetchEntry(db, universeId, datastore, scope, target, 0))
        if (auto ver = FetchVersion(db, entry->Id, ""))
            if (!ver->Deleted)
                if (auto cur = ParseInt(ver->Value))
                    current = *cur;

    int64_t next = current + delta;
    std::string value = std::to_string(next);
    WriteResult w = WriteVersion(db, universeId, datastore, scope, target, 0, value, "[]", "{}", false, NowMs());
    if (!w.Ok) {
        SendError(req, 500, "An internal server error occurred");
        return;
    }
    json j;
    j["data"] = json::array({LegacyEntryJson(scope, target, datastore, value)});
    SendJson(req, 200, j);
}

void DataStorePersistenceHandler::HandleLegacyRemove(evhttp_request *req) {
    const char *uri = evhttp_request_get_uri(req);
    int64_t universeId = ResolveUniverseFromHeaders(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }
    std::string datastore = QueryParam(uri, "key");
    std::string target = QueryParam(uri, "target");
    std::string scope = QueryParam(uri, "scope");
    if (scope.empty()) scope = "global";

    json data = json::array();
    if (auto entry = FetchEntry(db, universeId, datastore, scope, target, 0)) {
        if (auto ver = FetchVersion(db, entry->Id, ""))
            if (!ver->Deleted && !ver->ValueNull)
                data.push_back(LegacyEntryJson(scope, target, datastore, ver->Value));
        WriteVersion(db, universeId, datastore, scope, target, 0, std::nullopt, "[]", "{}", true, NowMs());
    }
    json j;
    j["data"] = std::move(data);
    SendJson(req, 200, j);
}

void DataStorePersistenceHandler::HandleLegacySorted(evhttp_request *req) {
    const char *uri = evhttp_request_get_uri(req);
    int64_t universeId = ResolveUniverseFromHeaders(req);
    EmuDb *db = SelectDb(universeId);
    if (db == nullptr) {
        SendError(req, 500, "No database available");
        return;
    }
    std::string datastore = QueryParam(uri, "key");
    std::string scope = QueryParam(uri, "scope");
    if (scope.empty()) scope = "global";
    std::string direction = QueryParam(uri, "direction");
    bool ascending = direction.empty() || direction[0] == 'a' || direction[0] == 'A';
    int pageSize = 50;
    if (auto p = ParseInt(QueryParam(uri, "pageSize")))
        pageSize = std::clamp(static_cast<int>(*p), 1, 100);
    std::optional<int64_t> minValue = ParseInt(QueryParam(uri, "minValue"));
    std::optional<int64_t> maxValue = ParseInt(QueryParam(uri, "maxValue"));

    // OrderedDataStore ranks keys by their numeric SortValue. Entries are written through the same
    // tables; ordered ones simply have a non-null SortValue.
    std::string sql =
        "SELECT EntryKey, SortValue FROM DataStoreEntry "
        "WHERE UniverseId=? AND DataStoreName=? AND Scope=? AND Deleted=0 AND SortValue IS NOT NULL";
    if (minValue) sql += " AND SortValue >= " + std::to_string(*minValue);
    if (maxValue) sql += " AND SortValue <= " + std::to_string(*maxValue);
    sql += ascending ? " ORDER BY SortValue ASC" : " ORDER BY SortValue DESC";
    sql += " LIMIT " + std::to_string(pageSize) + ";";

    SqlRows rows = db->QueryTyped(sql, SqlValue(universeId), SqlValue(datastore), SqlValue(scope));
    json entries = json::array();
    for (const SqlRow &r : rows) {
        json e;
        e["Target"] = RowStr(r, "EntryKey");
        e["Value"] = RowI64(r, "SortValue");
        entries.push_back(std::move(e));
    }
    json inner;
    inner["Entries"] = std::move(entries);
    inner["ExclusiveStartKey"] = nullptr;
    json j;
    j["data"] = std::move(inner);
    SendJson(req, 200, j);
}
