/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: DevelopHandler.cpp
// Started by: Hattozo
// Started on: 6/22/2026
// Description: develop.roblox.com endpoints behind the modern Studio (0.574) home/Create page.
//              /v1/search/universes lists the games stored in the mounted databases (this is what
//              fills the "My Games" / home grid). /v1/gametemplates and /v1/user/groups/canmanage
//              return valid-but-empty bodies (no local templates or groups). /v1/user/:userId/
//              canmanage/:placeId grants edit rights so a tile can be opened, and
//              /v1/universes/multiget/teamcreate reports Team Create inactive per universe so the grid
//              stops retrying. Response shapes mirror real Roblox + the reference webservers.
//              (Code generated by Claude Opus 4.8)
#include <NoobWarrior/HttpServer/Emulator/DevelopHandler.h>
#include <NoobWarrior/HttpServer/Base/HttpServer.h>
#include <NoobWarrior/NoobWarrior.h>
#include <NoobWarrior/Registry.h>
#include <NoobWarrior/Roblox/Api/Universe.h>

#include <nlohmann/json.hpp>

#include <cstdlib>
#include <ctime>
#include <format>
#include <string>
#include <vector>

using namespace NoobWarrior;

// Returns a single (decoded) query parameter, or "" when absent.
static std::string GetQueryParam(const char* uri, const char* key) {
    std::string out;
    if (uri == nullptr) return out;
    evkeyvalq query;
    if (evhttp_parse_query(uri, &query) == 0) {
        if (const char* val = evhttp_find_header(&query, key))
            out = val;
        evhttp_clear_headers(&query);
    }
    return out;
}

// Collects every value for a query key, handling BOTH the repeated form (ids=1&ids=2) and the
// comma-separated form (ids=1,2,3). Studio uses both. Parses the raw query so repeated keys aren't
// collapsed (evhttp_find_header only returns the first). Non-numeric tokens are skipped.
static std::vector<int64_t> CollectIds(const char* uri, const char* key) {
    std::vector<int64_t> ids;
    if (uri == nullptr) return ids;
    std::string u = uri;
    auto q = u.find('?');
    if (q == std::string::npos) return ids;
    std::string query = u.substr(q + 1);

    const std::string keyEq = std::string(key) + "=";
    size_t pos = 0;
    while (pos < query.size()) {
        size_t amp = query.find('&', pos);
        std::string pair = query.substr(pos, amp == std::string::npos ? std::string::npos : amp - pos);
        if (pair.rfind(keyEq, 0) == 0) {
            std::string vals = pair.substr(keyEq.size());
            size_t start = 0;
            while (start <= vals.size()) {
                size_t comma = vals.find(',', start);
                std::string tok = vals.substr(start, comma == std::string::npos ? std::string::npos : comma - start);
                char* endPtr = nullptr;
                int64_t v = strtoll(tok.c_str(), &endPtr, 10);
                if (!tok.empty() && endPtr && *endPtr == '\0')
                    ids.push_back(v);
                if (comma == std::string::npos) break;
                start = comma + 1;
            }
        }
        if (amp == std::string::npos) break;
        pos = amp + 1;
    }
    return ids;
}

// ISO-8601 UTC timestamp ("YYYY-MM-DDTHH:MM:SS.000Z"), matching what develop.roblox.com emits.
// Unset (<=0) times fall back to 2015-01-01 so the grid never shows a 1970 date.
static std::string UnixToIso8601(int64_t t) {
    std::time_t tt = t > 0 ? static_cast<std::time_t>(t) : static_cast<std::time_t>(1420070400);
    std::tm tmv{};
#if defined(_WIN32)
    gmtime_s(&tmv, &tt);
#else
    gmtime_r(&tt, &tmv);
#endif
    return std::format("{:04}-{:02}-{:02}T{:02}:{:02}:{:02}.000Z",
        tmv.tm_year + 1900, tmv.tm_mon + 1, tmv.tm_mday, tmv.tm_hour, tmv.tm_min, tmv.tm_sec);
}

static void SendJson(evhttp_request* req, const nlohmann::json& j) {
    const std::string body = j.dump();
    evhttp_add_header(evhttp_request_get_output_headers(req), "Content-Type", "application/json");
    evbuffer* buf = evbuffer_new();
    evbuffer_add(buf, body.data(), body.size());
    evhttp_send_reply(req, HTTP_OK, nullptr, buf);
    evbuffer_free(buf);
}

DevelopHandler::DevelopHandler(HttpServer *srv, EmuDbManager *dbm)
    : mHttpServer(srv), mEmuDbManager(dbm) {}

void DevelopHandler::OnRequest(evhttp_request *req, void *userdata) {
    const char* uri = evhttp_request_get_uri(req);
    std::string path = uri ? uri : "";
    if (auto q = path.find('?'); q != std::string::npos)
        path.resize(q);
    for (char &c : path)
        c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));

    if (path.find("search/universes") != std::string::npos)
        HandleSearchUniverses(req);
    else if (path.find("gametemplates") != std::string::npos)
        HandleGameTemplates(req);
    else if (path.find("multiget/teamcreate") != std::string::npos)
        HandleTeamCreateMultiget(req);
    else if (path.find("configuration") != std::string::npos)
        HandleUniverseConfiguration(req); // /v{1,2}/universes/:universeId/configuration
    else if (path.find("groups/canmanage") != std::string::npos)
        HandleGroupsCanManage(req);
    else if (path.find("canmanage") != std::string::npos)
        HandleUserCanManagePlace(req); // /v1/user/:userId/canmanage/:placeId
    else
        HandleGroupsCanManage(req); // any other develop stub
}

void DevelopHandler::HandleSearchUniverses(evhttp_request *req) {
    const char* uri = evhttp_request_get_uri(req);

    // q=creator:User -> the user's own games; q=creator:Team -> group-owned games.
    std::string q = GetQueryParam(uri, "q");
    for (char &c : q)
        c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    bool groupOwned = q.find("team") != std::string::npos || q.find("group") != std::string::npos;

    int limit = std::atoi(GetQueryParam(uri, "limit").c_str());
    if (limit <= 0) limit = 25;
    if (limit > 100) limit = 100;

    // The signed-in account (same registry values every identity/avatar handler uses). Becomes the
    // creator when a stored universe has no UserId of its own, so the games show under "My Games".
    Registry* reg = mHttpServer->GetCore()->GetRegistry();
    int64_t selfUserId = reg->GetKeyValue<int64_t>("user.id").value_or(1);
    std::string selfUserName = reg->GetKeyValue<std::string>("user.name").value_or("Player");

    nlohmann::json data = nlohmann::json::array();
    for (int64_t universeId : mEmuDbManager->ListUniverseIds(groupOwned, limit, 0)) {
        std::optional<EmuDb::UniverseSummary> s = mEmuDbManager->GetUniverseSummary(universeId);

        // A stored 0 means "unset" in these databases, same as NULL, so fall back rather than emit a 0
        // root place (unopenable) or a 0 creator (owner-less).
        int64_t rootPlaceId = s && s->StartPlaceId && *s->StartPlaceId != 0 ? *s->StartPlaceId : universeId;
        std::string name = s && !s->Name.empty() ? s->Name : std::string("noobWarrior Place");

        std::string creatorType;
        int64_t creatorTargetId;
        std::string creatorName;
        if (groupOwned) {
            creatorType = "Group";
            creatorTargetId = s && s->GroupId && *s->GroupId != 0 ? *s->GroupId : 1;
            creatorName = mEmuDbManager->GetItemName(ItemType::Group, creatorTargetId).value_or("Group");
        } else {
            creatorType = "User";
            creatorTargetId = s && s->UserId && *s->UserId != 0 ? *s->UserId : selfUserId;
            creatorName = mEmuDbManager->GetItemName(ItemType::User, creatorTargetId)
                              .value_or(selfUserName);
        }

        nlohmann::json u;
        u["id"] = universeId;
        u["name"] = name;
        u["description"] = ""; // the Universe table stores no description
        u["isArchived"] = false;
        u["rootPlaceId"] = rootPlaceId;
        u["isActive"] = s ? s->Active : true;
        u["privacyType"] = "Public";
        u["creatorType"] = creatorType;
        u["creatorTargetId"] = creatorTargetId;
        u["creatorName"] = creatorName;
        u["created"] = UnixToIso8601(s ? s->Created : 0);
        u["updated"] = UnixToIso8601(s ? s->Updated : 0);
        data.push_back(std::move(u));
    }

    nlohmann::json j;
    j["previousPageCursor"] = nullptr;
    j["nextPageCursor"] = nullptr;
    j["data"] = std::move(data);
    SendJson(req, j);
}

void DevelopHandler::HandleGameTemplates(evhttp_request *req) {
    // No bundled new-experience templates locally; an empty set keeps the New tab from erroring.
    nlohmann::json j;
    j["data"] = nlohmann::json::array();
    SendJson(req, j);
}

void DevelopHandler::HandleGroupsCanManage(evhttp_request *req) {
    nlohmann::json j;
    j["data"] = nlohmann::json::array();
    SendJson(req, j);
}

void DevelopHandler::HandleUserCanManagePlace(evhttp_request *req) {
    // The local games are ours to edit, so always grant manage rights (Studio gates "Edit" on this).
    nlohmann::json j;
    j["Success"] = true;
    j["CanManage"] = true;
    SendJson(req, j);
}

void DevelopHandler::HandleUniverseConfiguration(evhttp_request *req) {
    int64_t universeId = strtoll(mHttpServer->GetRouteParam("universeId").c_str(), nullptr, 10);

    std::optional<EmuDb::UniverseSummary> s = mEmuDbManager->GetUniverseSummary(universeId);
    Registry* reg = mHttpServer->GetCore()->GetRegistry();
    int64_t selfUserId = reg->GetKeyValue<int64_t>("user.id").value_or(1);
    std::string selfUserName = reg->GetKeyValue<std::string>("user.name").value_or("Player");

    std::string name = s && !s->Name.empty() ? s->Name : std::string("noobWarrior Place");
    int64_t creatorId = s && s->UserId && *s->UserId != 0 ? *s->UserId : selfUserId;

    // The universe's avatar type as configured in EmuDb (UniverseMisc.AvatarType): R6, R15 or Player
    // Choice. Falls back to MorphToR6 when the universe has no setting stored.
    Roblox::UniverseAvatarType avatarType = Roblox::UniverseAvatarType::MorphToR6;
    if (auto stored = mEmuDbManager->GetUniverseAvatarType(universeId))
        if (*stored == static_cast<int>(Roblox::UniverseAvatarType::MorphToR6) ||
            *stored == static_cast<int>(Roblox::UniverseAvatarType::PlayerChoice) ||
            *stored == static_cast<int>(Roblox::UniverseAvatarType::MorphToR15))
            avatarType = static_cast<Roblox::UniverseAvatarType>(*stored);

    nlohmann::json j;
    j["id"] = universeId;
    j["name"] = name;
    j["description"] = "";
    j["universeAvatarType"] = Roblox::UniverseAvatarTypeAsApiString(avatarType);
    j["isArchived"] = false;
    j["isFriendsOnly"] = false;
    j["genre"] = "All";
    j["playableDevices"] = nlohmann::json::array({"Computer", "Phone", "Tablet", "Console", "VR"});
    j["isForSale"] = false;
    j["price"] = nullptr;
    j["allowPrivateServers"] = false;
    j["privateServerPrice"] = nullptr;
    j["privacyType"] = "Public";
    j["creatorType"] = "User";
    j["creatorTargetId"] = creatorId;
    j["creatorName"] = selfUserName;
    j["isStudioAccessToApisAllowed"] = true;
    j["studioAccessToApisAllowed"] = true;
    j["permissions"] = nlohmann::json{
        {"isThirdPartyTeleportAllowed", true},
        {"isThirdPartyAssetAllowed", true},
        {"isThirdPartyPurchaseAllowed", true}
    };
    SendJson(req, j);
}

void DevelopHandler::HandleTeamCreateMultiget(evhttp_request *req) {
    // Team Create is never active in the emulator; answer one inactive entry per requested universe so
    // the home grid stops retrying the 404 and shows no "collaborate" badge.
    nlohmann::json data = nlohmann::json::array();
    for (int64_t id : CollectIds(evhttp_request_get_uri(req), "ids"))
        data.push_back(nlohmann::json{{"id", id}, {"isActive", false}});

    nlohmann::json j;
    j["data"] = std::move(data);
    SendJson(req, j);
}
