/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: VideoHandler.cpp
// Started by: Hattozo
// Started on: 8/26/2026
// Description: (This code was generated by Claude Opus 5.)
//              See VideoHandler.h for the URL shape and why it exists.
#include <NoobWarrior/HttpServer/Emulator/VideoHandler.h>
#include <NoobWarrior/HttpServer/Emulator/ServerEmulator.h>
#include <NoobWarrior/HttpServer/Base/HttpRange.h>
#include <NoobWarrior/Video/VideoTranscoder.h>
#include <NoobWarrior/EmuDb/EmuDbManager.h>
#include <NoobWarrior/Registry.h>
#include <NoobWarrior/NoobWarrior.h>

#include "../../algorithm/gzip.h"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <charconv>
#include <fstream>
#include <system_error>
#include <vector>

using namespace NoobWarrior;

namespace {

constexpr const char *kPlaylistFileName = "index.m3u8";


// A path segment from the URL is never allowed to reach the filesystem unchecked. Only the shapes
// VideoTranscoder actually produces are accepted: "index.m3u8" and "segN.ts".
bool IsSafeFileName(const std::string &name) {
    // Long enough for "<64 hex chars>-<index>.ts", which is how VideoTranscoder names segments.
    if (name.empty() || name.size() > 96)
        return false;
    if (name.find('/') != std::string::npos || name.find('\\') != std::string::npos)
        return false;
    if (name.find("..") != std::string::npos)
        return false;
    for (char c : name) {
        const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                     || (c >= '0' && c <= '9') || c == '.' || c == '-' || c == '_';
        if (!ok)
            return false;
    }
    return true;
}

// The cache directory name is built from this, so it gets the same treatment.
bool IsSafeHash(const std::string &hash) {
    if (hash.empty() || hash.size() > 128)
        return false;
    for (char c : hash) {
        const bool ok = (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F') || (c >= '0' && c <= '9');
        if (!ok)
            return false;
    }
    return true;
}

const char *ContentTypeFor(const std::string &fileName) {
    // The engine ignores these -- onAssetLoadedContentBase does no Content-Type sniffing -- but a
    // browser hitting the same URL to debug a playlist very much does not.
    if (fileName.ends_with(".m3u8")) return "application/vnd.apple.mpegurl";
    if (fileName.ends_with(".ts"))   return "video/MP2T";
    return "application/octet-stream";
}

bool UriNeedsPrefix(const std::string &uri) {
    if (uri.empty())
        return false;
    if (uri.front() == '/')
        return false;                    // already an absolute path, or protocol-relative
    return uri.find("://") == std::string::npos;       // anything with a scheme is left alone
}

std::string RewritePlaylist(const std::vector<unsigned char> &data, const std::string &prefix) {
    const std::string text(reinterpret_cast<const char*>(data.data()), data.size());

    std::string out;
    out.reserve(text.size() + 64);

    size_t pos = 0;
    while (pos < text.size()) {
        size_t lineEnd = text.find('\n', pos);
        const bool lastLine = lineEnd == std::string::npos;
        if (lastLine)
            lineEnd = text.size();

        std::string line = text.substr(pos, lineEnd - pos);
        pos = lineEnd + 1;

        std::string terminator = lastLine ? std::string() : std::string("\n");
        if (!line.empty() && line.back() == '\r') {
            line.pop_back();
            terminator = lastLine ? std::string("\r") : std::string("\r\n");
        }

        // Only a bare URI line names a segment; every tag emitted by -hls_segment_type mpegts carries
        // its value inline, so there is no attribute to rewrite.
        if (!line.empty() && line[0] != '#' && UriNeedsPrefix(line))
            line = prefix + line;

        out += line;
        out += terminator;
    }
    return out;
}


}

// Standard base64 (the ACR parameter is padded and uses +/), tolerating the URL-safe alphabet too.
// AuthUtil::Base64UrlDecode only accepts -_ and rejects padding, so it cannot be reused here.
static std::string DecodeBase64(std::string_view encoded) {
    auto value = [](char c) -> int {
        if (c >= 'A' && c <= 'Z') return c - 'A';
        if (c >= 'a' && c <= 'z') return c - 'a' + 26;
        if (c >= '0' && c <= '9') return c - '0' + 52;
        // evhttp_parse_query form-decodes the value, so a '+' in the base64 alphabet reaches us as a
        // space. Mapping it back matters: skipping it instead would shift every following sextet and
        // quietly decode to garbage.
        if (c == '+' || c == '-' || c == ' ') return 62;
        if (c == '/' || c == '_') return 63;
        return -1;
    };
    std::string out;
    uint32_t buf = 0;
    int bits = 0;
    for (char c : encoded) {
        if (c == '=')
            break;
        const int v = value(c);
        if (v < 0)
            continue; // whitespace or stray percent-decoding leftovers
        buf = (buf << 6) | static_cast<uint32_t>(v);
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out += static_cast<char>((buf >> bits) & 0xFF);
        }
    }
    return out;
}

bool VideoHandler::AcrRequestsHls(const char *encoded) {
    if (encoded == nullptr || *encoded == 0)
        return false;

    const std::string json = DecodeBase64(encoded);
    if (json.empty())
        return false;

    const nlohmann::json parsed = nlohmann::json::parse(json, nullptr, false);
    if (!parsed.is_array())
        return false;

    for (const auto &entry : parsed) {
        if (entry.is_object() && entry.value("format", std::string {}) == "hls")
            return true;
    }
    return false;
}

VideoHandler::VideoHandler(ServerEmulator *srv) : mServerEmulator(srv) {}

std::string VideoHandler::ResolvePlaylistPath(ServerEmulator *emu, int64_t assetId, int64_t version) {
    // emu.video.format = "mp4" opts out of HLS entirely and serves the stored progressive file, which
    // the engine can still demux (Mp4InputFormat is registered).
    if (emu->GetCore()->GetRegistry()->GetKeyValue<std::string>("emu.video.format")
            .value_or(std::string("auto")) == "mp4")
        return {};

    EmuDbManager *databases = emu->GetCore()->GetEmuDbManager();
    std::string hash;
    if (databases->RetrieveAssetDataHash(assetId, version, &hash) != SqlDb::Response::Success
        || hash.empty())
        return {};    // not held here; the proxy and Roblox fallbacks still apply

    VideoTranscoder *transcoder = emu->GetVideoTranscoder();
    const VideoTranscoder::Options options = transcoder->OptionsFromRegistry();
    if (transcoder->IsPrepared(hash, options))
        return BuildPlaylistPath(assetId, hash);

    if (transcoder->NeedsPreparation(hash, options)) {
        std::vector<unsigned char> video;
        std::string storedHash;
        if (databases->RetrieveAssetData(assetId, version, &video, &storedHash)
                == SqlDb::Response::Success && !video.empty()) {
            // Anything pulled from assetdelivery is stored gzipped, and ffmpeg has no idea what to do
            // with the compressed stream. ReplyWithAsset inflates on its own path for the same reason.
            GunzipIfNeeded(video);
            transcoder->RequestPreparation(assetId, storedHash, std::move(video));
        }
    }

    Out("VideoHandler", "video asset {} is not segmented yet; serving it whole for now", assetId);
    return {};
}

std::string VideoHandler::BuildPlaylistPath(int64_t assetId, const std::string &hash) {
    return BuildUriPrefix(assetId, hash) + kPlaylistFileName;
}

std::string VideoHandler::BuildUriPrefix(int64_t assetId, const std::string &hash) {
    return "/video/v1/" + std::to_string(assetId) + "/" + hash + "/";
}

void VideoHandler::ServeFile(evhttp_request *req, const std::filesystem::path &path,
                             const std::string &fileName, const std::string &uriPrefix) {
    std::error_code ec;
    const auto fileSize = std::filesystem::file_size(path, ec);
    if (ec) {
        Out("VideoHandler", "404 for \"{}\": {}", path.string(), ec.message());
        evhttp_send_error(req, 404, "Video file not found");
        return;
    }

    std::ifstream stream(path, std::ios::binary);
    if (stream.fail()) {
        evhttp_send_error(req, 500, "Failed to open video file");
        return;
    }

    if (fileName.ends_with(".m3u8")) {
        std::vector<unsigned char> raw(static_cast<size_t>(fileSize));
        if (fileSize > 0 && !stream.read(reinterpret_cast<char*>(raw.data()),
                                         static_cast<std::streamsize>(fileSize))) {
            evhttp_send_error(req, 500, "Failed to read video playlist");
            return;
        }

        const std::string body = RewritePlaylist(raw, uriPrefix);

        evkeyvalq *playlistHeaders = evhttp_request_get_output_headers(req);
        evhttp_add_header(playlistHeaders, "Content-Type", ContentTypeFor(fileName));

        evhttp_add_header(playlistHeaders, "Cache-Control", "no-store, no-cache, must-revalidate");
        evhttp_add_header(playlistHeaders, "Pragma", "no-cache");

        Out("VideoHandler", "serving playlist for {} ({} bytes):\n{}", uriPrefix, body.size(), body);

        evbuffer *playlistBuf = evbuffer_new();
        evbuffer_add(playlistBuf, body.data(), body.size());
        evhttp_send_reply(req, 200, "OK", playlistBuf);
        evbuffer_free(playlistBuf);
        return;
    }

    evkeyvalq *outHeaders = evhttp_request_get_output_headers(req);
    evhttp_add_header(outHeaders, "Content-Type", ContentTypeFor(fileName));
    // Advertised unconditionally: a player that knows it can seek will issue ranges instead of
    // refetching a whole segment.
    evhttp_add_header(outHeaders, "Accept-Ranges", "bytes");

    const char *rangeHeader = evhttp_find_header(evhttp_request_get_input_headers(req), "Range");

    uint64_t start = 0;
    uint64_t end   = fileSize > 0 ? fileSize - 1 : 0;
    bool partial   = false;

    if (rangeHeader != nullptr) {
        if (ParseHttpRange(rangeHeader, static_cast<uint64_t>(fileSize), &start, &end)) {
            partial = true;
        } else if (IsUnsatisfiableSingleRange(rangeHeader)) {
            evhttp_add_header(outHeaders, "Content-Range",
                              ("bytes */" + std::to_string(fileSize)).c_str());
            evhttp_send_error(req, 416, "Requested Range Not Satisfiable");
            return;
        }
    }

    const uint64_t length = partial ? (end - start + 1) : static_cast<uint64_t>(fileSize);

    if (partial) {
        stream.seekg(static_cast<std::streamoff>(start), std::ios::beg);
        if (stream.fail()) {
            evhttp_send_error(req, 500, "Failed to seek video file");
            return;
        }
    }

    evbuffer *buf = evbuffer_new();

    // Copied in chunks rather than one allocation, so a request costs a fixed amount of memory no
    // matter how large the segment is.
    constexpr size_t kChunk = 64 * 1024;
    std::vector<char> chunk(kChunk);
    uint64_t remaining = length;
    while (remaining > 0) {
        const size_t want = static_cast<size_t>(std::min<uint64_t>(remaining, kChunk));
        stream.read(chunk.data(), static_cast<std::streamsize>(want));
        const std::streamsize got = stream.gcount();
        if (got <= 0)
            break;
        evbuffer_add(buf, chunk.data(), static_cast<size_t>(got));
        remaining -= static_cast<uint64_t>(got);
    }

    if (remaining != 0) {
        evbuffer_free(buf);
        evhttp_send_error(req, 500, "Failed to read video file");
        return;
    }

    Out("VideoHandler", "serving {} {} bytes {}/{}{}", fileName, length, partial ? "206" : "200",
        fileSize, rangeHeader == nullptr ? std::string() : std::string(" range=") + rangeHeader);

    if (partial) {
        const std::string contentRange = "bytes " + std::to_string(start) + "-"
                                       + std::to_string(end) + "/" + std::to_string(fileSize);
        evhttp_add_header(outHeaders, "Content-Range", contentRange.c_str());
        evhttp_send_reply(req, 206, "Partial Content", buf);
    } else {
        evhttp_send_reply(req, 200, "OK", buf);
    }
    evbuffer_free(buf);
}

void VideoHandler::OnRequest(evhttp_request *req, void *userdata) {
    const std::string assetIdText = mServerEmulator->GetRouteParam("assetId");
    const std::string hash        = mServerEmulator->GetRouteParam("hash");
    const std::string fileName    = mServerEmulator->GetRouteParam("file");

    if (!IsSafeFileName(fileName) || !IsSafeHash(hash)) {
        Out("VideoHandler", "rejecting unsafe video path \"{}/{}\"", hash, fileName);
        evhttp_send_error(req, 400, "Bad video path");
        return;
    }

    int64_t assetId = 0;
    const char *idBegin = assetIdText.data();
    const char *idEnd   = assetIdText.data() + assetIdText.size();
    if (std::from_chars(idBegin, idEnd, assetId).ec != std::errc() || assetId <= 0) {
        evhttp_send_error(req, 400, "Bad video asset id");
        return;
    }

    VideoTranscoder *transcoder = mServerEmulator->GetVideoTranscoder();
    const std::filesystem::path cacheDir =
        transcoder->GetSegmentCacheDir(hash, transcoder->OptionsFromRegistry());

    std::error_code ec;
    if (std::filesystem::is_regular_file(cacheDir / fileName, ec)) {
        ServeFile(req, cacheDir / fileName, fileName, BuildUriPrefix(assetId, hash));
        return;
    }

    auto notFound = [assetId, fileName](evhttp_request *r) {
        Out("VideoHandler", "no local or remote copy of {} for video asset {}", fileName, assetId);
        evhttp_send_error(r, 404, "Video not found");
    };

    Out("VideoHandler", "{} for asset {} is not local; forwarding to the host", fileName, assetId);

    if (!mServerEmulator->TryProxyRequest(req, notFound))
        notFound(req);
}
