/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: DataStorePersistenceHandler.h
// Started by: Hattozo
// Started on: 6/23/2026
// Description: DataStoreService persistence endpoints (gamepersistence.roblox.com). Backs GetAsync,
//              SetAsync, UpdateAsync, IncrementAsync, RemoveAsync, GetVersionAsync/ListVersionsAsync,
//              ListKeysAsync, ListDataStoresAsync and OrderedDataStore:GetSortedAsync against the
//              DataStore/DataStoreEntry/DataStoreVersion tables (EmuDb migration v17). Serves both the
//              modern /v2/persistence/{universeId}/... wire format (value in the body, metadata in
//              Roblox-Object-* headers) and the legacy /persistence/{getV2,set,increment,remove,
//              getSortedValues} format. Endpoint shapes verified against the 0.574 engine binary.
//              (Code generated by Claude Opus 4.8)
#pragma once
#include <NoobWarrior/HttpServer/Base/Handler.h>
#include <NoobWarrior/EmuDb/EmuDbManager.h>

#include <cstdint>
#include <string>

namespace NoobWarrior {
class HttpServer;
class DataStorePersistenceHandler : public Handler {
public:
    DataStorePersistenceHandler(HttpServer *srv, EmuDbManager *dbm);
    void OnRequest(evhttp_request *req, void *userdata) override;

private:
    // --- modern v2 (/v2/persistence/:universeId/datastores/...) ---
    // GET = GetAsync/GetVersionAsync, POST = SetAsync (or IncrementAsync when incrementBy is present),
    // DELETE = RemoveAsync. Value travels in the body; version/time/userids/attributes in headers.
    void HandleV2Object(evhttp_request *req, int64_t universeId, int dataStoreType);
    void HandleV2Increment(evhttp_request *req, int64_t universeId);
    void HandleV2ListVersions(evhttp_request *req, int64_t universeId);
    void HandleV2ListObjects(evhttp_request *req, int64_t universeId);     // ListKeysAsync
    void HandleV2ListDataStores(evhttp_request *req, int64_t universeId);  // ListDataStoresAsync

    // --- legacy (/persistence/...) ---
    // Here the query param "key" is the *datastore* name, "target" is the entry key and "scope" is the
    // scope, matching the old standardDataStores wire format.
    void HandleLegacyGet(evhttp_request *req);
    void HandleLegacySet(evhttp_request *req);
    void HandleLegacyIncrement(evhttp_request *req);
    void HandleLegacyRemove(evhttp_request *req);
    void HandleLegacySorted(evhttp_request *req);

    // The database a universe's DataStore data lives in: the mounted database that owns the universe,
    // else the master database. Read and write both go through this so a key round-trips. May be null
    // if nothing is mounted.
    EmuDb *SelectDb(int64_t universeId);

    // Legacy requests don't carry the universe in the path; resolve it from the Roblox-Universe-Id /
    // Roblox-Place-Id headers, falling back to 0 (a shared local universe).
    int64_t ResolveUniverseFromHeaders(evhttp_request *req);

    HttpServer *mHttpServer;
    EmuDbManager *mEmuDbManager;
};
}
