/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: DevelopHandler.h
// Started by: Hattozo
// Started on: 6/22/2026
// Description: develop.roblox.com endpoints that back the modern Studio (0.574) home/Create page:
//              /v1/search/universes (the user's games), /v1/gametemplates (the New-experience
//              templates) and /v1/user/groups/canmanage (the creator dropdown's group list).
//              (Code generated by Claude Opus 4.8)
#pragma once
#include <NoobWarrior/HttpServer/Base/Handler.h>
#include <NoobWarrior/EmuDb/EmuDbManager.h>

namespace NoobWarrior {
class HttpServer;
class DevelopHandler : public Handler {
public:
    DevelopHandler(HttpServer *srv, EmuDbManager *dbm);
    void OnRequest(evhttp_request *req, void *userdata) override;
private:
    // GET /v1/search/universes?q=creator:User|creator:Team&limit=N&sort=-GameCreated
    // Enumerates the universes stored in the mounted databases as the home page's games list.
    void HandleSearchUniverses(evhttp_request *req);
    // GET /v1/gametemplates — the New-experience template list (none locally, so an empty set).
    void HandleGameTemplates(evhttp_request *req);
    // GET /v1/user/groups/canmanage — groups the user can build for (none locally).
    void HandleGroupsCanManage(evhttp_request *req);
    // GET /v1/user/:userId/canmanage/:placeId — can this user edit the place? (yes, it's a local game).
    void HandleUserCanManagePlace(evhttp_request *req);
    // GET /v1/universes/multiget/teamcreate?ids=... — per-universe team-create status (all inactive).
    void HandleTeamCreateMultiget(evhttp_request *req);

    HttpServer *mHttpServer;
    EmuDbManager *mEmuDbManager;
};
}
