return {
    version = 1,
    base = "darcula",
    dark = {
        colors = {
            window = "#002b36",
            base = "#073642",
            alternateBase = "#05313d",
            button = "#0a4250",
            highlight = "#2aa198",
            link = "#2aa198",
            toolTipBase = "#0a4250",
            light = "#145060",
            midlight = "#0a4250",
            mid = "#0d3d49",
            dark = "#001f27",
            shadow = "#001419",
            text = "#eee8d5",
            placeholderText = "#839496",
            tabPane = "#03303c",
            listBase = "#05313d",
        },
    },
}
