return {
    version = 1,
    base = "darcula",
    dark = {
        colors = {
            window = "#272822",
            base = "#1e1f1c",
            alternateBase = "#2d2e27",
            button = "#3e3d32",
            highlight = "#f92672",
            link = "#66d9ef",
            toolTipBase = "#3e3d32",
            light = "#49483e",
            midlight = "#3e3d32",
            mid = "#3e3d32",
            dark = "#1a1b17",
            shadow = "#0d0d0b",
            text = "#f8f8f2",
            placeholderText = "#a6a28c",
            tabPane = "#22231e",
            listBase = "#22231e",
        },
    },
}
