/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: Backup.h
// Started by: Hattozo
// Started on: 12/23/2025
// Description: Contains structs and other functions involving backing up Roblox items
#pragma once
#include <NoobWarrior/EmuDb/EmuDb.h>
#include <cstdint>
#include <string>
#include <functional>

namespace NoobWarrior {
class Core;
namespace Backup {
enum class Response {
    Failed,
    Ok, // Not a success yet, we are just getting started.
    Cancelled,
    UrlNotSet,
    AccountRequired,
    DestinationInvalid,
    UnsupportedItemType,
    HttpFailed,
    NotFound,
    Unauthorized
};

enum class State {
    Failed,
    Success,
    Started,
    ScrapingMetadata,
    DiscoveringChildren,
    DownloadingFile,
    ParsingFile,
    AddingToDatabase,
    Finalizing,
};

enum class ItemSource {
    OnlineItem,
    LocalFile
};

// A node representation of an item on the Roblox platform.
class ItemDescriptor {
public:
    ItemDescriptor();
    ~ItemDescriptor();

    ItemType Type;
    int64_t Id;
    int Version;

    ItemDescriptor* GetParent();
    std::vector<ItemDescriptor*> GetChildren();

    std::string GetName();
    std::vector<unsigned char>& GetIconData();
    
    void AddChild(ItemDescriptor* child);
    void RemoveChild(ItemDescriptor* child);
private:
    ItemDescriptor* Parent { nullptr };
    std::vector<ItemDescriptor*> Children;

    // These will be populated when they are discovered through API scraping.
    std::string Name;
    std::vector<unsigned char> IconData;
};

typedef void* Destination;
enum class DestinationType {
    FileSystem,
    Database
};

struct ProcessOptions {
    std::string ProviderUrl { "https://www.roblox.com" };
    
    ItemSource TargetType;
    ItemType TargetItemType;
    int64_t TargetId;

    DestinationType DestinationType;

    // If DestinationType is Database, then this should be a pointer to a Database.
    // If DestinationType is FileSystem, this should be a pointer to a null-terminated C string that describes the path of the output directory.
    Destination Destination { nullptr };

    bool ParseFilesAndBackupFoundAssets;
    bool DownloadMetadata;
    bool DownloadAutoGeneratedThumbnails;

    std::function<void(State, std::string, size_t, size_t)> Callback;
};

class Process {
public:
    Process(Core* core, const ProcessOptions options);
    ~Process();

    Response Start();
private:
    Core*           mCore { nullptr };
    ItemDescriptor* mRoot { nullptr };
    ProcessOptions mOptions {};

    DestinationType mDestinationType;
    Destination mDestination;

    double Progress;
};
}
}