/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: Backup.h
// Started by: Hattozo
// Started on: 12/23/2025
// Description: Contains structs and other functions involving backing up Roblox items
#pragma once
#include <NoobWarrior/EmuDb/EmuDb.h>
#include <NoobWarrior/Roblox/Api/Asset.h>

#include <cstdint>
#include <string>
#include <functional>
#include <utility>
#include <map>
#include <atomic>

namespace NoobWarrior {
class Core;
namespace Backup {
enum class Response {
    Failed,
    Ok, // Not a success yet, we are just getting started.
    Cancelled,
    UrlNotSet,
    AccountRequired,
    DestinationInvalid,
    UnsupportedItemType,
    HttpFailed,
    NotFound,
    Unauthorized
};

enum class State {
    Failed, // This is fatal. All of the other "Failed" values in this enum are not fatal.
    Success,
    Started,
    Populating,
    Downloading,
    DownloadingFailed,
    Ratelimited,
    ParsingJson,
    ParsingJsonFailed,
    ParsingFile,
    ParsingFileFailed,
    AddingToDatabase,
    AddingToDatabaseFailed,
    Finalizing,
};

enum class ItemSource {
    OnlineItem,
    LocalFile
};

// A node representation of an item on the Roblox platform.
class ItemDescriptor {
public:
    ItemDescriptor();
    ~ItemDescriptor();

    ItemType Type {};
    int64_t Id {};
    int Version {};

    Roblox::AssetType AssetType {};

    std::string Name;
    std::string Description;
    std::vector<unsigned char> IconData;

    // Extra metadata harvested during population, written out to the destination in phase 2.
    Roblox::CreatorType CreatorType {};
    int64_t CreatorId {};   // owning user/group id (0 = unknown); paired with CreatorType
    int64_t Created {};     // unix epoch seconds (0 = unknown)
    int64_t Updated {};     // unix epoch seconds (0 = unknown)
    int64_t StartPlaceId {}; // Universe only: its root place
    int64_t ImageId {};      // display-icon asset id (badges, groups, ...) — what previews resolve to

    // User only: the avatar captured from the Roblox avatar API during population, written out to the
    // UserCharacter* tables and the User row's scale columns in phase 2. The worn assets are also added
    // as child Asset descriptors so their binaries get downloaded.
    std::vector<int64_t> WornAssetIds;
    std::vector<std::pair<int, int>> BodyColors; // (UserCharacterBodyPart, packed 0xRRGGBB)
    bool   HasAvatar {false};
    int    AvatarBodyType {0};
    double AvatarWidth {0}, AvatarHeight {0}, AvatarHead {0}, AvatarProportions {0};

    ItemDescriptor* GetParent() const;
    const std::vector<ItemDescriptor*>& GetChildren() const;
    
    void AddChild(ItemDescriptor* child);
    void RemoveChild(ItemDescriptor* child);
private:
    ItemDescriptor* Parent { nullptr };
    std::vector<ItemDescriptor*> Children;
};

typedef void* Destination;
enum class DestinationType {
    FileSystem,
    Database
};

struct ProcessOptions {
    std::string ProviderUrl { "https://www.roblox.com" };
    
    ItemSource TargetSource;
    ItemType TargetItemType;
    int64_t TargetId;

    DestinationType DestinationType;

    // If DestinationType is Database, then this should be a pointer to a Database.
    // If DestinationType is FileSystem, this should be a pointer to a null-terminated C string that describes the path of the output directory.
    Destination Destination { nullptr };

    bool ParseFilesAndBackupFoundAssets;
    bool DownloadMetadata;
    bool DownloadAutoGeneratedThumbnails;
    bool SetDestinationMetaFromTarget = false;

    std::function<void(State, std::string, double)> Callback;
    std::function<void(const std::function<void()>&)> DbExecutor;
};

class Process {
public:
    Process(Core* core, const ProcessOptions options);
    ~Process();

    Response Start();

    // Requests that an in-progress backup stop as soon as it can. Safe to call from another thread.
    void Cancel();

    ItemDescriptor* GetRoot();
private:
    void PopulateItemDescriptor(Backup::ItemDescriptor* descriptor, std::map<std::pair<ItemType, int64_t>, bool> &discoveredItems, int depth = 0);
    void DownloadItemDescriptorRecursively(Backup::ItemDescriptor* descriptor);
    void DownloadItemDescriptor(Backup::ItemDescriptor* descriptor);

    SqlRow BuildItemRow(Backup::ItemDescriptor* descriptor, bool includeId);
    int64_t FindParentUniverseId(Backup::ItemDescriptor* descriptor) const;

    bool DownloadAssetData(int64_t id, const std::string& cookie, std::vector<unsigned char>& out);
    bool DownloadAssetThumbnail(int64_t id, std::vector<unsigned char>& out);
    bool DownloadGameIcon(int64_t universeId, std::vector<unsigned char>& out);
    bool DownloadUserThumbnail(int64_t userId, std::vector<unsigned char>& out); // avatar headshot
    bool DownloadUserAvatar(int64_t userId, std::vector<unsigned char>& out);    // full-body avatar

    int64_t ResolveUniverseForPlace(Backup::ItemDescriptor* descriptor);
    void DownloadPlaceThumbnails(Backup::ItemDescriptor* descriptor, EmuDb* db);
    
    void SetDestinationMeta();

    int CountDescriptors(Backup::ItemDescriptor* descriptor) const;
    void RunDb(const std::function<void()>& work);
    void Report(State state, const std::string& message);

    Core*           mCore { nullptr };
    ItemDescriptor* mRoot { nullptr };
    ProcessOptions mOptions {};

    std::string mAuthCookie;

    std::atomic<bool> mCancelled { false };
    int    mMaxDepth { 6 }; // discovery recursion cap; from registry "backup.max_depth", clamped
    int    mTotalNodes { 0 };
    int    mDoneNodes  { 0 };
    double mProgress { 0 };

    std::map<int64_t, std::vector<std::pair<int64_t, std::vector<unsigned char>>>> mUniverseCarouselCache;
};
}
}