/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: main.cpp
// Started by: Hattozo
// Started on: 8/18/2025
// Description: Generates file-format DOM classes and enums from a Roblox JSON API dump.
#include <cppgenerate/enum.h>

#include "PropertyPatches.h"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

using json = nlohmann::json;
namespace fs = std::filesystem;

namespace {

constexpr std::string_view kNamespace = "NoobWarrior::Roblox";

// Classes the tree layer already provides by hand. RobloxFiles does the same for Instance: the
// generated set and the hand-written set share one namespace, so a generated redeclaration would
// collide rather than extend.
constexpr std::string_view kHandWrittenClasses[] = {
    "Instance",
};

bool IsHandWritten(std::string_view className) {
    return std::find(std::begin(kHandWrittenClasses), std::end(kHandWrittenClasses),
                     className) != std::end(kHandWrittenClasses);
}
constexpr std::string_view kBanner = R"CPP(/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 * Generated by NoobWarrior.RobloxFileFormatGenerator; do not edit manually.
 */
)CPP";

const std::set<std::string> kCppKeywords = {
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor",
    "bool", "break", "case", "catch", "char", "char8_t", "char16_t", "char32_t",
    "class", "compl", "concept", "const", "consteval", "constexpr", "constinit",
    "const_cast", "continue", "co_await", "co_return", "co_yield", "decltype",
    "default", "delete", "do", "double", "dynamic_cast", "else", "enum", "explicit",
    "export", "extern", "false", "float", "for", "friend", "goto", "if", "inline",
    "int", "long", "mutable", "namespace", "new", "noexcept", "not", "not_eq",
    "nullptr", "operator", "or", "or_eq", "private", "protected", "public", "register",
    "reinterpret_cast", "requires", "return", "short", "signed", "sizeof", "static",
    "static_assert", "static_cast", "struct", "switch", "template", "this",
    "thread_local", "throw", "true", "try", "typedef", "typeid", "typename", "union",
    "unsigned", "using", "virtual", "void", "volatile", "wchar_t", "while", "xor",
    "xor_eq",
};

std::string Identifier(std::string_view value) {
    std::string result;
    result.reserve(value.size() + 1);
    for (unsigned char character : value) {
        if ((result.empty() && (std::isalpha(character) || character == '_')) ||
            (!result.empty() && (std::isalnum(character) || character == '_'))) {
            result.push_back(static_cast<char>(character));
        } else if (std::isalnum(character) || character == '_') {
            result.push_back('_');
            result.push_back(static_cast<char>(character));
        } else {
            result.push_back('_');
        }
    }
    if (result.empty())
        result = "Unnamed";
    if (kCppKeywords.contains(result))
        result += '_';
    return result;
}

std::string Escape(std::string_view value) {
    std::ostringstream output;
    for (unsigned char character : value) {
        switch (character) {
        case '\\': output << "\\\\"; break;
        case '"': output << "\\\""; break;
        case '\n': output << "\\n"; break;
        case '\r': output << "\\r"; break;
        case '\t': output << "\\t"; break;
        default:
            if (character < 0x20)
                output << "\\x" << std::hex << static_cast<int>(character);
            else
                output << character;
        }
    }
    return output.str();
}

bool HasTag(const json &value, std::string_view tag) {
    const auto tags = value.find("Tags");
    if (tags == value.end() || !tags->is_array())
        return false;
    return std::any_of(tags->begin(), tags->end(), [&](const json &candidate) {
        return candidate.is_string() && candidate.get<std::string>() == tag;
    });
}

std::string JsonString(const json &value, std::string_view key,
                       std::string fallback = {}) {
    const auto iterator = value.find(key);
    return iterator != value.end() && iterator->is_string()
        ? iterator->get<std::string>() : std::move(fallback);
}

struct PropertyModel {
    std::string Name;
    std::string Category;
    std::string Type;
    bool CanLoad {true};
    bool CanSave {true};
    // A C++ expression producing the engine's default, or empty when none is known. The dump
    // carries no defaults at all; these come from PropertyPatches.h.
    std::string Default;
};

struct ClassModel {
    std::string Name;
    std::string CppName;
    std::string Superclass;
    std::string CppSuperclass;
    bool IsService {};
    bool Creatable {true};
    std::vector<PropertyModel> Properties;
};

// The serialization-only members and defaults recorded for one class. A patched member is
// always savable -- it exists precisely because the format writes it.
std::vector<PropertyModel> PatchesForClass(std::string_view className) {
    std::vector<PropertyModel> patched;
    for (const NoobWarrior::RobloxGenerator::PropertyPatch &patch : NoobWarrior::RobloxGenerator::kPropertyPatches) {
        if (patch.ClassName != className)
            continue;
        PropertyModel model;
        model.Name = std::string(patch.PropertyName);
        model.Category = std::string(patch.Category);
        model.Type = std::string(patch.Type);
        model.Default = std::string(patch.Default);
        patched.push_back(std::move(model));
    }
    return patched;
}

std::vector<ClassModel> ReadClasses(const json &dump) {
    const auto classesNode = dump.find("Classes");
    if (classesNode == dump.end() || !classesNode->is_array())
        throw std::runtime_error("API dump has no Classes array");

    std::vector<ClassModel> classes;
    for (const json &entry : *classesNode) {
        if (!entry.is_object())
            continue;
        ClassModel model;
        model.Name = JsonString(entry, "Name");
        if (model.Name.empty())
            continue;
        model.CppName = Identifier(model.Name);
        model.Superclass = JsonString(entry, "Superclass", "<<<ROOT>>>");
        model.CppSuperclass = model.Superclass == "<<<ROOT>>>"
            ? "::NoobWarrior::Roblox::Instance"
            : "::NoobWarrior::Roblox::" + Identifier(model.Superclass);
        model.IsService = HasTag(entry, "Service");
        model.Creatable = !HasTag(entry, "NotCreatable");

        const auto members = entry.find("Members");
        if (members != entry.end() && members->is_array()) {
            for (const json &member : *members) {
                if (!member.is_object() || JsonString(member, "MemberType") != "Property")
                    continue;
                PropertyModel property;
                property.Name = JsonString(member, "Name");
                const auto valueType = member.find("ValueType");
                if (valueType != member.end() && valueType->is_object()) {
                    property.Category = JsonString(*valueType, "Category", "Unknown");
                    property.Type = JsonString(*valueType, "Name", "Unknown");
                } else {
                    property.Category = "Unknown";
                    property.Type = "Unknown";
                }
                const auto serialization = member.find("Serialization");
                if (serialization != member.end() && serialization->is_object()) {
                    property.CanLoad = serialization->value("CanLoad", true);
                    property.CanSave = serialization->value("CanSave", true);
                }
                model.Properties.push_back(std::move(property));
            }
        }
        // The dump describes the scripting surface, so it is missing every serialization-only
        // member (Color3uint8, size, shape, Health_XML) and every default value. Both come from
        // the patch table, which is the one place those facts live.
        for (const PropertyModel &patched : PatchesForClass(model.Name)) {
            // Match on the identifier, not the raw name: C# cannot spell a serialized name
            // containing a space, so the reference's field for "Enable VR Mode" is
            // Enable_VR_Mode. They are one property, and the dump has the name the file uses.
            const std::string patchedIdentifier = Identifier(patched.Name);
            const auto existing = std::find_if(model.Properties.begin(), model.Properties.end(),
                [&patchedIdentifier](const PropertyModel &candidate) {
                    return Identifier(candidate.Name) == patchedIdentifier;
                });
            if (existing == model.Properties.end())
                model.Properties.push_back(patched);
            else if (existing->Default.empty())
                existing->Default = patched.Default;
        }

        std::sort(model.Properties.begin(), model.Properties.end(),
            [](const PropertyModel &left, const PropertyModel &right) {
                return left.Name < right.Name;
            });
        classes.push_back(std::move(model));
    }
    std::sort(classes.begin(), classes.end(),
        [](const ClassModel &left, const ClassModel &right) { return left.Name < right.Name; });
    return classes;
}

void WriteText(const fs::path &path, std::string_view value) {
    std::ofstream stream(path, std::ios::binary | std::ios::trunc);
    if (!stream)
        throw std::runtime_error("could not open " + path.string());
    stream.write(value.data(), static_cast<std::streamsize>(value.size()));
    if (!stream)
        throw std::runtime_error("could not write " + path.string());
}

void WriteSupportHeader(const fs::path &outputDirectory) {
    std::ostringstream output;
    output << kBanner << R"CPP(#pragma once

#include <any>
#include <span>
#include <string_view>

namespace NoobWarrior::Roblox {
struct PropertyDescriptor {
    std::string_view Name;
    std::string_view Category;
    std::string_view Type;
    bool CanLoad;
    bool CanSave;
    // The engine's default for this property, or null when none is known. A binary column has to
    // carry a value for every instance of its class, so an instance that lacks the property still
    // needs one written -- and the C++ type's zero is the wrong answer often enough to break a
    // place (CollisionGroup wants "Default", CanQuery wants true, Material's lowest member is
    // 256). Captureless lambdas, so the table stays a constant expression.
    std::any (*Default)();
};

struct ClassDescriptor {
    std::string_view Name;
    std::string_view Superclass;
    std::span<const PropertyDescriptor> Properties;
    bool IsService;
    bool Creatable;
};
} // namespace NoobWarrior::Roblox
)CPP";
    WriteText(outputDirectory / "PropertyDescriptor.h", output.str());
}

// The registry declarations live apart from Classes.h so a consumer that only wants to ask a
// property's declared type does not compile 906 class headers to get there.
void WriteRegistryHeader(const fs::path &outputDirectory) {
    std::ostringstream output;
    output << kBanner << "#pragma once\n\n"
        << "#include <span>\n#include <string_view>\n\n"
        << "#include \"PropertyDescriptor.h\"\n\n"
        << "namespace " << kNamespace << " {\n"
        << "// Every class the dump described, sorted by name.\n"
        << "std::span<const ClassDescriptor *const> AllClasses();\n\n"
        << "// Null when the dump does not describe the class.\n"
        << "const ClassDescriptor *FindClass(std::string_view className);\n\n"
        << "// Walks Superclass, so Part.Color resolves through BasePart. Null when neither the\n"
           "// class nor any ancestor declares the property.\n"
        << "const PropertyDescriptor *FindProperty(std::string_view className,\n"
           "                                      std::string_view propertyName);\n"
        << "} // namespace " << kNamespace << "\n";
    WriteText(outputDirectory / "Registry.h", output.str());
}

struct AccessorMapping {
    std::string CppType;
    std::string PropertyTypeName;
    std::string XmlToken;
    bool ThroughEnum {};
    bool NeedsDataTypes {};
};

// Accessor names the tree layer already spells. Nothing in the current dump lands here now that
// Instance is hand-written, but a later dump adding one would silently shadow a base member.
bool IsReservedAccessor(std::string_view identifier) {
    static constexpr std::string_view kReserved[] = {
        "Attribute", "Children", "Descendants", "Descriptor", "FullName",
        "Parent", "Properties", "Property", "PropertyValue",
    };
    return std::find(std::begin(kReserved), std::end(kReserved), identifier) !=
        std::end(kReserved);
}

// Maps a dump property onto the C++ type its value actually holds once decoded -- which is not
// always the type the dump names. BrickColor decodes to a palette index, ContentId shares
// DataTypes::Content with Content, and every enum is stored as the raw uint32 the file carried.
//
// Returns false for types the DataTypes layer does not model (DateTime, QDir, TweenInfo, the
// Class category's referents). Those still get a descriptor entry; they just get no accessor,
// because an accessor whose type lies about the storage is worse than none.
bool MapAccessor(const PropertyModel &property, AccessorMapping &mapping) {
    struct Entry {
        std::string_view Type;
        std::string_view CppType;
        std::string_view PropertyTypeName;
        std::string_view XmlToken;
        bool NeedsDataTypes;
    };
    static constexpr Entry kPrimitives[] = {
        {"bool",   "bool",        "Bool",   "bool",   false},
        {"double", "double",      "Double", "double", false},
        {"float",  "float",       "Float",  "float",  false},
        {"int",    "int32_t",     "Int",    "int",    false},
        {"int64",  "int64_t",     "Int64",  "int64",  false},
        {"string", "std::string", "String", "string", false},
    };
    static constexpr Entry kDataTypes[] = {
        {"Axes",                 "DataTypes::Axes",                 "Axes",                 "Axes",                 true},
        {"BinaryString",         "std::string",                     "String",               "BinaryString",         false},
        {"BrickColor",           "int32_t",                         "BrickColor",           "BrickColor",           false},
        {"CFrame",               "DataTypes::CFrame",               "CFrame",               "CoordinateFrame",      true},
        {"Color3",               "DataTypes::Color3",               "Color3",               "Color3",               true},
        {"ColorSequence",        "DataTypes::ColorSequence",        "ColorSequence",        "ColorSequence",        true},
        {"Content",              "DataTypes::Content",              "Content",              "Content",              true},
        {"ContentId",            "DataTypes::ContentId",            "String",               "ContentId",            true},
        {"Faces",                "DataTypes::Faces",                "Faces",                "Faces",                true},
        {"Font",                 "DataTypes::FontFace",             "FontFace",             "Font",                 true},
        {"NumberRange",          "DataTypes::NumberRange",          "NumberRange",          "NumberRange",          true},
        {"NumberSequence",       "DataTypes::NumberSequence",       "NumberSequence",       "NumberSequence",       true},
        {"BinaryString",         "std::string",                     "String",               "BinaryString",         false},
        {"Color3uint8",          "DataTypes::Color3uint8",          "Color3uint8",          "Color3uint8",          true},
        {"OptionalCFrame",       "std::optional<DataTypes::CFrame>", "OptionalCFrame",      "OptionalCoordinateFrame", true},
        // Every codec stores this as an optional -- an absent CustomPhysicalProperties is a real,
        // common state, and PROP::Write rejects a bare value.
        {"PhysicalProperties",   "std::optional<DataTypes::PhysicalProperties>", "PhysicalProperties", "PhysicalProperties", true},
        {"ProtectedString",      "DataTypes::ProtectedString",      "ProtectedString",      "ProtectedString",      true},
        {"Ray",                  "DataTypes::Ray",                  "Ray",                  "Ray",                  true},
        {"Rect",                 "DataTypes::Rect",                 "Rect",                 "Rect2D",               true},
        {"SecurityCapabilities", "DataTypes::SecurityCapabilities", "SecurityCapabilities", "SecurityCapabilities", true},
        {"UDim",                 "DataTypes::UDim",                 "UDim",                 "UDim",                 true},
        {"UDim2",                "DataTypes::UDim2",                "UDim2",                "UDim2",               true},
        {"UniqueId",             "DataTypes::UniqueId",             "UniqueId",             "UniqueId",             true},
        {"Vector2",              "DataTypes::Vector2",              "Vector2",              "Vector2",              true},
        {"Vector3",              "DataTypes::Vector3",              "Vector3",              "Vector3",              true},
    };

    const auto take = [&](const Entry &entry) {
        mapping.CppType = std::string(entry.CppType);
        mapping.PropertyTypeName = std::string(entry.PropertyTypeName);
        mapping.XmlToken = std::string(entry.XmlToken);
        mapping.NeedsDataTypes = entry.NeedsDataTypes;
        return true;
    };

    if (property.Category == "Primitive") {
        for (const Entry &entry : kPrimitives) {
            if (entry.Type == property.Type)
                return take(entry);
        }
        return false;
    }
    if (property.Category == "DataType") {
        for (const Entry &entry : kDataTypes) {
            if (entry.Type == property.Type)
                return take(entry);
        }
        return false;
    }
    if (property.Category == "Enum") {
        mapping.CppType = "Enums::" + Identifier(property.Type);
        mapping.PropertyTypeName = "Enum";
        mapping.XmlToken = "token";
        mapping.ThroughEnum = true;
        return true;
    }
    // The Class category is a referent, not a pointer: the reader leaves Ref properties as the
    // int32 index the file stored, so a typed Instance * accessor would be a fiction.
    return false;
}

// The descriptor's Default is a captureless lambda returning std::any, so the value it produces
// has to be the exact type the codec stores for that property -- not merely something that
// converts to it, since the reader casts with std::any_cast.
std::string DefaultFactory(const PropertyModel &property) {
    if (property.Default.empty())
        return "nullptr";
    std::string value;
    if (property.Category == "Enum") {
        value = "static_cast<uint32_t>(" + property.Default + ")";
    } else if (property.Category == "Primitive") {
        if (property.Type == "string")
            value = "std::string(" + property.Default + ")";
        else if (property.Type == "int")
            value = "static_cast<int32_t>(" + property.Default + ")";
        else if (property.Type == "int64")
            value = "static_cast<int64_t>(" + property.Default + ")";
        else if (property.Type == "float")
            value = "static_cast<float>(" + property.Default + ")";
        else if (property.Type == "double")
            value = "static_cast<double>(" + property.Default + ")";
        else
            value = property.Default;
    } else if (property.Category == "DataType") {
        // BrickColor and BinaryString are stored as a palette index and a string respectively.
        if (property.Type == "BrickColor")
            value = "static_cast<int32_t>(" + property.Default + ")";
        else if (property.Type == "BinaryString")
            value = "std::string(" + property.Default + ")";
        else
            value = property.Default;
    } else {
        return "nullptr";
    }
    return "[]() -> std::any { return " + value + "; }";
}

struct ClassSource {
    std::string Header;
    std::string Implementation;
};

ClassSource GenerateClass(const ClassModel &model) {
    struct Accessor {
        const PropertyModel *Property;
        AccessorMapping Mapping;
        std::string Suffix;
    };
    std::vector<Accessor> accessors;
    std::set<std::string> emitted;
    bool needsDataTypes = false;
    bool needsEnums = false;
    for (const PropertyModel &property : model.Properties) {
        Accessor accessor {&property, {}, Identifier(property.Name)};
        // A property the format never saves is a scripting alias for one it does: the dump lists
        // BasePart.Color, and the file stores Color3uint8. Emitting the alias is what put a
        // Color column typed Color3uint8 onto every Part in a place, which the engine declares
        // as Color3 and refuses. The member the file actually stores comes from the patch table
        // and is savable, so gating on this keeps exactly one of each pair.
        if (!property.CanSave || !property.CanLoad)
            continue;
        if (IsReservedAccessor(accessor.Suffix) || !MapAccessor(property, accessor.Mapping))
            continue;
        // Two distinct serialized names can sanitize to one identifier; a second definition of
        // the same member function would not compile.
        if (!emitted.insert(accessor.Suffix).second)
            continue;
        needsDataTypes = needsDataTypes || accessor.Mapping.NeedsDataTypes;
        needsEnums = needsEnums || accessor.Mapping.ThroughEnum;
        accessors.push_back(std::move(accessor));
    }

    // Every include the classes need is on Classes.h once, so nothing is emitted per class.
    (void)needsDataTypes;
    (void)needsEnums;

    std::ostringstream header;
    header << "class " << model.CppName << " : public " << model.CppSuperclass << " {\n"
        << "public:\n"
        << "    " << model.CppName << "();\n\n"
        << "    static const ClassDescriptor &Descriptor();\n";

    for (const Accessor &accessor : accessors) {
        const std::string quoted = "\"" + Escape(accessor.Property->Name) + "\"";
        const std::string stored = accessor.Mapping.ThroughEnum
            ? std::string("uint32_t") : accessor.Mapping.CppType;
        header << "\n    // " << accessor.Property->Category << '/' << accessor.Property->Type
               << '\n'
               << "    " << accessor.Mapping.CppType << " Get" << accessor.Suffix << "() const {\n"
               << "        return ";
        if (accessor.Mapping.ThroughEnum)
            header << "static_cast<" << accessor.Mapping.CppType << ">(";
        header << "GetPropertyValue<" << stored << ">(" << quoted << ")";
        if (accessor.Mapping.ThroughEnum)
            header << ')';
        header << ";\n    }\n"
               << "    void Set" << accessor.Suffix << '(' << accessor.Mapping.CppType
               << " value) {\n"
               << "        SetPropertyValue<" << stored << ">(" << quoted
               << ", PropertyType::" << accessor.Mapping.PropertyTypeName
               << ", \"" << accessor.Mapping.XmlToken << "\", ";
        if (accessor.Mapping.ThroughEnum)
            header << "static_cast<uint32_t>(value)";
        else
            header << "std::move(value)";
        header << ");\n    }\n"
               << "    bool Has" << accessor.Suffix << "() const { return HasProperty("
               << quoted << "); }\n";
    }

    header << "};\n";

    std::ostringstream implementation;
    implementation << model.CppName << "::" << model.CppName << "() {\n"
        << "    ClassName = \"" << Escape(model.Name) << "\";\n"
        << "    Name = ClassName;\n"
        << "    IsService = " << (model.IsService ? "true" : "false") << ";\n"
        << "}\n\n"
        << "const ClassDescriptor &" << model.CppName << "::Descriptor() {\n";
    if (model.Properties.empty()) {
        implementation << "    static const std::array<PropertyDescriptor, 0> properties {};\n";
    } else {
        implementation << "    static const std::array<PropertyDescriptor, "
            << model.Properties.size() << "> properties {{\n";
        for (const PropertyModel &property : model.Properties) {
            implementation << "        {\"" << Escape(property.Name) << "\", \""
                << Escape(property.Category) << "\", \"" << Escape(property.Type) << "\", "
                << (property.CanLoad ? "true" : "false") << ", "
                << (property.CanSave ? "true" : "false") << ", "
                << DefaultFactory(property) << "},\n";
        }
        implementation << "    }};\n";
    }
    implementation << "    static const ClassDescriptor descriptor {\"" << Escape(model.Name)
        << "\", \"" << Escape(model.Superclass) << "\", properties, "
        << (model.IsService ? "true" : "false") << ", "
        << (model.Creatable ? "true" : "false") << "};\n"
        << "    return descriptor;\n"
        << "}\n";
    return {header.str(), implementation.str()};
}

void GenerateEnums(const json &dump, const fs::path &outputDirectory) {
    const auto enumsNode = dump.find("Enums");
    if (enumsNode == dump.end() || !enumsNode->is_array())
        throw std::runtime_error("API dump has no Enums array");

    struct EnumModel {
        std::string Name;
        std::unique_ptr<cppgenerate::Enum> Definition;
    };
    std::vector<EnumModel> enums;
    for (const json &entry : *enumsNode) {
        if (!entry.is_object())
            continue;
        const std::string name = JsonString(entry, "Name");
        if (name.empty())
            continue;
        auto definition = std::make_unique<cppgenerate::Enum>();
        definition->setName(Identifier(name)).setIsEnumClass(true)
            .setNamespace(std::string(kNamespace) + "::Enums");
        std::set<std::string> usedNames;
        const auto items = entry.find("Items");
        if (items != entry.end() && items->is_array()) {
            for (const json &item : *items) {
                if (!item.is_object())
                    continue;
                std::string itemName = Identifier(JsonString(item, "Name", "Value"));
                while (!usedNames.insert(itemName).second)
                    itemName += '_';
                definition->addEnumValue(itemName, item.value("Value", 0));
            }
        }
        enums.push_back({name, std::move(definition)});
    }
    std::sort(enums.begin(), enums.end(), [](const EnumModel &left, const EnumModel &right) {
        return left.Name < right.Name;
    });

    std::ostringstream output;
    output << kBanner << "#pragma once\n\n#include <cstdint>\n\n"
        << "namespace " << kNamespace << "::Enums {\n";
    for (const EnumModel &model : enums) {
        output << "enum class " << model.Definition->getName() << " : int32_t {\n";
        for (const auto &[name, value] : model.Definition->getEnumNameToValues())
            output << "    " << name << " = " << value << ",\n";
        output << "};\n\n";
    }
    output << "} // namespace " << kNamespace << "::Enums\n";
    WriteText(outputDirectory / "Enums.h", output.str());
}

// Emits a descriptor for a class the tree provides by hand. It has no header of its own to sit
// in, so the definition goes straight into Classes.cpp.
std::string HandWrittenDescriptor(const ClassModel &model) {
    std::ostringstream out;
    out << "// " << Escape(model.Name)
        << " is hand-written in Tree/, but FindProperty walks Superclass to the end of the "
           "chain,\n// so the registry still needs its property set.\n"
        << "const ClassDescriptor &" << model.CppName << "Descriptor() {\n";
    if (model.Properties.empty()) {
        out << "    static const std::array<PropertyDescriptor, 0> properties {};\n";
    } else {
        out << "    static const std::array<PropertyDescriptor, " << model.Properties.size()
            << "> properties {{\n";
        for (const PropertyModel &property : model.Properties) {
            out << "        {\"" << Escape(property.Name) << "\", \""
                << Escape(property.Category) << "\", \"" << Escape(property.Type) << "\", "
                << (property.CanLoad ? "true" : "false") << ", "
                << (property.CanSave ? "true" : "false") << ", "
                << DefaultFactory(property) << "},\n";
        }
        out << "    }};\n";
    }
    // Superclass is empty, which is what stops FindProperty's walk.
    out << "    static const ClassDescriptor descriptor {\"" << Escape(model.Name)
        << "\", \"\", properties, false, "
        << (model.Creatable ? "true" : "false") << "};\n"
           "    return descriptor;\n}\n";
    return out.str();
}

void GenerateUmbrella(const std::vector<ClassModel> &classes,
                       const std::vector<ClassModel> &handWritten,
                       const fs::path &outputDirectory) {
    // One header holds every class, so a base has to appear before anything deriving from it.
    // Depth in the Superclass chain gives that ordering; ties stay alphabetical so the output is
    // stable between runs.
    std::map<std::string, const ClassModel *> byName;
    for (const ClassModel &model : classes)
        byName.emplace(model.Name, &model);

    const auto depthOf = [&byName](const ClassModel &model) {
        int depth = 0;
        std::string current = model.Superclass;
        // Bounded, so a malformed chain cannot spin forever.
        for (; depth < 64; ++depth) {
            const auto found = byName.find(current);
            if (found == byName.end())
                break;
            current = found->second->Superclass;
        }
        return depth;
    };

    std::vector<const ClassModel *> ordered;
    ordered.reserve(classes.size());
    for (const ClassModel &model : classes)
        ordered.push_back(&model);
    std::sort(ordered.begin(), ordered.end(),
        [&depthOf](const ClassModel *left, const ClassModel *right) {
            const int leftDepth = depthOf(*left);
            const int rightDepth = depthOf(*right);
            return leftDepth != rightDepth ? leftDepth < rightDepth : left->Name < right->Name;
        });

    std::vector<ClassSource> sources;
    sources.reserve(ordered.size());
    for (const ClassModel *model : ordered)
        sources.push_back(GenerateClass(*model));

    std::ostringstream header;
    header << kBanner << "#pragma once\n\n"
        << "#include <cstdint>\n#include <memory>\n#include <optional>\n#include <span>\n"
           "#include <string>\n#include <string_view>\n#include <utility>\n\n"
        << "#include \"Enums.h\"\n"
        << "#include \"Registry.h\"\n"
        << "#include <NoobWarrior/Roblox/FileFormat/DataTypes/DataTypes.h>\n"
        << "#include <NoobWarrior/Roblox/FileFormat/Tree/Instance.h>\n"
        << "\nnamespace " << kNamespace << " {\n";
    for (const ClassSource &source : sources)
        header << source.Header << "\n";
    header << "std::unique_ptr<::NoobWarrior::Roblox::Instance> CreateInstance("
              "std::string_view className);\n"
        << "} // namespace " << kNamespace << "\n";
    WriteText(outputDirectory / "Classes.h", header.str());

    std::ostringstream implementation;
    implementation << kBanner << "#include \"Classes.h\"\n\n"
        << "#include <algorithm>\n#include <any>\n#include <array>\n\n"
        << "namespace " << kNamespace << " {\n";
    for (const ClassSource &source : sources)
        implementation << source.Implementation << "\n";
    implementation
        << "std::unique_ptr<::NoobWarrior::Roblox::Instance> CreateInstance("
           "std::string_view className) {\n";
    for (const ClassModel &model : classes) {
        implementation << "    if (className == \"" << Escape(model.Name)
            << "\") return std::make_unique<" << model.CppName << ">();\n";
    }
    implementation << "    auto instance = std::make_unique<::NoobWarrior::Roblox::Instance>();\n"
        << "    instance->ClassName = std::string(className);\n"
        << "    instance->Name = instance->ClassName;\n"
        << "    return instance;\n"
        << "}\n\n";

    // The registry is what lets the serializer ask a property's declared type. Sorting by name
    // keeps lookup a binary search rather than a scan across ~900 classes.
    std::vector<const ClassModel *> sorted;
    sorted.reserve(classes.size() + handWritten.size());
    for (const ClassModel &model : classes)
        sorted.push_back(&model);
    for (const ClassModel &model : handWritten)
        sorted.push_back(&model);
    std::sort(sorted.begin(), sorted.end(), [](const ClassModel *left, const ClassModel *right) {
        return left->Name < right->Name;
    });
    // FindClass binary-searches this table, so a hand-written class has to sit in sorted position
    // like any other.
    const auto isHandWritten = [&handWritten](const ClassModel *model) {
        return std::any_of(handWritten.begin(), handWritten.end(),
            [model](const ClassModel &candidate) { return candidate.Name == model->Name; });
    };

    implementation << "namespace {\n";
    for (const ClassModel &model : handWritten)
        implementation << HandWrittenDescriptor(model);

    implementation
        << "// Each Descriptor() hands back a function-local static, so the table is built on\n"
           "// first use rather than at load time.\n"
        << "const std::array<const ClassDescriptor *, " << sorted.size()
        << "> &Classes() {\n"
        << "    static const std::array<const ClassDescriptor *, " << sorted.size()
        << "> table {{\n";
    for (const ClassModel *model : sorted) {
        implementation << "        &"
            << (isHandWritten(model) ? model->CppName + "Descriptor()"
                                     : model->CppName + "::Descriptor()")
            << ",\n";
    }
    implementation << "    }};\n"
           "    return table;\n"
           "}\n} // namespace\n\n"
        << "std::span<const ClassDescriptor *const> AllClasses() {\n"
           "    return Classes();\n"
           "}\n\n"
        << "const ClassDescriptor *FindClass(std::string_view className) {\n"
           "    const auto &table = Classes();\n"
           "    const auto found = std::lower_bound(table.begin(), table.end(), className,\n"
           "        [](const ClassDescriptor *entry, std::string_view name) {\n"
           "            return entry->Name < name;\n"
           "        });\n"
           "    if (found == table.end() || (*found)->Name != className)\n"
           "        return nullptr;\n"
           "    return *found;\n"
           "}\n\n"
        << "const PropertyDescriptor *FindProperty(std::string_view className,\n"
           "                                      std::string_view propertyName) {\n"
           "    const ClassDescriptor *current = FindClass(className);\n"
           "    // Bounded, so a malformed Superclass chain cannot spin forever.\n"
           "    for (int depth = 0; depth < 64 && current != nullptr; ++depth) {\n"
           "        for (const PropertyDescriptor &property : current->Properties) {\n"
           "            if (property.Name == propertyName)\n"
           "                return &property;\n"
           "        }\n"
           "        if (current->Superclass.empty())\n"
           "            break;\n"
           "        current = FindClass(current->Superclass);\n"
           "    }\n"
           "    return nullptr;\n"
           "}\n"
        << "} // namespace " << kNamespace << "\n";
    WriteText(outputDirectory / "Classes.cpp", implementation.str());

}

} // namespace

int main(int argc, char **argv) {
    if (argc != 3) {
        std::cerr << "Usage: " << (argc > 0 ? argv[0] : "RobloxFileFormatGenerator")
                  << " <API-Dump.json> <output-directory>\n";
        return 2;
    }

    try {
        const fs::path inputPath = fs::absolute(argv[1]);
        const fs::path outputDirectory = fs::absolute(argv[2]);
        std::ifstream input(inputPath, std::ios::binary);
        if (!input)
            throw std::runtime_error("could not open " + inputPath.string());
        const json dump = json::parse(input);
        std::vector<ClassModel> classes = ReadClasses(dump);
        // Hand-written classes share the namespace, so emitting them would redeclare rather
        // than extend. Anything deriving from one is repointed at the tree type above.
        std::vector<ClassModel> handWritten;
        for (const ClassModel &model : classes) {
            if (IsHandWritten(model.Name))
                handWritten.push_back(model);
        }
        std::erase_if(classes, [](const ClassModel &model) {
            return IsHandWritten(model.Name);
        });
        if (classes.empty())
            throw std::runtime_error("API dump contains no usable classes");

        fs::create_directories(outputDirectory);
        WriteSupportHeader(outputDirectory);
        WriteRegistryHeader(outputDirectory);
        GenerateEnums(dump, outputDirectory);
        GenerateUmbrella(classes, handWritten, outputDirectory);
        std::cout << "Generated " << classes.size() << " Roblox classes in "
                  << outputDirectory.string() << '\n';
        return 0;
    } catch (const std::exception &exception) {
        std::cerr << "Roblox file-format generation failed: " << exception.what() << '\n';
        return 1;
    }
}
