/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: VideoTranscoder.h
// Started by: Hattozo
// Started on: 8/26/2026
// Description: This transcodes videos and shid using ffmpeg, needed for creating HLS playlists which Roblox needs.
// (Disclaimer: This code was generated by Claude Opus 5.)
#pragma once

#include <atomic>
#include <condition_variable>
#include <cstdint>
#include <deque>
#include <filesystem>
#include <mutex>
#include <string>
#include <thread>
#include <unordered_set>
#include <vector>

namespace NoobWarrior {
class Core;

// Bumped whenever a change alters the segments produced from the same input. The cache directory name
// carries it, so stale output is never looked up again rather than served.
constexpr int kVideoSegmentCacheSchema = 6;

class VideoTranscoder {
public:
    enum class Response {
        Success,
        Disabled,        // emu.video.transcode is off and the input would need re-encoding
        NoEncoder,       // no usable ffmpeg executable could be resolved
        EmptyInput,
        TempFileFailed,  // could not stage the input or read the output back
        ProbeFailed,     // ffprobe could not make sense of the input
        EncodeFailed,    // ffmpeg ran but exited non-zero
        OutputMissing,   // ffmpeg exited 0 but produced nothing
        BadPlaylist,     // the playlist ffmpeg wrote is not one the engine's parser would accept
    };

    struct Options {
        int  MaxHeight      {720};  // downscale anything taller; 0 keeps the original resolution
        int  BitrateKbps    {2000};
        int  AudioKbps      {128};
        int  SegmentSeconds {6};    // target #EXTINF duration
        bool AllowRemux     {true}; // stream-copy H.264/AAC input instead of re-encoding it
    };

    struct Probe {
        bool        Ok {false};
        std::string Container;
        std::string VideoCodec;
        std::string AudioCodec;
        int         Width  {0};
        int         Height {0};
        double      DurationSeconds {0.0};
    };

    // What Segment() produced. Names are relative to the output directory, playlist first.
    struct Segments {
        std::string              PlaylistName;    // "index.m3u8"
        std::vector<std::string> Names;           // playlist, then the .ts files in playlist order
        uint64_t                 TotalBytes {0};
    };

    explicit VideoTranscoder(Core *core);
    ~VideoTranscoder();

    Options OptionsFromRegistry();

    // Where Segment() output for a given blob belongs. Keyed on the blob's content hash rather than an
    // asset id, matching how Engine.cpp caches prepared Studio places: re-uploading changes the hash and
    // so regenerates, and two assets with identical bytes share one directory.
    std::filesystem::path GetSegmentCacheDir(const std::string &blobHash, const Options &options);

    // BLOCKING. Cuts a stored video into loose HLS files inside outDir, which is created if needed.
    // Builds in a scratch directory and renames into place behind a marker file, so a reader never sees
    // a half-written playlist; existing complete output is reported as Success without re-running.
    Response Segment(const std::vector<unsigned char> &video, const Options &options,
                     const std::filesystem::path &outDir, Segments *out);

    // Reads back an already-populated cache directory without running ffmpeg. False if incomplete.
    static bool ReadExistingSegments(const std::filesystem::path &dir, Segments *out);

    /* Is this video ready to be served as HLS right now?
     *
     * Ask BEFORE telling the engine where to find a playlist. RBX::VideoStream::openContext copies the
     * location the emulator advertises into the demuxer as cdnUrl and never revisits it, so naming a
     * playlist is an irreversible promise -- and segmenting takes minutes. Advertising HLS for a video
     * that is not prepared is what forced every request to wait on ffmpeg, and a client that gives up
     * remembers the failure for the life of its process. Advertise the plain asset instead when this
     * returns false, and call RequestPreparation so the next load can be HLS. */
    bool IsPrepared(const std::string &blobHash, const Options &options);

    /* Segment a video in the background, if it is not already prepared or being prepared.
     *
     * Returns immediately; the work happens on this class's own worker. Deduplicated by cache
     * directory, so calling it on every request for the same cold video costs nothing after the first.
     * Takes the bytes by value because reading a blob is the caller's job -- database access belongs on
     * the event-loop thread, and this hands the caller's copy straight to ffmpeg. */
    void RequestPreparation(int64_t assetId, const std::string &blobHash, std::vector<unsigned char> video);

    // Worth reading the blob to hand to RequestPreparation? False once it is prepared, already queued,
    // or known to be something ffmpeg could not segment -- so an advertiser can fall back to the plain
    // asset without paying a multi-megabyte database read on every request.
    bool NeedsPreparation(const std::string &blobHash, const Options &options);

    static const char *ResponseToString(Response response);
private:
    void RunPreparationWorker();
    void ResolveTools();
    std::filesystem::path MakeTempDir();

    // BLOCKING. Reads container/codec/duration out of a buffer.
    Response Inspect(const std::vector<unsigned char> &input, Probe *out);

    // True when a buffer is already something MPEG-TS can carry, i.e. safe to stream-copy.
    static bool IsEngineReadable(const Probe &probe);

    Core *mCore;

    // Background preparation. One worker: segmenting is CPU-bound and a game server is running on the
    // same machine, so there is nothing to gain from doing several at once.
    std::atomic<bool>       mPreparationRunning {false};
    std::thread             mPreparationWorker;
    std::mutex              mPreparationMutex;
    std::condition_variable mPreparationCv;
    struct PendingPreparation {
        int64_t                    AssetId {0};
        std::filesystem::path      CacheDir;
        std::vector<unsigned char> Video;
    };
    std::deque<PendingPreparation> mPreparationQueue;
    std::unordered_set<std::string> mPreparing;  // cache dirs queued or in flight
    std::unordered_set<std::string> mUnusable;   // cache dirs whose video ffmpeg could not segment

    std::mutex            mResolveMutex;
    bool                  mResolved {false};
    std::filesystem::path mFfmpeg;
    std::filesystem::path mFfprobe;
};
}
