return {
    {
        Title = "docs.getting_started",
        Fallback = "Getting Started",
        Children = {
            {
                Title = "docs.getting_started.preface",
                Fallback = "Preface",
                File = "001-getting-started/001-preface.md"
            },
            {
                Title = "docs.getting_started.introduction",
                Fallback = "Introduction",
                File = "001-getting-started/002-introduction.md"
            }
        }
    },
    {
        Title = "docs.user_guides",
        Fallback = "User Guides"
    }
}
