/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: ClusterNullDerefGuard.cpp
// Started by: Hattozo
// Started on: 6/9/2026
// Description: (Disclaimer: Code generated by Claude Opus 4.8.)
//              (THIS IS AN ABSOLUTELY SLOP-CODED HACKJOB THAT WAS MADE TO
//               PREVENT 2023 ROBLOX FROM CRASHING ON LARGE PLACES!)
//   First-chance vectored exception handler that lets the 0.573 (x86)
//   player survive the 2026-format CORRUPTED UNIONS it cannot parse, without
//   touching the place data.
//
//   The 0.573 player's DeserializedClusterItem::process copy/scan loops dereference
//   a null cluster-item INPUT pointer at MANY sites: a loop does `lea esi,[edi+0x10]`
//   with edi (the input record ptr) == 0, giving esi=0x10, then `movq xmm0,[esi-0x10]`
//   reads address 0 -> AV. Each loop has several such derefs ([esi-0x10],[esi-8],
//   [esi-4],...) and there are multiple loops (captured live: 0x835FA6, then 0x836671).
//   The player's own UnhandledExceptionFilter swallows the AV into exit(1) (the
//   "silent crash"). Windows null-page mitigation blocks mapping address 0, and
//   hand-writing a trampoline per site is impractical -- so we install a first-chance
//   vectored handler scoped to the regular .text that (a) redirects each faulting
//   null-page read's base register into a big zero buffer so the counted copy loop
//   produces empty geometry and terminates normally, and (b) aborts the corrupt-union
//   CSG mesh builder (FuncB, RVA 0x99a410) via its own clean epilogue. The filter is
//   strict (AV + faulting address in the low null page + EIP within .text, excluding
//   the VMProtect .vmp sections) so VMProtect's own first-chance exceptions and all
//   unrelated faults pass through. x86-only.
#include "Patches.h"
#include <windows.h>
#include <atomic>
#include <cstdint>
#include <cstring>

#if defined(_M_IX86)
namespace NoobHook {
namespace {
uintptr_t gExeBase = 0;
uint8_t*  gZeroBuf = nullptr;
const size_t kZeroBufSize = 0x4000000;   // 64 MB of zeros
const size_t kZeroBufMid  = 0x2000000;   // redirect to the middle (room to climb both ways)
std::atomic<unsigned> gNullRedir { 0 };
std::atomic<unsigned> gClusterAbort { 0 };

// The corrupt-union CSG index builder ("FuncB") moves between player builds, so its abort RVAs
// must be pinned per build. Each variant is selected at install ONLY if the loaded image holds
// both the aligned-frame prologue at funcStart AND the clean epilogue at Epilogue -- so a wrong
// or stale build never arms (on 0.574 the old 0.573 epilogue target 0x99c68f is an alignment NOP
// whose tail is `add byte ptr [ecx-1],dl`, a wild heap write; gating on the real bytes makes that
// unreachable). Both builds happen to share the same frame (sub esp,0x2a8 -> saved edi at Ebp-0x2b0)
// and epilogue shape (pop edi;pop esi;mov esp,ebp;pop ebp;mov esp,ebx;pop ebx;ret 0x18).
struct FuncBVariant {
    const char* Name;
    uintptr_t   FuncStart;   // aligned-frame prologue: 53 8b dc 83 ec 08 83 e4 f0
    uintptr_t   RangeLo;     // first byte after the prologue (frame fully established)
    uintptr_t   RangeHi;     // one past the function's ret
    uintptr_t   Epilogue;    // clean exit: pop edi;...;mov esp,ebx;pop ebx;ret 0x18
    uint32_t    EspSub;      // abort sets Esp = Ebp - EspSub (the saved-edi slot)
};
const FuncBVariant kFuncBVariants[] = {
    { "0.573",         0x99a410, 0x99a431, 0x99c697, 0x99c68f, 0x2b0 },
    { "0.574.0.38814", 0x99b300, 0x99b31e, 0x99d544, 0x99d53c, 0x2b0 },
};
const FuncBVariant* gFuncB = nullptr;   // the matched variant, or null -> abort disarmed

// Compare n bytes at base+rva to sig, bounds-checked against SizeOfImage so a smaller/stale
// build can never make us read past the mapping.
bool BytesMatch(uintptr_t base, uintptr_t rva, const uint8_t* sig, size_t n) {
    auto* dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(base);
    if (dos->e_magic != IMAGE_DOS_SIGNATURE || dos->e_lfanew <= 0)
        return false;
    auto* nt = reinterpret_cast<const IMAGE_NT_HEADERS*>(base + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE)
        return false;
    if (rva + n > nt->OptionalHeader.SizeOfImage)
        return false;
    return std::memcmp(reinterpret_cast<const void*>(base + rva), sig, n) == 0;
}

const FuncBVariant* SelectFuncBVariant(uintptr_t base) {
    static const uint8_t kProlog[9]   = { 0x53, 0x8b, 0xdc, 0x83, 0xec, 0x08, 0x83, 0xe4, 0xf0 };
    static const uint8_t kEpilogue[10] = { 0x5f, 0x5e, 0x8b, 0xe5, 0x5d, 0x8b, 0xe3, 0x5b, 0xc2, 0x18 };
    for (const auto& v : kFuncBVariants) {
        if (BytesMatch(base, v.FuncStart, kProlog, sizeof(kProlog)) &&
            BytesMatch(base, v.Epilogue,  kEpilogue, sizeof(kEpilogue)))
            return &v;
    }
    return nullptr;
}

// Parse a memory-operand instruction's ModRM/SIB to find which GP register is
// the address BASE, and return a pointer to that register's slot in CONTEXT.
// Returns nullptr if the operand has no base register (abs disp32) or the base
// is ESP (never redirect the stack pointer). Reuses the same prefix/opcode skip
// as a length decoder.
DWORD* BaseRegSlot(const uint8_t* p, CONTEXT* c) {
    int i = 0;
    for (int g = 0; g < 8; g++) {
        uint8_t b = p[i];
        if (b==0xF3||b==0xF2||b==0x66||b==0x67||b==0x2E||b==0x3E||b==0x26||b==0x64||b==0x65||b==0x36||b==0xF0) i++;
        else break;
    }
    if (p[i]==0x0F) { i++; if (p[i]==0x38 || p[i]==0x3A) i++; }
    i++;                                  // opcode
    uint8_t modrm = p[i++];
    int mod = modrm >> 6, rm = modrm & 7;
    if (mod == 3) return nullptr;         // register direct, no memory operand
    int baseReg;
    if (rm == 4) {                        // SIB
        uint8_t sib = p[i++];
        int base = sib & 7;
        if (mod == 0 && base == 5) return nullptr; // no base (disp32)
        baseReg = base;
    } else if (mod == 0 && rm == 5) {
        return nullptr;                   // [disp32] absolute, no base
    } else {
        baseReg = rm;
    }
    if (baseReg == 4) return nullptr;     // ESP -- never touch
    DWORD* regs[8] = { &c->Eax, &c->Ecx, &c->Edx, &c->Ebx, &c->Esp, &c->Ebp, &c->Esi, &c->Edi };
    return regs[baseReg];
}

LONG CALLBACK ClusterNullDerefVeh(EXCEPTION_POINTERS* ep) {
    auto* r = ep->ExceptionRecord;
    if (r->ExceptionCode != EXCEPTION_ACCESS_VIOLATION || r->NumberParameters < 2)
        return EXCEPTION_CONTINUE_SEARCH;
    CONTEXT* c = ep->ContextRecord;
    uintptr_t eip = c->Eip;
    uintptr_t rva = eip - gExeBase;

    // --- Corrupt-union CSG index builder ("FuncB"): abort the whole function via its
    // own clean epilogue instead of band-aiding each access. FuncB builds a render mesh
    // from the deserialized cluster. For the 2026-format unions this player can't parse
    // (the SolidModel physics fails to load -- "Invalid TriangleMesh translationStride"),
    // the cluster holds null/garbage, so FuncB computes a garbage face count that overruns
    // its u16 index buffer (mov [edi+esi*2],ax / mov [edx+esi*2+2],ax) -> WRITE AV. On the
    // FIRST fault anywhere inside the function we jump to its normal early-exit epilogue,
    // returning eax=0 ("nothing built", what the function's own size-check early-out yields).
    // FuncB uses an aligned-stack frame; saved edi/esi sit at [ebp-EspSub]/[ebp-EspSub+4]
    // (push esi; push edi after sub esp,0x2a8), so pointing esp at the saved-edi slot lets
    //   pop edi; pop esi; mov esp,ebp; pop ebp; mov esp,ebx; pop ebx; ret 0x18
    // restore the callee-saved regs and unwind the frame exactly. The RVAs differ per build
    // (gFuncB is the variant matched at install); the union renders nothing but no crash.
    if (gFuncB && rva >= gFuncB->RangeLo && rva < gFuncB->RangeHi) {
        c->Esp = c->Ebp - gFuncB->EspSub;       // saved-edi slot in FuncB's frame
        c->Eip = gExeBase + gFuncB->Epilogue;   // FuncB clean early-exit epilogue
        c->Eax = 0;                             // "nothing built"
        unsigned n = ++gClusterAbort;
        if (n <= 8 || (n % 64) == 0)
            Out("NullGuard", "abort corrupt-union mesh builder @ rva 0x%zx -> epilogue (total=%u)", (size_t)rva, n);
        return EXCEPTION_CONTINUE_EXECUTION;
    }

    uintptr_t faultAddr = r->ExceptionInformation[1];
    if (faultAddr >= 0x10000)                       // only null+small-offset derefs
        return EXCEPTION_CONTINUE_SEARCH;
    // Anywhere in the regular .text (RVA 0x1000 .. 0x24b400a). The corrupt-union
    // null-derefs cascade across many functions (captured: 0x835FA6, 0x836671,
    // 0x999B98), all in .text. This range deliberately EXCLUDES the VMProtect
    // .vmp0/.vmp1 sections (RVA >= 0x3f53000), so VMProtect's own obfuscation
    // exceptions pass through untouched; combined with the null+small-offset
    // address filter above, only genuine null-pointer dereferences are handled.
    if (rva < 0x1000 || rva >= 0x24b400a)
        return EXCEPTION_CONTINUE_SEARCH;
    if (!gZeroBuf) return EXCEPTION_CONTINUE_SEARCH;
    DWORD* base = BaseRegSlot(reinterpret_cast<const uint8_t*>(eip), ep->ContextRecord);
    if (!base) return EXCEPTION_CONTINUE_SEARCH;
    // Redirect the loop's climbing base pointer into the middle of a big zero
    // buffer. The faulting read (and every subsequent read in this counted copy
    // loop) now hits zeros instead of address ~0, so the loop produces empty
    // geometry and terminates normally on its counter -- no walk into unmapped
    // memory, no crash. The output pointer (a different register) is untouched.
    *base = static_cast<DWORD>(reinterpret_cast<uintptr_t>(gZeroBuf) + kZeroBufMid);
    unsigned n = ++gNullRedir;
    if (n <= 8 || (n % 256) == 0)
        Out("NullGuard", "redirect cluster null-deref base @ rva 0x%zx (read was %p) total=%u",
            (size_t)rva, (void*)faultAddr, n);
    return EXCEPTION_CONTINUE_EXECUTION;             // re-run the load against zeros
}
} // anonymous namespace

// The 0.573 player's DeserializedClusterItem::process null-deref family and
// the corrupt-union CSG mesh builder are handled by the cluster null-deref
// VEH install below (InstallClusterNullGuard): it redirects every faulting
// null-page read in .text to a zero buffer, and aborts the mesh builder
// (RVA 0x99a410) via its own clean epilogue, so the 2026-format unions
// render nothing instead of crashing the client.
void Patches::InstallClusterNullGuard() {
    gExeBase = reinterpret_cast<uintptr_t>(GetModuleHandleW(nullptr));
    gZeroBuf = static_cast<uint8_t*>(VirtualAlloc(nullptr, kZeroBufSize, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE));
    // Pick the FuncB-abort variant whose prologue + epilogue signatures both match the loaded
    // build. If none match (unknown build), the abort stays disarmed and we never execute the
    // wild write a stale epilogue jump would land on. The null-page redirect is build-agnostic
    // and always runs.
    gFuncB = SelectFuncBVariant(gExeBase);
    AddVectoredExceptionHandler(1 /*first*/, ClusterNullDerefVeh);
    Out("NullGuard", "Installed cluster null-deref VEH (exe base %p, zerobuf %p, FuncB-abort %s)",
        (void*)gExeBase, (void*)gZeroBuf, gFuncB ? gFuncB->Name : "DISARMED (unknown build)");
}
} // namespace NoobHook
#endif
