/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: ClusterNullDerefGuard.cpp
// Started by: Hattozo
// Started on: 6/9/2026
// Description: (Disclaimer: Code generated by Claude Opus 4.8.)
//              (THIS IS AN ABSOLUTELY SLOP-CODED HACKJOB THAT WAS MADE TO
//               PREVENT 2023 ROBLOX FROM CRASHING ON LARGE PLACES!)
//   First-chance vectored exception handler that lets the 0.573 (x86)
//   player survive the 2026-format CORRUPTED UNIONS it cannot parse, without
//   touching the place data.
//
//   The 0.573 player's DeserializedClusterItem::process copy/scan loops dereference
//   a null cluster-item INPUT pointer at MANY sites: a loop does `lea esi,[edi+0x10]`
//   with edi (the input record ptr) == 0, giving esi=0x10, then `movq xmm0,[esi-0x10]`
//   reads address 0 -> AV. Each loop has several such derefs ([esi-0x10],[esi-8],
//   [esi-4],...) and there are multiple loops (captured live: 0x835FA6, then 0x836671).
//   The player's own UnhandledExceptionFilter swallows the AV into exit(1) (the
//   "silent crash"). Windows null-page mitigation blocks mapping address 0, and
//   hand-writing a trampoline per site is impractical -- so we install a first-chance
//   vectored handler scoped to the regular .text that (a) redirects each faulting
//   null-page read's base register into a big zero buffer so the counted copy loop
//   produces empty geometry and terminates normally, and (b) aborts the corrupt-union
//   CSG mesh builder (FuncB, RVA 0x99a410) via its own clean epilogue. The filter is
//   strict (AV + faulting address in the low null page + EIP within .text, excluding
//   the VMProtect .vmp sections) so VMProtect's own first-chance exceptions and all
//   unrelated faults pass through. x86-only.
#include "Patches.h"
#include <windows.h>
#include <atomic>
#include <cstdint>

#if defined(_M_IX86)
namespace NoobHook {
namespace {
uintptr_t gExeBase = 0;
uint8_t*  gZeroBuf = nullptr;
const size_t kZeroBufSize = 0x4000000;   // 64 MB of zeros
const size_t kZeroBufMid  = 0x2000000;   // redirect to the middle (room to climb both ways)
std::atomic<unsigned> gNullRedir { 0 };
std::atomic<unsigned> gClusterAbort { 0 };

// Parse a memory-operand instruction's ModRM/SIB to find which GP register is
// the address BASE, and return a pointer to that register's slot in CONTEXT.
// Returns nullptr if the operand has no base register (abs disp32) or the base
// is ESP (never redirect the stack pointer). Reuses the same prefix/opcode skip
// as a length decoder.
DWORD* BaseRegSlot(const uint8_t* p, CONTEXT* c) {
    int i = 0;
    for (int g = 0; g < 8; g++) {
        uint8_t b = p[i];
        if (b==0xF3||b==0xF2||b==0x66||b==0x67||b==0x2E||b==0x3E||b==0x26||b==0x64||b==0x65||b==0x36||b==0xF0) i++;
        else break;
    }
    if (p[i]==0x0F) { i++; if (p[i]==0x38 || p[i]==0x3A) i++; }
    i++;                                  // opcode
    uint8_t modrm = p[i++];
    int mod = modrm >> 6, rm = modrm & 7;
    if (mod == 3) return nullptr;         // register direct, no memory operand
    int baseReg;
    if (rm == 4) {                        // SIB
        uint8_t sib = p[i++];
        int base = sib & 7;
        if (mod == 0 && base == 5) return nullptr; // no base (disp32)
        baseReg = base;
    } else if (mod == 0 && rm == 5) {
        return nullptr;                   // [disp32] absolute, no base
    } else {
        baseReg = rm;
    }
    if (baseReg == 4) return nullptr;     // ESP -- never touch
    DWORD* regs[8] = { &c->Eax, &c->Ecx, &c->Edx, &c->Ebx, &c->Esp, &c->Ebp, &c->Esi, &c->Edi };
    return regs[baseReg];
}

LONG CALLBACK ClusterNullDerefVeh(EXCEPTION_POINTERS* ep) {
    auto* r = ep->ExceptionRecord;
    if (r->ExceptionCode != EXCEPTION_ACCESS_VIOLATION || r->NumberParameters < 2)
        return EXCEPTION_CONTINUE_SEARCH;
    CONTEXT* c = ep->ContextRecord;
    uintptr_t eip = c->Eip;
    uintptr_t rva = eip - gExeBase;

    // --- Corrupt-union CSG mesh builder: abort the whole function via its own
    // clean epilogue instead of band-aiding each access. FuncB (RVA 0x99a410)
    // builds a render mesh from the deserialized cluster. For the 2026-format
    // unions this 2023 player can't parse, the cluster holds null/garbage
    // pointers, so FuncB reads a near-null vertex base (many null-page reads)
    // and computes a garbage face count that overruns its u16 index buffer --
    // captured as a WRITE AV at 0x99c3ec (mov [edx+esi*2+2],ax). Redirecting the
    // null reads to zeros (below) only lets that garbage count survive into the
    // overflow, so for this function we instead jump, on the FIRST fault anywhere
    // inside it, to its normal early-exit epilogue at 0x99c68f, returning eax=0
    // ("nothing built" -- exactly what the function's own size-check early-out at
    // 0x99a45f yields). FuncB uses an aligned-stack frame with NO SEH; its saved
    // edi/esi sit at [ebp-0x2b0]/[ebp-0x2ac] (push esi; push edi after sub esp,
    // 0x2a8). Pointing esp at the saved-edi slot lets the epilogue
    //   pop edi; pop esi; mov esp,ebp; pop ebp; mov esp,ebx; pop ebx; ret 0x18
    // restore the callee-saved regs and unwind the frame exactly. The corrupt
    // union renders nothing instead of taking the whole client down.
    if (rva >= 0x99a431 && rva < 0x99c697) {
        c->Esp = c->Ebp - 0x2b0;            // saved-edi slot in FuncB's frame
        c->Eip = gExeBase + 0x99c68f;       // FuncB clean early-exit epilogue
        c->Eax = 0;                         // "nothing built"
        unsigned n = ++gClusterAbort;
        if (n <= 8 || (n % 64) == 0)
            Out("NullGuard", "abort corrupt-union mesh builder @ rva 0x%zx -> epilogue (total=%u)", (size_t)rva, n);
        return EXCEPTION_CONTINUE_EXECUTION;
    }

    uintptr_t faultAddr = r->ExceptionInformation[1];
    if (faultAddr >= 0x10000)                       // only null+small-offset derefs
        return EXCEPTION_CONTINUE_SEARCH;
    // Anywhere in the regular .text (RVA 0x1000 .. 0x24b400a). The corrupt-union
    // null-derefs cascade across many functions (captured: 0x835FA6, 0x836671,
    // 0x999B98), all in .text. This range deliberately EXCLUDES the VMProtect
    // .vmp0/.vmp1 sections (RVA >= 0x3f53000), so VMProtect's own obfuscation
    // exceptions pass through untouched; combined with the null+small-offset
    // address filter above, only genuine null-pointer dereferences are handled.
    if (rva < 0x1000 || rva >= 0x24b400a)
        return EXCEPTION_CONTINUE_SEARCH;
    if (!gZeroBuf) return EXCEPTION_CONTINUE_SEARCH;
    DWORD* base = BaseRegSlot(reinterpret_cast<const uint8_t*>(eip), ep->ContextRecord);
    if (!base) return EXCEPTION_CONTINUE_SEARCH;
    // Redirect the loop's climbing base pointer into the middle of a big zero
    // buffer. The faulting read (and every subsequent read in this counted copy
    // loop) now hits zeros instead of address ~0, so the loop produces empty
    // geometry and terminates normally on its counter -- no walk into unmapped
    // memory, no crash. The output pointer (a different register) is untouched.
    *base = static_cast<DWORD>(reinterpret_cast<uintptr_t>(gZeroBuf) + kZeroBufMid);
    unsigned n = ++gNullRedir;
    if (n <= 8 || (n % 256) == 0)
        Out("NullGuard", "redirect cluster null-deref base @ rva 0x%zx (read was %p) total=%u",
            (size_t)rva, (void*)faultAddr, n);
    return EXCEPTION_CONTINUE_EXECUTION;             // re-run the load against zeros
}
} // anonymous namespace

// The 0.573 player's DeserializedClusterItem::process null-deref family and
// the corrupt-union CSG mesh builder are handled by the cluster null-deref
// VEH install below (InstallClusterNullGuard): it redirects every faulting
// null-page read in .text to a zero buffer, and aborts the mesh builder
// (RVA 0x99a410) via its own clean epilogue, so the 2026-format unions
// render nothing instead of crashing the client.
void Patches::InstallClusterNullGuard() {
    gExeBase = reinterpret_cast<uintptr_t>(GetModuleHandleW(nullptr));
    gZeroBuf = static_cast<uint8_t*>(VirtualAlloc(nullptr, kZeroBufSize, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE));
    AddVectoredExceptionHandler(1 /*first*/, ClusterNullDerefVeh);
    Out("NullGuard", "Installed cluster null-deref VEH (exe base %p, zerobuf %p)", (void*)gExeBase, (void*)gZeroBuf);
}
} // namespace NoobHook
#endif
