/*
 * Copyright (C) 2026 Hattozo
 *
 * This file is part of noobWarrior.
 *
 * noobWarrior is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * noobWarrior is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with noobWarrior; if not, see
 * <https://www.gnu.org/licenses/>.
 */
// === noobWarrior ===
// File: CrashDiagnostics.cpp
// Started by: Hattozo
// Started on: 6/9/2026
// Description: (Disclaimer: Code generated by Claude Opus 4.8 so dat it can debug shit easier because roblox crashes a lot!!!!s)
//   SAVED / DISABLED crash-capture diagnostics for an injected engine.
//   *** THIS FILE IS NOT IN THE BUILD *** (it is intentionally left out of
//   Hook/CMakeLists.txt SOURCES) so it ships zero code. It is kept here so the
//   crash-capture instrumentation can be retrieved the next time the engine
//   crashes silently.
//
//   The 0.573 player crashes silently mid-session (no Roblox crash reporter, no
//   dump), and x32dbg can't attach (VMProtect anti-debug stalls the process). But
//   noobhook runs IN-process and is invisible to the anti-debug, so this captured
//   the crash from three vantage points -- an unhandled-exception filter, a
//   kernelbase!UnhandledExceptionFilter hook (the player's own top-level filter
//   swallows the AV into exit(1), so this reads the REAL EXCEPTION_POINTERS first),
//   and a RaiseFailFastException hook -- logging the faulting instruction + a
//   module+RVA backtrace (resolvable offline against the player PE even though
//   VMProtect encrypts the symbols) and writing a full minidump to %TEMP%.
//
//   NOTE: the dump is MiniDumpWithFullMemory (~2 GB) and fires on ANY unhandled
//   exception (including some the player throws-and-handles), so it can fill the
//   disk -- only enable it while actively hunting a crash, and consider dropping
//   to MiniDumpNormal.
//
//   TO RE-ENABLE:
//     1. Add "Patch/CrashDiagnostics.cpp" to SOURCES in Hook/CMakeLists.txt, and
//        add `dbghelp` to target_link_libraries(NoobWarrior.Hook PRIVATE ...).
//     2. Add `void InstallCrashDiagnostics();` to namespace NoobHook::Patches in
//        Patch/Patches.h.
//     3. In Hook.cpp Thread(), BEFORE MH_EnableHook(MH_ALL_HOOKS), call
//        Patches::InstallCrashDiagnostics();
//     4. (Optional) to also capture the exit caller-chain, re-add LogBacktrace()
//        to MyExitProcess / MyRtlExitUserProcess in Hook.cpp (impls below).
#include "Patches.h"
#include <windows.h>
#include <psapi.h>
#include <strsafe.h>
#include <dbghelp.h>
#include <MinHook.h>
#include <atomic>
#include <cstdint>

namespace NoobHook {
static void LogAddr(const char* tag, void* addr) {
    HMODULE mod = nullptr;
    GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        reinterpret_cast<LPCSTR>(addr), &mod);
    char name[MAX_PATH] = "?";
    if (mod) GetModuleBaseNameA(GetCurrentProcess(), mod, name, sizeof(name));
    uintptr_t rva = mod ? (reinterpret_cast<uintptr_t>(addr) - reinterpret_cast<uintptr_t>(mod))
        : reinterpret_cast<uintptr_t>(addr);
    Out("Crash", "  %s %s+0x%zx (abs %p, base %p)", tag, name, (size_t)rva, addr, (void*)mod);
}

void Patches::InstallCrashDiagnostics_LogBacktrace() {
    void* frames[40] = { 0 };
    USHORT n = CaptureStackBackTrace(0, 40, frames, nullptr);
    Out("Crash", "Backtrace (%u frames):", (unsigned)n);
    for (USHORT i = 0; i < n; i++)
        LogAddr("frame", frames[i]);
}

namespace {
using MiniDumpWriteDump_t = BOOL (WINAPI*)(HANDLE, DWORD, HANDLE, MINIDUMP_TYPE,
    PMINIDUMP_EXCEPTION_INFORMATION, PMINIDUMP_USER_STREAM_INFORMATION, PMINIDUMP_CALLBACK_INFORMATION);

std::atomic<bool> gDumpWritten { false };
void WriteCrashDump(EXCEPTION_POINTERS* ep) {
    bool expected = false;
    if (!gDumpWritten.compare_exchange_strong(expected, true))
        return;
    char tmp[MAX_PATH] = {0};
    GetTempPathA(sizeof(tmp), tmp);
    char path[MAX_PATH] = {0};
    StringCchPrintfA(path, sizeof(path), "%snoobhook_crash2_%lu.dmp", tmp, GetCurrentProcessId());
    HANDLE h = CreateFileA(path, GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h == INVALID_HANDLE_VALUE) {
        Out("Crash", "Failed to open dump file %s (err %lu)", path, GetLastError());
        return;
    }
    MINIDUMP_EXCEPTION_INFORMATION mei = {};
    mei.ThreadId = GetCurrentThreadId();
    mei.ExceptionPointers = ep;
    mei.ClientPointers = FALSE;
    // dbghelp forwards MiniDumpWriteDump to dbgcore on current Windows builds.
    // Resolve it only when a crash actually needs a dump so the manually mapped
    // Hyperion hook has no startup import on an otherwise-unloaded dbgcore.dll.
    HMODULE dbghelp = GetModuleHandleW(L"dbghelp.dll");
    if (!dbghelp)
        dbghelp = LoadLibraryW(L"dbghelp.dll");
    const auto miniDumpWriteDump = dbghelp
        ? reinterpret_cast<MiniDumpWriteDump_t>(GetProcAddress(dbghelp, "MiniDumpWriteDump"))
        : nullptr;
    BOOL ok = miniDumpWriteDump && miniDumpWriteDump(
        GetCurrentProcess(), GetCurrentProcessId(), h,
        static_cast<MINIDUMP_TYPE>(MiniDumpWithFullMemory | MiniDumpWithHandleData |
                                   MiniDumpWithThreadInfo),
        ep ? &mei : nullptr, nullptr, nullptr);
    CloseHandle(h);
    Out("Crash", "MiniDumpWriteDump %s -> %s", ok ? "OK" : "FAILED", path);
}

// Roblox captures crashes with an OUT-OF-PROCESS crashpad handler (no thread in this process ever
// touches dbgcore/dbghelp), so an in-process MiniDumpWriteDump hook can't reach its writer. But a
// first-chance VEH runs BEFORE crashpad's handler (proven: ClusterNullGuard's VEH already handles
// union AVs ahead of crashpad), and the heap corruption arrives here as a catchable
// RtlRaiseStatus(0xC0000374). So we catch the fatal code first-chance and write our OWN full-memory
// dump, then CONTINUE_SEARCH to let crashpad/the OS terminate as usual. Scoped to always-fatal
// noncontinuable codes so a benign throw-and-catch never triggers a 1+ GB dump.
LONG CALLBACK MyFatalDumpVeh(EXCEPTION_POINTERS* ep) {
    if (!ep || !ep->ExceptionRecord)
        return EXCEPTION_CONTINUE_SEARCH;
    DWORD code = ep->ExceptionRecord->ExceptionCode;
    if (code == 0xC0000374u /*STATUS_HEAP_CORRUPTION*/ ||
        code == 0xC0000409u /*STATUS_STACK_BUFFER_OVERRUN (__fastfail)*/) {
        Out("Crash", "Fatal 0x%08X caught first-chance in VEH -> writing full-memory dump before crashpad", (unsigned)code);
        LogAddr("fault", ep->ExceptionRecord->ExceptionAddress);
        WriteCrashDump(ep);
    }
    return EXCEPTION_CONTINUE_SEARCH;
}

LONG WINAPI MyUnhandledFilter(EXCEPTION_POINTERS* ep) {
    if (ep && ep->ExceptionRecord) {
        auto* r = ep->ExceptionRecord;
        Out("Crash", "UNHANDLED EXCEPTION code=0x%08X addr=%p flags=0x%lX nparams=%lu",
            (unsigned)r->ExceptionCode, r->ExceptionAddress, r->ExceptionFlags, r->NumberParameters);
        if (r->ExceptionCode == EXCEPTION_ACCESS_VIOLATION && r->NumberParameters >= 2)
            Out("Crash", "  ACCESS VIOLATION %s address %p",
                r->ExceptionInformation[0] == 1 ? "WRITE" : (r->ExceptionInformation[0] == 8 ? "EXEC" : "READ"),
                (void*)r->ExceptionInformation[1]);
        LogAddr("fault", r->ExceptionAddress);
    }
    Patches::InstallCrashDiagnostics_LogBacktrace();
    WriteCrashDump(ep);
    return EXCEPTION_EXECUTE_HANDLER;
}

void (WINAPI* pOrigRaiseFailFast)(PEXCEPTION_RECORD, PCONTEXT, DWORD) = nullptr;
void WINAPI MyRaiseFailFast(PEXCEPTION_RECORD er, PCONTEXT ctx, DWORD flags) {
    Out("Crash", "RaiseFailFastException code=0x%08X addr=%p flags=0x%lX",
        er ? (unsigned)er->ExceptionCode : 0, er ? er->ExceptionAddress : nullptr, flags);
    if (er) LogAddr("failfast", er->ExceptionAddress);
    Patches::InstallCrashDiagnostics_LogBacktrace();
    EXCEPTION_POINTERS ep = { er, ctx };
    WriteCrashDump((er || ctx) ? &ep : nullptr);
    if (pOrigRaiseFailFast) pOrigRaiseFailFast(er, ctx, flags);
}

// The player registers its OWN top-level filter (which logs and calls exit(1)),
// overriding our SetUnhandledExceptionFilter. But UnhandledExceptionFilter (the
// API) is still in the path -- hooking it lets us read the REAL underlying
// EXCEPTION_POINTERS (the faulting instruction + AV address) before the player's
// handler swallows it into a clean exit. This is the actual crash site.
LONG (WINAPI* pOrigUEF)(EXCEPTION_POINTERS*) = nullptr;
LONG WINAPI MyUEFHook(EXCEPTION_POINTERS* ep) {
    if (ep && ep->ExceptionRecord) {
        auto* r = ep->ExceptionRecord;
        Out("Crash", "*** UnhandledExceptionFilter: code=0x%08X addr=%p flags=0x%lX ***",
            (unsigned)r->ExceptionCode, r->ExceptionAddress, r->ExceptionFlags);
        if (r->ExceptionCode == EXCEPTION_ACCESS_VIOLATION && r->NumberParameters >= 2)
            Out("Crash", "  ACCESS VIOLATION %s address %p",
                r->ExceptionInformation[0] == 1 ? "WRITE" : (r->ExceptionInformation[0] == 8 ? "EXEC" : "READ"),
                (void*)r->ExceptionInformation[1]);
        LogAddr("fault-instr", r->ExceptionAddress);
        if (ep->ContextRecord) {
            auto* c = ep->ContextRecord;
#if defined(_M_IX86)
            Out("Crash", "  Eip=%p Esp=%p Ebp=%p Eax=%p Ecx=%p Edx=%p Esi=%p Edi=%p",
                (void*)c->Eip, (void*)c->Esp, (void*)c->Ebp, (void*)c->Eax,
                (void*)c->Ecx, (void*)c->Edx, (void*)c->Esi, (void*)c->Edi);
            LogAddr("ctx-eip", (void*)c->Eip);
#elif defined(_M_X64)
            Out("Crash", "  Rip=%p Rsp=%p Rbp=%p Rax=%p Rcx=%p Rdx=%p",
                (void*)c->Rip, (void*)c->Rsp, (void*)c->Rbp, (void*)c->Rax,
                (void*)c->Rcx, (void*)c->Rdx);
            LogAddr("ctx-rip", (void*)c->Rip);
#endif
        }
    }
    Patches::InstallCrashDiagnostics_LogBacktrace();
    WriteCrashDump(ep);
    return pOrigUEF ? pOrigUEF(ep) : EXCEPTION_EXECUTE_HANDLER;
}

// The player's own crash reporter (the in-process CrashReporter_* watcher threads, with
// dbghelp/dbgcore loaded) catches the fault and writes its dump BEFORE our UEF/fail-fast hooks
// ever see it -- heap corruption arrives as a catchable RtlRaiseStatus(0xC0000374) that the
// reporter's handler swallows, so SetUnhandledExceptionFilter/UnhandledExceptionFilter/
// RaiseFailFastException never fire. Rather than race the reporter, ride it: it writes a TRIAGE
// dump via dbgcore!MiniDumpWriteDump (dbghelp forwards there), so OR MiniDumpWithFullMemory into
// the type it asks for and its dump captures the whole heap instead -- catching exactly what the
// player catches, including load-phase heap-corruption crashes. ~1-1.5 GB per dump.
MiniDumpWriteDump_t pOrigMiniDumpWriteDump = nullptr;
BOOL WINAPI MyMiniDumpWriteDump(HANDLE proc, DWORD pid, HANDLE file, MINIDUMP_TYPE type,
                                PMINIDUMP_EXCEPTION_INFORMATION exc,
                                PMINIDUMP_USER_STREAM_INFORMATION usr,
                                PMINIDUMP_CALLBACK_INFORMATION cb) {
    MINIDUMP_TYPE upgraded = static_cast<MINIDUMP_TYPE>(type
        | MiniDumpWithFullMemory | MiniDumpWithHandleData
        | MiniDumpWithFullMemoryInfo | MiniDumpWithThreadInfo);
    Out("Crash", "MiniDumpWriteDump intercepted: type 0x%x -> 0x%x (forcing full memory)",
        (unsigned)type, (unsigned)upgraded);
    return pOrigMiniDumpWriteDump ? pOrigMiniDumpWriteDump(proc, pid, file, upgraded, exc, usr, cb) : FALSE;
}
} // anonymous namespace

// Registers the UEF + fail-fast hooks (the ExitProcess/RtlExitUserProcess hooks
// already live in Hook.cpp for the Goodbye ping; re-add LogBacktrace() there for
// the exit caller-chain). Call from Thread() BEFORE MH_EnableHook(MH_ALL_HOOKS).
void Patches::InstallCrashDiagnostics() {
    MH_CreateHookApi(L"kernel32",   "RaiseFailFastException",   (LPVOID)MyRaiseFailFast, (LPVOID*)&pOrigRaiseFailFast);
    MH_CreateHookApi(L"kernelbase", "UnhandledExceptionFilter", (LPVOID)MyUEFHook,       (LPVOID*)&pOrigUEF);
    SetUnhandledExceptionFilter(MyUnhandledFilter);
    // First-chance VEH that writes our own full-memory dump before Roblox's out-of-process crashpad
    // handler gets the crash. This is the path that actually fires (the UEF/fail-fast hooks above sit
    // downstream of crashpad and don't). The MiniDumpWriteDump hook stays as a belt-and-suspenders for
    // any crash a game DOES dump in-process.
    AddVectoredExceptionHandler(1 /*first*/, MyFatalDumpVeh);
    LoadLibraryW(L"dbgcore.dll");
    MH_CreateHookApi(L"dbgcore", "MiniDumpWriteDump", (LPVOID)MyMiniDumpWriteDump, (LPVOID*)&pOrigMiniDumpWriteDump);
    Out("Crash", "Crash diagnostics installed (first-chance full-dump VEH + UEF/fail-fast + MiniDumpWriteDump upgrade)");
}
} // namespace NoobHook
